### ISSUE TITLE
Glyphicons should be a dependency

### ISSUE THREAD

**Issue by zedtux** [twbs/bootstrap-sass#1000]
I'm looking to replace glyphicons by another font, and the solution is quite hard as it will then be boring for the future updates.

What I suggest is to move glyphicons in a gem and update the `README.md` in order to suggest to add that gem.
This would allow anyone to use another gem adding another font.

For instance, let say someone want to use the standard stack, he would have in his `Gemfile`

```
source 'https://rubygems.org'

...
gem 'bootstrap-sass'
gem 'font-glyphicons-sass'
gem 'sass-rails'
...
```

while another guy would like to use another font

```
source 'https://rubygems.org'

...
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'sass-rails'
...
```

This solution would avoid any difficulties to upgrade Bootstrap. Another advantage is that when an update of the font is done, only the glyphicons gem would be updated limiting the download size, and vise-versa.

**Comment by thomas-mcdonald** [comment]
Follow the instructions [here](https://github.com/twbs/bootstrap-sass#sass) to disable the Glyphicons component.

We don't usually change the file naming between minor versions, and v4 drops Glyphicons, so we are unlikely to make this change.
