### ISSUE TITLE
_grid-framework.scss calc-grid-column() issue

### ISSUE THREAD

**Issue by wcomartin** [twbs/bootstrap-sass#1003]
calc-grid-column()  is using $grid-columns instead of number passed to the loop-grid-columns

should be passing number of columns to the calc-grid-column function

this would allow having multiple grid types, example a 12 col grid and a 20 col grid in the same css

**Comment by cvrebert** [comment]
This isn't a Sass-specific issue, so please file it upstream at https://github.com/twbs/bootstrap/issues
Thanks!
