### ISSUE TITLE
.idea in your npm published package

### ISSUE THREAD

**Issue by rom1504** [twbs/bootstrap-sass#1006]
I've recently noticed that git globally ignored filed are included in a npm package when publishing it and as a result some files are published by accident. See https://github.com/npm/npm/issues/5673 (and I'm working on https://github.com/rom1504/npm-safeguard)

The last version published of this package contain files in a .idea/. It doesn't seem like they contain actually private information in this case, but publishing these files by accident can lead to publishing passwords or any other private information (that would be put in webstorm run configurations for example)

**Comment by glebm** [comment]
Thanks, fixed by specifying package.json `files`.
