### ISSUE TITLE
Compiling issue with Ruby Sass

### ISSUE THREAD

**Issue by oneblackcrayon** [twbs/bootstrap-sass#1014]
I am running a project that is using Ruby Sass to compile SCSS to CSS. When using the terminal command: `sass --watch scss:css -t expanded --sourcemap=none`
the last column of a grid breaks instead of float left.
When using `sass --watch scss:css -t compressed --sourcemap=none`
the last column of a grid floats left as expected.

Help.

**Comment by cvrebert** [comment]
@oneblackcrayon 
What version of Ruby Sass?
What version of bootstrap-sass?
Which web browser and version thereof?

I'm not sure whether we officially support compressed mode. Probably it's better to use a dedicated CSS minifier tool instead.

**Comment by cvrebert** [comment]
Closing due to lack of reply to my questions.

**Comment by oneblackcrayon** [comment]
My apologies. It may have been due to outdated Ruby Sass.
