### ISSUE TITLE
[Compass] Glyphicons not imported

### ISSUE THREAD

**Issue by joris-** [twbs/bootstrap-sass#1017]
Hi !

I have read lot of subjects but it don't solved my problem.
I'm new in Compass. I use Bootstrap Sass with glyphicon but they don't appear.   
![glyph](https://cloud.githubusercontent.com/assets/7545547/12798919/4dd2294c-cacc-11e5-9aac-3a3401cce444.png)

I have the latest version of Compass, fresh installed.
Some informations about my project : 
```
// Import Bootstrap for Sass  
@import "bootstrap-sprockets";  
@import "bootstrap";  
```

```
$bootstrap-sass-asset-helper: false;   
$icon-font-path: if($bootstrap-sass-asset-helper, "bootstrap/", "../fonts/bootstrap/") !default;
```
I try lot of path but the problem is not solve...

And css appear in firefox or chrome : 
```
@font-face {  
  font-family: 'Glyphicons Halflings';  
  src: url(font-path("../fonts/bootstrap/glyphicons-halflings-regular.eot"));  
  src: url(font-path("../fonts/bootstrap/glyphicons-halflings-regular.eot?#iefix")) format("embedded-opentype"), url(font-path("../fonts/bootstrap/glyphicons-halflings-regular.woff2")) format("woff2"), url(font-path("../fonts/bootstrap/glyphicons-halflings-regular.woff")) format("woff"), url(font-path("../fonts/bootstrap/glyphicons-halflings-regular.ttf")) format("truetype"), url(font-path("../fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular")) format("svg");  
}
```
If I remove `font-path` to get `url("../fonts/bootstrap/glyphicons-halflings-regular.eot");  ` for example, it's works perfect.  
Thanks for help.

Sorry for my bad english.

**Comment by cvrebert** [comment]
@joris- Why are you setting `$bootstrap-sass-asset-helper: false;` ?

**Comment by cvrebert** [comment]
Closing due to lack of reply to my question.
