### ISSUE TITLE
I Need Help Using Popovers with Bootstrap 2 (bootstrap-sass 2.3.2.2)

### ISSUE THREAD

**Issue by lightbe** [twbs/bootstrap-sass#1021]
I'm attempting popovers with bootstrap-sass for the first time in a Rails 4.2.5 application but without any success. 

Here is my setup in my Rails application.

CSS

**app/assets/stylesheets/custom.css.scss**

```
@import "bootstrap";

.popover { max-width: none; }
```
JS

**app/assets/javascripts/bootstrap.js.coffee**

```
jQuery ->
  $(".popover-map").popover({ html : true })
  # $("a[rel~=popover], .has-popover").popover()
```

**app/assets/javascripts/application.js** 

`//= require bootstrap`

**Rails partial code**

`<%= link_to("#{t :map_marfa_head}" , '#', class: "popover-map", rel: "popover", title: "#{t :map_marfa_head}", :"data-placement" => "bottom", :"data-content" => "#{render 'pages/map_marfa'}") %>`

This code worked when I was using the twitter-bootstrap-rails gem. The only difference was the @import statement in my stylesheet and the require statement in application.js. When using bootstrap-sass I get the following error when I view the page source.

```
TypeError: $(".popover-map").popover is not a function. (In '$(".popover-map").popover({
      html: true
    })', '$(".popover-map").popover' is undefined)
(anonymous function)bootstrap.self-a54a326f6cd027d08c61488151646f3b32c14ca968788b351d38b24c02b72000.js:2
firejquery.self-c64a74367bda6ef8b860f19e74df08927ca99d2be2ac934e9e92d5fd361e0da4.js:3232
fireWithjquery.self-c64a74367bda6ef8b860f19e74df08927ca99d2be2ac934e9e92d5fd361e0da4.js:3362
readyjquery.self-c64a74367bda6ef8b860f19e74df08927ca99d2be2ac934e9e92d5fd361e0da4.js:3582
completedjquery.self-c64a74367bda6ef8b860f19e74df08927ca99d2be2ac934e9e92d5fd361e0da4.js:3617
```
I have tried commenting out the statement that got the error and uncommenting the other statement in **app/assets/javascripts/bootstrap.js.coffee**. I still get the error that popover is not a function.

I also tried to add each of the following statements in **app/assets/javascripts/application.js** (one at a time).

`//= require bootstrap/bootstrap-popover`
`//= require bootstrap/bootstrap-popover.js`

For both require statements I get the following additional error.

```
TypeError: undefined is not an object (evaluating '$.fn.tooltip.Constructor')
(anonymous function)bootstrap-popover.self-f7ccec381e00cb3f9bde10f269cac0145d4926fa87aa0e0a184c5629a7c1d58d.js:37
(anonymous function)bootstrap-popover.self-f7ccec381e00cb3f9bde10f269cac0145d4926fa87aa0e0a184c5629a7c1d58d.js:114
```

From what I read on the main GitHub page the entire package is installed by default. I assume that means all I need to correct my setup somehow to use popovers. I'm not finding much online regarding this error. On GitHub I cannot find any documentation regarding versions of bootstrap-sass for Bootstrap 2. However I'm not sure if the version of Bootstrap is the issue.

UPDATE 3/2/2016 9:45 am CST: I decided to move my tooltip statement to be the first line. I get the same error for tooltip as well when I view the page source. It appears that the version of the gem I'm using does not include tooltip or popover like the twitter-bootstrap-rails does. I'm not sure what to do at this point since I'm new to using this gem.

Any help would be appreciated.

**Comment by lightbe** [comment]
I have given up on this. I went back to using gem twitter-bootstrap-rails. It appears the problem I was having with that gem had to do with the version of Ruby I had at the time. Since I've upgraded to the 2.3.0 I can use that one instead of bootstrap-sass to get my popover to work.

**Comment by slim1979** [comment]
i solve this problem by bringing my application.js to that
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require twitter/bootstrap
//= require_tree .

Gemfile
source 'https://rubygems.org'
ruby '2.3.1'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.2'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# gem 'bootstrap-sass'

gem 'therubyracer'
gem 'twitter-bootstrap-rails'
gem 'less-rails'
gem 'sprockets', '3.6.3'
gem 'jquery-rails'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'devise'
gem 'omniauth'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
maybe this can help. good luck
