### ISSUE TITLE
Extra-small screen rendering problem.

### ISSUE THREAD

**Issue by BrianTatum** [twbs/bootstrap-sass#1022]
I am using this gem in a project right now just on my development laptop. I have been testing the screen size with my computer and cell phone (Samsung Gal. S4). Everything is working right on my laptop, but it is not displaying the extra small classes on my phone. I can make my browser window smaller and see all the breakpoints including extra small but not on my phone. Does anyone know why this might be happening? Have been doing some searches for this issue but have not found anything. My apologies if this is not the right place to place this question.

**Comment by cvrebert** [comment]
@BrianTatum Note that the WebKit-based Android Browser isn't officially supported. (Android Chrome and Android Firefox are supported.)
Also, non-Sass-specific bugs should be filed at https://github.com/twbs/bootstrap ; if it reproduces with Bootstrap's precompiled CSS or with Bootstrap's LESS, the issue should be filed there instead.
What does http://getbootstrap.com/css/#responsive-utilities-tests show in Chrome on your device?

**Comment by cvrebert** [comment]
Closing due to lack of response to my question.
