### ISSUE TITLE
Meteor integration

### ISSUE THREAD

**Issue by nikolay211** [twbs/bootstrap-sass#1023]
is this package already supporting meteor or any plan on this ?

**Comment by cvrebert** [comment]
Meteor is supported in upstream's (https://github.com/twbs/bootstrap) Less-based Bootstrap v3 stable and Sass-based Bootstrap v4 alpha.

**Comment by cvrebert** [comment]
@twbs/sass Should we deem this WontFix?

**Comment by cvrebert** [comment]
Closing as WONTFIX per https://github.com/twbs/bootstrap/issues/20389
I advise using our npm package (https://www.npmjs.com/package/bootstrap-sass) instead, since Meteor now supports npm.
