### ISSUE TITLE
Add precompiled css to package

### ISSUE THREAD

**Issue by jcbvm** [twbs/bootstrap-sass#1029]
Currently I'm missing a precompiled css in the package like the bootstrap package has. It would be nice if this package also comes with a precompiled `.css` and `.min.css` file.

**Comment by thomas-mcdonald** [comment]
If you want to use the precompiled css you can just use the Bootstrap package? Not sure there would be much value in duplicating here.

**Comment by jcbvm** [comment]
Thanks, I know but if the css is precompiled there is no need for any bootstrap dep anymore, which would be nice.
