### ISSUE TITLE
Error when changing 'default' to 'application' in stylesheet tag from application.html.erb file

### ISSUE THREAD

**Issue by aleherzko** [twbs/bootstrap-sass#1033]
I am building a new app from scratch.

Versions of the enviroment are:
`Ruby 2.2.4
Rails 4.2.5.1`

Followed the instructions in this guide step by step. (Installed gems, put the `@import` lines, etc)

The error I get is the following:
`ExecJS::ProgramError in Studies#show
Showing ... application.html.erb where line #5 raised:
TypeError: Object doesn't support this property or method`

If I change to 'default' from 'application' in application.html.erb the Error disappears, but I do not get the bootstrap styling.

**Comment by cvrebert** [comment]
CC: @twbs/sass
