### ISSUE TITLE
Bootstrap SASS shows bugs in W3C CSS validator

### ISSUE THREAD

**Issue by akash-d** [twbs/bootstrap-sass#1034]
I have used bootstrap SASS for one my project. 
I imported bootstrap sass file in my master.scss file. When the checked it in W3C css validator i found these many bugs. Please let me know what the issue is .

![import](https://cloud.githubusercontent.com/assets/16605014/15205910/cb09eec2-1838-11e6-9d4f-083f9b56c9b5.jpg)

input[type="radio"], input[type="checkbox"]	Value Error : margin-top Too many values or values are not recognized : 1px \000009
2530		Feature -webkit-min-device-pixel-ratio doesn't exist for media screen ) { input[type="date"].form-control, input[type="time"].form-control, input[type="datetime-local"].form-control, input[type="month"].form-control { line-height: 34px; } input[type="date"].input-sm, .input-group-sm > input[type="date"].form-control, .input-group-sm > input[type="date"].input-group-addon, .input-group-sm > .input-group-btn > input[type="date"].btn, .input-group-sm input[type="date"], input[type="time"].input-sm, .input-group-sm > input[type="time"].form-control, .input-group-sm > input[type="time"].input-group-addon, .input-group-sm > .input-group-btn > input[type="time"].btn, .input-group-sm input[type="time"], input[type="datetime-local"].input-sm, .input-group-sm > input[type="datetime-local"].form-control, .input-group-sm > input[type="datetime-local"].input-group-addon, .input-group-sm > .input-group-btn > input[type="datetime-local"].btn, .input-group-sm input[type="datetime-local"], input[type="month"].input-sm, .input-group-sm > input[type="month"].form-control, .input-group-sm > input[type="month"].input-group-addon, .input-group-sm > .input-group-btn > input[type="month"].btn, .input-group-sm input[type="month"] { line-height: 30px; } input[type="date"].input-lg, .input-group-lg > input[type="date"].form-control, .input-group-lg > input[type="date"].input-group-addon, .input-group-lg > .input-group-btn > input[type="date"].btn, .input-group-lg input[type="date"], input[type="time"].input-lg, .input-group-lg > input[type="time"].form-control, .input-group-lg > input[type="time"].input-group-addon, .input-group-lg > .input-group-btn > input[type="time"].btn, .input-group-lg input[type="time"], input[type="datetime-local"].input-lg, .input-group-lg > input[type="datetime-local"].form-control, .input-group-lg > input[type="datetime-local"].input-group-addon, .input-group-lg > .input-group-btn > input[type="datetime-local"].btn, .input-group-lg input[type="datetime-local"], input[type="month"].input-lg, .input-group-lg > input[type="month"].form-control, .input-group-lg > input[type="month"].input-group-addon, .input-group-lg > .input-group-btn > input[type="month"].btn, .input-group-lg input[type="month"] { line-height: 46px; } }
2554	.radio input[type="radio"], .radio-inline input[type="radio"], .checkbox input[type="checkbox"], .checkbox-inline input[type="checkbox"]	Value Error : margin-top Too many values or values are not recognized : 4px \000009
2705	.form-control-feedback	Property pointer-events doesn't exist : none
2881	.btn	Property touch-action doesn't exist : manipulation
2893	.btn	Property user-select doesn't exist : none
2914	a.btn.disabled, fieldset[disabled] a.btn	Property pointer-events doesn't exist : none
3175	.caret	Value Error : border-top \000009 is not a color value : 4px solid \000009
3240	.dropdown-menu > .disabled > a:hover, .dropdown-menu > .disabled > a:focus	attempt to find a semi-colon before the property name. add it
3240	.dropdown-menu > .disabled > a:hover, .dropdown-menu > .disabled > a:focus	Property progid doesn't exist : DXImageTransform
3240	.dropdown-menu > .disabled > a:hover, .dropdown-menu > .disabled > a:focus	Parse Error DXImageTransform.Microsoft.gradient(enabled = false);
3243		Parse Error [: not-allowed; } .open > .dropdown-menu]
3280	.dropup .caret, .navbar-fixed-bottom .dropdown .caret	Value Error : border-bottom \000009 is not a color value : 4px solid \000009
3458	[data-toggle="buttons"] > .btn input[type="radio"], [data-toggle="buttons"] > .btn input[type="checkbox"], [data-toggle="buttons"] > .btn-group > .btn input[type="radio"], [data-toggle="buttons"] > .btn-group > .btn input[type="checkbox"]	Property pointer-events doesn't exist : none
3787	.navbar-brand	Value Error : padding inherit-20px is not a padding value : inherit-20px / 2 0
3804	.navbar-toggle	Value Error : margin-top Too many values or values are not recognized : inherit-34px / 2
3805	.navbar-toggle	Value Error : margin-bottom Too many values or values are not recognized : inherit-34px / 2
3824	.navbar-nav	Value Error : margin Too many values or values are not recognized : inherit-20px / 2 / 2 0
3852	.navbar-nav > li > a	Value Error : padding-top Too many values or values are not recognized : inherit-20px / 2
3853	.navbar-nav > li > a	Value Error : padding-bottom Too many values or values are not recognized : inherit-20px / 2
3863	.navbar-form	Value Error : margin-top Too many values or values are not recognized : inherit-34px / 2
3864	.navbar-form	Value Error : margin-bottom Too many values or values are not recognized : inherit-34px / 2
3932	.navbar-btn	Value Error : margin-top Too many values or values are not recognized : inherit-34px / 2
3933	.navbar-btn	Value Error : margin-bottom Too many values or values are not recognized : inherit-34px / 2
3935	.navbar-btn.btn-sm, .btn-group-sm > .navbar-btn.btn	Value Error : margin-top Too many values or values are not recognized : inherit-30px / 2
3936	.navbar-btn.btn-sm, .btn-group-sm > .navbar-btn.btn	Value Error : margin-bottom Too many values or values are not recognized : inherit-30px / 2
3938	.navbar-btn.btn-xs, .btn-group-xs > .navbar-btn.btn	Value Error : margin-top Too many values or values are not recognized : inherit-22 / 2
3939	.navbar-btn.btn-xs, .btn-group-xs > .navbar-btn.btn	Value Error : margin-bottom Too many values or values are not recognized : inherit-22 / 2
3942	.navbar-text	Value Error : margin-top Too many values or values are not recognized : inherit-20px / 2
3943	.navbar-text	Value Error : margin-bottom Too many values or values are not recognized : inherit-20px / 2
4418		Sorry, the at-rule @-webkit-keyframes is not implemented.
4500	.media, .media-body	Property zoom doesn't exist : 1
5448		Feature transform-3d doesn't exist for media all ), (-webkit-transform-3d) { .carousel-inner > .item { -webkit-transition: -webkit-transform 0.6s ease-in-out; -moz-transition: -moz-transform 0.6s ease-in-out; -o-transition: -o-transform 0.6s ease-in-out; transition: transform 0.6s ease-in-out; -webkit-backface-visibility: hidden; -moz-backface-visibility: hidden; backface-visibility: hidden; -webkit-perspective: 1000px; -moz-perspective: 1000px; perspective: 1000px; } .carousel-inner > .item.next, .carousel-inner > .item.active.right { -webkit-transform: translate3d(100%, 0, 0); transform: translate3d(100%, 0, 0); left: 0; } .carousel-inner > .item.prev, .carousel-inner > .item.active.left { -webkit-transform: translate3d(-100%, 0, 0); transform: translate3d(-100%, 0, 0); left: 0; } .carousel-inner > .item.next.left, .carousel-inner > .item.prev.right, .carousel-inner > .item.active { -webkit-transform: translate3d(0, 0, 0); transform: translate3d(0, 0, 0); left: 0; } }
5490	.carousel-control.left	attempt to find a semi-colon before the property name. add it
5490	.carousel-control.left	Property progid doesn't exist : DXImageTransform
5490	.carousel-control.left	Parse Error DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1);
5490	.carousel-control.left	Parse Error }
5498	.carousel-control.right	attempt to find a semi-colon before the property name. add it
5498	.carousel-control.right	Property progid doesn't exist : DXImageTransform
5498	.carousel-control.right	Parse Error DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1);
5498	.carousel-control.right	Parse Error }
5552	.carousel-indicators li	Value Error : background-color Too many values or values are not recognized : #000 \000009
5624	.text-hide	Value Error : font 0 is not a font-weight value : 0 / 0 a
5636		Sorry, the at-rule @-ms-viewport is not implemented.
5844		Sorry, the at-rule @-webkit-keyframes is not implemented.
6189	.popup-container .form-control	Value Error : color Too many values or values are not recognized : #1c1c1c l
6248		Unknown pseudo-element or pseudo-class :window-inactive

**Comment by quantumpacket** [comment]
What validator settings are you using? Please post the validation URL to the file in question.

**Comment by akash-d** [comment]
https://jigsaw.w3.org/css-validator/#validate_by_uri+with_options
This is the website . I just copy pasted as direct input and tried. After that I tried as a url..

**Comment by quantumpacket** [comment]
I'm asking for the URL AFTER you submit the URL to your CSS file.

For example:

> https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fexample.com&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by akash-d** [comment]
https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Ftesting.appinessworld.com%2Ffm1.1%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by cvrebert** [comment]
See http://getbootstrap.com/getting-started/#support-validators
