### ISSUE TITLE
Fail to import library

### ISSUE THREAD

**Issue by edin-rivera** [twbs/bootstrap-sass#1035]
I installed bootstrap-sass by npm.
`$ npm install bootstrap-sass`
Then, put the import on my sass file.
`@import 'bootstrap';`
When I run the compile task this import fails. I have the bootstrap-sass folder in the node-modules one. Should I use a relative path to it? or copy the bootstrap folder from node-modules to my sass folder?.

**Comment by MHanslo** [comment]
Sass `@import` isn't as clever as npm's `require()`. You'll need to give sass the relative path to bootstrap-sass within your node_modules folder. Something like:
`@import "../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap";`.

**Comment by cvrebert** [comment]
If MHanslo's suggestion didn't solve your problem, let us know.
