### ISSUE TITLE
Why some values are precomputed in variables?

### ISSUE THREAD

**Issue by olalonde** [twbs/bootstrap-sass#1037]
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L95

Why are those values pre-computed and how are they computed? It would be more useful if they were derived from the base font size.

**Comment by olalonde** [comment]
I've been trying to change the $font-size-base variable but it breaks some things like the navbar paddings.

**Comment by cvrebert** [comment]
Please file non-Sass-specific bugs upstream at https://github.com/twbs/bootstrap/issues
Thanks.

**Comment by olalonde** [comment]
Thanks, moved to https://github.com/twbs/bootstrap/issues/20119
