### ISSUE TITLE
How can i use less mixin?

### ISSUE THREAD

**Issue by Studioartcz** [twbs/bootstrap-sass#1039]
Hi, 

i am remaking less based project to sass project with bootstrap.
I have problem with this mixin:
`.img-thumbnail();`

https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_scaffolding.scss#L92

How can i call her?

**Comment by madalinignisca** [comment]
Can't you call it with the normal syntax?

.yourclass {
  @include img-thumbnail();
}

**Comment by cvrebert** [comment]
How-to questions are outside the scope of this bug tracker.
Please use community support channels instead: https://github.com/twbs/bootstrap/blob/master/README.md#community

**Comment by Studioartcz** [comment]
@madalinignisca What? It isn't sass mixin. IDE, compilator returning warnings.
