### ISSUE TITLE
Expose scss file in "style" field of package.json

### ISSUE THREAD

**Issue by ringods** [twbs/bootstrap-sass#1045]
Hello,

I am trying use `bootstrap-sass` via `npm`, `node-sass` and the `sass-module-importer`. The importer [documents](https://www.npmjs.com/package/sass-module-importer) this lookup strategy:

    1. Set a SCSS/Sass/CSS file on the "main" field of their package.json/bower.json
    2. Set a SCSS/Sass/CSS file on the "style" field of their package.json/bower.json
    3. Have a index.css file on the root of their module

If I look at the `bootstrap` npm package, [it uses](https://github.com/twbs/bootstrap/blob/7c86bc9664ddc3a1965fe91d7a0db97eb9348448/package.json#L21) the `style` field in `package.json`. It seems [this field is becoming a de facto standard](http://stackoverflow.com/questions/32037150/style-field-in-package-json).

Is it possible to get a similar setup and expose the main scss file in the `style` field of `package.json`?

**Comment by cvrebert** [comment]
We should also add a "sass" field for consistency with https://github.com/twbs/bootstrap/blob/ac1ea8c26ccb4b65d14bf207974854ca993ea4e5/package.json#L25
