### ISSUE TITLE
jQuery version range in bower.json is too broad, allows incompatible jQuery 3.0

### ISSUE THREAD

**Issue by bessieatrazoyo** [twbs/bootstrap-sass#1048]
bootstrap modals don't work with jQuery 3.0:  https://github.com/twbs/bootstrap/issues/16834

I found this to be the case.

I am installing bootstrap with bower and it depends on jQuery.  bootstrap-sass goes and gets version 3.0 of jQuery and then the modal won't work.

This is direct from bootstrap-sass:  https://github.com/twbs/bootstrap-sass/blob/3.3-stable/bower.json 

  "dependencies": {
    "jquery": ">= 1.9.0"
  },  
  "version": "3.3.6"

So, I think it would help if the version on the dependency was changed.

In the meantime, I did this:

`bower uninstall jquery`

`bower install jquery#2.2.4`

I had to confirm the uninstall.  I don't know what the best version of jQuery to use is.  2.2.4 let my modal work.

**Comment by bessieatrazoyo** [comment]
Thank you for the response.  I agree that this bower file would fix it:  [https://github.com/twbs/bootstrap/blob/7c86bc9664ddc3a1965fe91d7a0db97eb9348448/bower.json#L32]

If I go at this from a bower install perspective, what version of bootstrap do I need?

My current bower.json shows this:

`"bootstrap-sass-official": "^3.2.0",`

If I wanted to fix it to get the right bower_components/bootstrap-sass-official/bower.json, what should I change that line to??

**Comment by mattiasnordqvist** [comment]
@bessieatrazoyo I guess you can add another line with "jquery": "2.2.4", to force an upper version limit on jquery. That's what I did and it worked for me. The hardest thing will be to remember why you've added a jquery-dep to your project next time you visit bower.json.

Is this fix scheduled for release anytime soon?

**Comment by skinofstars** [comment]
So this has been fixed in the bower.json file, but hasn't be released. 

This breaks any new/current builds. Can we get a new release please?

**Comment by philipenelson** [comment]
Any update on this? Is there any new release planned?

**Comment by pixeldeluxe** [comment]
I use Codekit and I don't know how to degrade jQuery to previous version.

**Comment by embats** [comment]
@philipenelson, @skinofstars: A simple quickfix would be to reference the git-version in bower.json, like this:
```
 "dependencies": {
    "bootstrap-sass": "git@github.com:embats/bootstrap-sass.git"
  }
```

**Comment by cvrebert** [comment]
> Any update on this? Is there any new release planned?

Yes, upstream should release on Monday: https://github.com/twbs/bootstrap/milestone/34
bootstrap-sass should release same-day or soon after.
