### ISSUE TITLE
Support Bootstrap 4.0?

### ISSUE THREAD

**Issue by thelamborghinistory** [twbs/bootstrap-sass#1053]
Can we slowly adapt to the https://github.com/twbs/bootstrap/tree/v4-dev alpha branch and support Bootstrap 4.0 (not in the master though, of course)?

**Comment by Skaronator** [comment]
Bootstrap v4 is now built with SASS instead of LESS so there is no need to convert it to SASS. The SASS source can be found here: https://github.com/twbs/bootstrap/tree/v4-dev/scss

**Comment by thelamborghinistory** [comment]
Aww, I somehow thought this gem was doing something different, despite the clear name. My bad, sorry.

**Comment by zedtux** [comment]
@Skaronator Am I wrong or the bootstrap gem from where you have a link is not using SASS?

**Comment by thomas-mcdonald** [comment]
The Bootstrap 4 gem is available [here](https://github.com/twbs/bootstrap-rubygem).
