### ISSUE TITLE
How to change default style

### ISSUE THREAD

**Issue by knzudgt** [twbs/bootstrap-sass#1054]
I would like to customize the style of some of bootstrap's components, like the background-colour or the text colour attributes for tabs for instance, which are defined by `nav` and `nav-tabs` classes.
Is that possible? Would it be enough to add custom style for these classes in my custom stylesheet in order to overwrite the default style? For instance, would the following lines of code added to my `custom.css.scss` file be enough to change the background colour and the border radius of my tabs?

```
@import "bootstrap-sprockets";
@import "bootstrap";

.nav-tabs {
  background-color: #d9d9d9;
  border-radius: 4px;
}
```

**Comment by cvrebert** [comment]
In general, your options are to either set Bootstrap's variables to your desired values (which is preferred when possible), or to override the CSS with your own CSS like in your code snippet. The exact CSS selectors necessary for such overrides will depend on the selectors in the Bootstrap CSS for the component in question.
For questions about the intricacies of overriding specific components, please ask on StackOverflow, IRC, or Slack. See https://github.com/twbs/bootstrap/blob/master/README.md#community for links to those forums.
