### ISSUE TITLE
Large file sizes when using import to bring in specific JS components

### ISSUE THREAD

**Issue by tysonnero** [twbs/bootstrap-sass#1055]
Using ES6 and Webpack, if I try to bring in specific Bootstrap JS components, my file size grows tremendously.
```
import 'bootstrap-sass/assets/javascripts/bootstrap/collapse';
import 'bootstrap-sass/assets/javascripts/bootstrap/tab';
import 'bootstrap-sass/assets/javascripts/bootstrap/transition';
```
Including the above imports produces a file with a size of 700+ kb un-minified and 90+ kb minified. When these lines are removed, I get 10kb un-minified and 1.59 kb minified. The baseline sizes include some minimal js I have.

Does this make sense?

**Comment by cvrebert** [comment]
Since this doesn't sound Sass-specific, please file your bug upstream at https://github.com/twbs/bootstrap
Thanks.

**Comment by george-norris-salesforce** [comment]
https://github.com/twbs/bootstrap/issues/20634
