### ISSUE TITLE
Caught some syntax errors on `mixins/_buttons.scss`

### ISSUE THREAD

**Issue by BorelTung** [twbs/bootstrap-sass#1056]
```
  &:active,
  &.active,
  .open > &.dropdown-toggle {
    color: $color;
    background-color: darken($background, 10%);
        border-color: darken($border, 12%);

    &:hover,
    &:focus,
    &.focus {
      color: $color;
      background-color: darken($background, 17%);
          border-color: darken($border, 25%);
    }
  }
  &:active,
  &.active,
  .open > &.dropdown-toggle {
    background-image: none;
  }
```

**Comment by BorelTung** [comment]
It seems something wrong with this [line](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/mixins/_buttons.scss#L24)

**Comment by BorelTung** [comment]
with node-sass v3.8.0

**Comment by cvrebert** [comment]
@BorelTung So when you say "syntax error", are you getting an error message, or...?
Also, what Sass compiler are you using?

**Comment by BorelTung** [comment]
@cvrebert Thank you for your reply. This may be related to [react-redux-starter-kit issue#474](https://github.com/davezuko/react-redux-starter-kit/issues/474)

**Comment by cvrebert** [comment]
@BorelTung Again, please clarify precisely what you mean by "syntax error".

**Comment by cvrebert** [comment]
Closing due to lack of reply to my question.
