### ISSUE TITLE
support for sassc gem

### ISSUE THREAD

**Issue by djudd** [twbs/bootstrap-sass#1059]
It appears that libsass is supported: https://github.com/twbs/bootstrap-sass/issues/494

However, the gemspec specifies the Ruby sass gem, AFAICT only to reference it here: https://github.com/twbs/bootstrap-sass/blob/master/lib/bootstrap-sass.rb#L59-L66

It would be great if the sassc gem, which provides libsass, was supported as well.

**Comment by glebm** [comment]
SassC also [depends](https://github.com/sass/sassc-ruby/blob/90ce13e4f06a32e842a90afdecfd52b603e00552/sassc.gemspec#L32) on the Sass gem. It works out of the box as a drop-in replacement.
