### ISSUE TITLE
z-index for .modal

### ISSUE THREAD

**Issue by tahahojati** [twbs/bootstrap-sass#1067]
In bootstrap cdns I see that .modal has a z-index of 1050.  This is not the case in this repository. Line 25 of _modal.scss is   z-index: $zindex-modal-background;  and that value is 1040. This causes the problem where the modal is inactive because it is under the backdrop.  That line must be substituted with   z-index: $zindex-modal;

**Comment by cvrebert** [comment]
[Line 25 of `_modal.scss`](https://github.com/twbs/bootstrap-sass/blob/5d6b2ebba0c2a5885ce2f0e01e9218db3d3b5e47/assets/stylesheets/bootstrap/_modals.scss#L24) is already `z-index: $zindex-modal;`

**Comment by cvrebert** [comment]
Closing due to lack of reply.

**Comment by craft37** [comment]
@cvrebert Have this issue. 
modal-backdrop with lowest z-index covers the modal.
