### ISSUE TITLE
Rails 5 bootstrap-sass navbar mobile responsiveness not working

### ISSUE THREAD

**Issue by varbonida** [twbs/bootstrap-sass#1068]
I am using Rails 5 with **bootstrap-sass gem**.

Why is it the responsiveness of the Navbar is not working.

Here is my **app/assets/stylesheets/application.css.sccs** 
```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS/SCSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 * 
 *
 */

@import "bootstrap-sprockets";
@import "bootstrap";
```

This is my html 
```
<div class="bs-example">
    <nav id="myNavbar" class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Profile</a></li>
                    <li ><a href="#">Messages</a></li>
                </ul>                
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>
</div>
```

Any help ?

**Comment by kkaliannan** [comment]
Having the same issue here, were you able to figure this one out?

**Comment by davicitoafc** [comment]
I am having the same issue as well

**Comment by marcelarubim** [comment]
You are coding with the documentation of Bootstrap 3, but your gem is Boostrap 4 Alpha version. Look at the new documentation: [http://v4-alpha.getbootstrap.com/components/navbar/].
A nice tutorial: [https://rubyplus.com/articles/3981-Integrating-Twitter-Bootstrap-4-with-Rails-5]
And the official gem link: [https://github.com/twbs/bootstrap-rubygem]

**Comment by Amorim2014** [comment]
I am using Rails 5 en Bootstrpa, but has error in Sidebar....loook...nedd help.

**Here is my app/assets/stylesheets/application.css.sccs**
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS/SCSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 *= require bootstrap
 *= require_tree .
 *= require_self
-----------------
My app/assets/javascripts/application.js

// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file. JavaScript code in this file should be added after the last require_* statement.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//= require bootstrap
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require turbolinks
//= require_tree .
________________________________
My Gemfile

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
gem "twitter-bootstrap-rails"
gem 'rails-assets-bootstrap', source: 'https://rails-assets.org'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
__________________
My HTML

This is my html

<div class="bs-example">
    <nav id="myNavbar" class="navbar navbar-default" role="navigation">
        
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>
            
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Profile</a></li>
                    <li ><a href="#">Messages</a></li>
                </ul>                
            </div>
        </div>
    </nav>
</div>
_________________________
Result
![capturar](https://cloud.githubusercontent.com/assets/6577393/23308115/cec6dd4e-fa88-11e6-9563-496755bc0c8c.PNG)

**Comment by marcelarubim** [comment]
First, you're not using the official gem for bootstrap, but a forked one: [twitter-bootstrap-rails](https://github.com/seyhunak/twitter-bootstrap-rails)

There is a tutorial avaliable in: http://railscasts.com/episodes/328-twitter-bootstrap-basics
Follow the instruction and it will be nice!

Ps.: in 'application.css.scss' (the extension should be only .scss) you are importing the wrong way. The correct way if you still using twitter-bootstrap-rails gem:
`@import "twitter/bootstrap/bootstrap";`

If you change for the official one, only:
`@import "bootstrap";`

And delete all the following lines:
```
*= require bootstrap
*= require_tree .
*= require_self
```

**Comment by soumitcse** [comment]
Please check your application.html.erb file in the header section add this

  <meta charset="UTF-8">
    <meta name=viewport content="width=device-width, initial-scale=1">

**Comment by soumitcse** [comment]
Please check your application.html.erb file in the header section add this
`  <meta charset="UTF-8">
    <meta name=viewport content="width=device-width, initial-scale=1">`

**Comment by piga** [comment]
I added `//= require bootstrap-sprockets` like I saw at [http://www.rubydoc.info/gems/bootstrap-sass/3.3.6#a-ruby-on-rails](url)

**Comment by vieyrapy** [comment]
@soumitcse que grande me solucionaste la vida :)
