### ISSUE TITLE
compiled bootstrap file does not match original bootstrap file

### ISSUE THREAD

**Issue by kimbaudi** [twbs/bootstrap-sass#1071]
When I compiled bootstrap from LESS using the grunt command `grunt dist`, I expected the bootstrap files to match the original since I didn't make any changes to any .less files. However, its not exactly the same. I am on a Windows 7 64 bit machine using npm.

Here are the steps I took:
1. `npm install -g grunt-cli`
2. `cd` to bootstrap file with less source code
3. `npm install`
4. `grunt dist`

I have node version 6.2.1, npm version 3.10.5, grunt-cli version 1.2.0

Original bootstrap.css snippet:
```
html {
  font-family: sans-serif;
  -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
}
```

Grunt compiled bootstrap.css snippet:
```
html
{
    font-family: sans-serif;

        -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
```

How come my compiled bootstrap files do not exactly match the pre-compiled bootstrap files? How can I make sure my compiled files match the pre-compiled ones (assuming I don't modify any of the original .LESS files)?

**Comment by cvrebert** [comment]
You seem to have the wrong project. This is the Sass port of Bootstrap, not the Less-based mainline Bootstrap project. We can't help you with Less stuff here.
