### ISSUE TITLE
Why are vendor-prefixes mixins still used if depreciated and autoprefixer is requirement?

### ISSUE THREAD

**Issue by Soundvessel** [twbs/bootstrap-sass#1072]
[Documentation states](http://getbootstrap.com/getting-started/#download-autoprefixer) that autoprefixer is required however shouldn't that replace use of vendor prefixes mixins? I thought I could simply remove that import from my `_mixins.scss` file but other components are still using those mixins.

**Comment by cvrebert** [comment]
They are used for the sake of backward-compatibility since the Autoprefixer requirement was added midway into Bootstrap v3's life. Didn't want to cause extra breakage for folks who don't have Autoprefixer in their build.
They have been fully eliminated in v4.
