### ISSUE TITLE
Tooltips not rendering with bootstrap styles

### ISSUE THREAD

**Issue by ERPedersen** [twbs/bootstrap-sass#1073]
Tooltips doesn't seem to work with the current version. Activating the tooltip just shows a native browser tooltip, and doesn't seem to load the styling from bootstrap.

`<a id="fubar" href="#" data-toggle="tooltip" title="Ohoy">Hover</a>`

`$(document).ready(function(){
    $('#fubar').tooltip(); 
});`

**Comment by cvrebert** [comment]
I assume you're referring to v3.3.7? Does it work with v3.3.6?

**Comment by XoniycL** [comment]
placement and rendering doesn't work with 3.3.6 and 3.3.7
![2016-09-19 8 38 22](https://cloud.githubusercontent.com/assets/18523568/18632286/3e8f92b2-7ea9-11e6-9830-020f35085ffd.png)

**Comment by ERPedersen** [comment]
It seems I had some other functionality running, which interfered with the tooltips. I'll close this issue
