### ISSUE TITLE
Sass @import "bootstrap-compass" + @import "bootstrap" issue using Compass.

### ISSUE THREAD

**Issue by pr0jectile** [twbs/bootstrap-sass#1075]
I've created a new project using `compass create <my-project-name> -r bootstrap-sass --using bootstrap` and when I open styles.scss I see the following code: 

```
// Import Bootstrap Compass integration
@import "bootstrap-compass";

// Import custom Bootstrap variables
@import "bootstrap-variables";

// Import Bootstrap for Sass
@import "bootstrap";
```

Now I am using PHPStorm and `@import "bootstrap-compass";` and `@import "bootstrap";` are showing up as red lines. Upon hover it says **Cannot resolve file 'bootstrap'** and **Cannot resolve file 'bootstrap-compass'**.

I've tried to run the following command (again):

```
$ gem install bootstrap-sass
Successfully installed bootstrap-sass-3.3.7
Parsing documentation for bootstrap-sass-3.3.7
Done installing documentation for bootstrap-sass after 0 seconds
1 gem installed
$ 
```

But it doesn't fix the error. 

My project tree looks like this after a fresh `compass create my-new-project -r bootstrap-sass --using bootstrap`:

```
.
├── config.rb
├── fonts
│   └── bootstrap
│       ├── glyphicons-halflings-regular.eot
│       ├── glyphicons-halflings-regular.svg
│       ├── glyphicons-halflings-regular.ttf
│       ├── glyphicons-halflings-regular.woff
│       └── glyphicons-halflings-regular.woff2
├── javascripts
│   ├── bootstrap
│   │   ├── affix.js
│   │   ├── alert.js
│   │   ├── button.js
│   │   ├── carousel.js
│   │   ├── collapse.js
│   │   ├── dropdown.js
│   │   ├── modal.js
│   │   ├── popover.js
│   │   ├── scrollspy.js
│   │   ├── tab.js
│   │   ├── tooltip.js
│   │   └── transition.js
│   ├── bootstrap-sprockets.js
│   ├── bootstrap.js
│   └── bootstrap.min.js
├── sass
│   ├── _bootstrap-variables.scss
│   └── styles.scss
└── stylesheets
    └── styles.css
```

What's the best way to correct this issue?

**Comment by steinmb** [comment]
Mine look like:

    // Default variables.
    @import "default-variables";

    // Bootstrap Framework.
    @import '../bootstrap/assets/stylesheets/bootstrap';

    // Base-theme overrides.
    @import 'overrides';

**Comment by pr0jectile** [comment]
Are you creating the projects with `compass create <my-project-name> -r bootstrap-sass --using bootstrap`?

**Comment by steinmb** [comment]
No. I created my by hand.

**Comment by pr0jectile** [comment]
Thanks for letting me know. But that doesn't help the situation for what the README tell you to do.

Basically, I think the command I mentioned above may need to be looked into and include partials.
