### ISSUE TITLE
Don't use @extend with classnames

### ISSUE THREAD

**Issue by viveleroi** [twbs/bootstrap-sass#1077]
SCSS and `@extend` are wildly troublesome when used with classnames because they extend any instances where the target is the last piece of a selector. Now that you're using the following on line 109 of `_navs.scss`:

    &.nav-justified {
      @extend .nav-justified;
      @extend .nav-tabs-justified;
    }

And we use the following in our own scss:

`.nav-tabs:not(.nav-justified) { ... }`

The compiled output is:

`.nav-tabs:not(.nav-justified):not(.nav-tabs.nav-justified) { ... }`

Which is invalid CSS and breaks our styling.

When commenting out line 109 in your file, it becomes:

`.nav-tabs:not(.nav-justified)`

If you're intending to *share* styles within your own scss, I would highly advise using a placeholder so you don't copy unwanted styles, especially since this project is intended to allow for custom compilation by users.

*Edit: Now that I review your history though, it's been this way since 2013. This is how `@extend` behaves so it's a valid complaint. I have to assume that it's only now compiling incorrectly because of a sass update.

**Comment by cvrebert** [comment]
Yeah, I think there might be an existing action item buried somewhere to use @include instead of @extend.

**Comment by cvrebert** [comment]
Oh, wait, wrong repo. I thought this was Bootstrap 4 instead of bootstrap-sass.

Seems like it might be too late in Bootstrap 3's lifecycle to change something like this.

**Comment by cvrebert** [comment]
@twbs/sass Should this be deemed WontFix?

**Comment by glebm** [comment]
Won't fix. This is not a trivial fix to perform automatically, and would break backwards compatibility. This is not an issue in Bootstrap 4.
