### ISSUE TITLE
Please reopen Issue 714

### ISSUE THREAD

**Issue by MincePie** [twbs/bootstrap-sass#1078]
https://github.com/twbs/bootstrap-sass/issues/714

I am having the same problem as outlined in Issue 714. I have tried every suggestion discussed by those who found issue 714 whilst it was open for comments.

If I require bootstrap-sprockets before jQuery, then my bootstrap dropdown menu works, but all my other js doesnt work. If I move it below jQuery, then all my other js works but the drop down menu does not. I am only in development mode at the moment, I have read about a lot of users who find a solution that serves them in development but not in production. Surely there is a universal answer to this. 

At the moment I can't even get this working in development environment.

http://stackoverflow.com/questions/39304217/rails-4-which-order-to-put-jquery-and-bootstrap

Is there a solution to Issue 714?

**Comment by cvrebert** [comment]
Based on your StackOverflow description, I would suspect that there is an incompatibility between Bootstrap's JavaScript and one of the many other JavaScripts that you're including in your application. I would suspect jQuery UI in particular, but that's merely a guess.

Per http://getbootstrap.com/javascript/#callout-third-party-libs , we are unfortunately unable to assist you in debugging such incompatibilities.
