### ISSUE TITLE
assets\javascripts\bootstrap files missing official header script

### ISSUE THREAD

**Issue by BryanFarrell** [twbs/bootstrap-sass#1082]
If you look at the official pre-bundled assets\javascripts\bootstrap.js file the very first section contains the official bootstrap header comment and the jQuery requirement check and the jQuery version check.  

This javascript code is not included in the assets\javascripts folder or the bootstrap sub-folder so even when correctly bundling the individual files in the correct order you do not end up with an identical bootstrap.js file because it is missing the jQuery requirement check and the jQuery version check.

I was able to work around this by creating a 'header.js' file and putting it in my own assets folder (outside of the bootstrap-sass assets folder). Then using 'gulp-concat' I combined my file with the files from the bootstrap-sass assets folder.  Here is an example of the 'header.js' file I created and how I did this in my 'gulpfile.js'.

header.js
```
/*!
 * Bootstrap v3.3.6 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under the MIT license
 */

if (typeof jQuery === 'undefined') {
  throw new Error('Bootstrap\'s JavaScript requires jQuery')
}

+function ($) {
  'use strict';
  var version = $.fn.jquery.split(' ')[0].split('.')
  if ((version[0] < 2 && version[1] < 9) || (version[0] == 1 && version[1] == 9 && version[2] < 1) || (version[0] > 2)) {
    throw new Error('Bootstrap\'s JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3')
  }
}(jQuery);
```

gulpfile.js
```
var gulp = require('gulp');
var plumber = require('gulp-plumber');
var concat = require('gulp-concat');

var BOOTSTRAP = [
  '/assets/js/bootstrap/header.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/transition.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/alert.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/button.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/carousel.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/collapse.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/modal.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/popover.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/tab.js',
  '/lib/bootstrap-sass/assets/javascripts/bootstrap/affix.js'
];
gulp.task('javascript:bootstrap-concat', function () {
    return gulp.src(BOOTSTRAP)
      .pipe(plumber())
      .pipe(concat('bootstrap.js'))
      .pipe(gulp.dest('/js'));
});
```

As you can see I now have to maintain that header to have my 'javascript:bootstrap-concat' gulp task create an identical version of the pre-bundled 'bootstrap.js'.  I did this as a requirement so I know I am building the full 'bootstrap.js' file correctly.  From here I can then modify the BOOTSTRAP array to only include the bootstrap features I plan on using and reduce the overhead of my applications page request size.

Would it be possible for you guys to include this 'header.js' file (or whatever name you want to give it) as an official javascript file in the repo so that when someone like myself manually bundles the javascript files it has the missing jQuery requirement check and the jQuery version check at the top?

**Comment by cvrebert** [comment]
Please file JavaScript issues upstream at https://github.com/twbs/bootstrap/issues since they're not Sass-specific. Thanks.
