### ISSUE TITLE
What does the function in the _grid.scss for?

### ISSUE THREAD

**Issue by wufenfen** [twbs/bootstrap-sass#1083]
Firstly, I  am a newbie.  I am reading bootstrap's souce code about grid system. To my understanding, the function make-grid is the one that make the whole thing works( Of course, there are make-row, container-fixed etc.).  My confusion is what do some mixin functions in _grid.scss for, such as make-**-column, make-**-column-offset ...  I don't see they are used in any places.  So, i consider them as redundant codes, am I right?

**Comment by cvrebert** [comment]
They are included for the benefit of Sass users who wish to make their own custom classes behave like grid rows/columns/etc., which can be accomplished by using the mixin in their custom class.
They are indeed not used by the framework itself.
