### ISSUE TITLE
eyeglass import is not consistent with rails/bower/node/etc

### ISSUE THREAD

**Issue by fivetanley** [twbs/bootstrap-sass#1085]
In [#1007](https://github.com/twbs/bootstrap-sass/pull/1007), Eyeglass support was added. This was a great improvement for us as it allowed us to pull more dependencies in through npm.

We have a sass library that works both in Rails's asset pipeline and in other ecosystems. The eyeglass import having a different name in Eyeglass unfortunately makes us choose between only supporting building through eyeglass, or not having eyeglass support and having everything else work.

For example, in Rails:

``` scss
@import "bootstrap";
```

But in eyeglass:

``` scss
@import "bootstrap-sass/bootstrap";
```

If you look at the README in its current state you can see how consistent it is until you get down to the Eyeglass section.

This could be fixed by adding a `name` field to the `eyeglass` section package.json for `bootstrap-sass`:

``` json
{
  "name": "bootstrap-sass",
  "version": "1.1.0",
  "eyeglass": {
    "name": "bootstrap",
    "needs": "^0.6.7",
    "exports": "eyeglass-exports.js"
  }
```

For consistency, I think it would be great if you could `@import "bootstrap"` in any ecosystem and have it work.

This would be a breaking change for anybody currently using eyeglass, but an easy fix to implement (change your import statements to "@import bootstrap").

**Comment by fivetanley** [comment]
@iammikecohen I'd love to hear your input here as you championed the first pull request. There may be a historical reason for the name difference that I'm missing.

**Comment by iammikecohen** [comment]
Yes, this should absolutely be done.

**Comment by cvrebert** [comment]
@glebm I assume this is out of the question due to SemVer?
