### ISSUE TITLE
Rails Setup Instructions Change

### ISSUE THREAD

**Issue by rebelweb** [twbs/bootstrap-sass#1086]
I have had problems in the past maintaining compatibility between adding this to rails and jquery-ui due to changing the application.css to application.scss.

I have a suggestion, i feel all bootstrap includes and variables should be in a separate file  __bootstrap_and_overides.scss__ then included in application.css I have recently tried out foundation and this is how theirs is setup. I would be willing to help with this if this is acceptable.

Thank You,

**Comment by cvrebert** [comment]
Are you proposing a documentation change, or a code change?

**Comment by rebelweb** [comment]
This would be a documentation change. The documentation currently says to change __application.css__ to __application.scss__. This can creates problems when including other css libraries. I was proposing that the documentation should suggest adding a file __bootstrap_and_overides.scss__ and including it in application.css

The __bootstrap_and_overides.scss__ would look like this:

```scss
/* Declare variables here */

/* Includes for bootstrap */
@import 'bootstrap-sprokets';
@import 'bootstrap';
```

Leave the application.scss as it is like so:
```css
/*
 *= require bootstrap_and_overrides
 *= require_tree
 */
```

**Comment by thomas-mcdonald** [comment]
You can still use the manifest syntax at the beginning of an .scss file. We have a production app that uses to import libraries - from that `application.scss`:
```sass
/*
 *= require xyz
 *= require_self
*/

@import "bootstrap";
```

using a `bootstrap_and_overrides` file and Sprockets `require_tree` is not recommended, since you will be unable to use Bootstrap variables in your Sass files within that tree.

**Comment by rebelweb** [comment]
Okay I was unaware you could do that. Thank You for the help.
