### ISSUE TITLE
media-breakpoint mixins missing?

### ISSUE THREAD

**Issue by strarsis** [twbs/bootstrap-sass#1100]
I can't find the media breakpoint mixins (like media-breakpoint-up(...)) or classes like '.figure-img' in 
bootstrap-sass. Do these belong to a specific bootstrap release that is different to stock bootstrap?

**Comment by icanseesharp** [comment]
Facing the same issue
@strarsis  did you get a workaround?

**Comment by strarsis** [comment]
@icanseesharp: Well, I just replaced these with default WordPress styles from WordPress Codex.

**Comment by glebm** [comment]
These mixins only exist in Bootstrap 4. This gem is for Bootstrap 3. See the first paragraph of the Readme.

**Comment by icanseesharp** [comment]
@strarsis Thanks for the reply, a friend of mine has come up with something similar to the mixin so we are using his code.

@glebm  I am facing this problem with Bootstrap 4, but found the issue here and commented without realising the version, silly me!

**Comment by glebm** [comment]
@icanseesharp These mixins do exist in Bootstrap 4. If they don't work, it is likely a problem with how you're importing Bootstrap.

**Comment by abrambailey** [comment]
@glebm I think this is a problem. Here's what I have:

```application.js
//= require jquery3
//= require popper
//= require bootstrap-sprockets
//= require jquery_ujs
```

```application.scss
@import "bootstrap-overrides";
@import "bootstrap";
```

```bootstrap-overrides.scss
$primary-color: #2c88c5;
$theme-colors: (
  "primary": $primary-color,
  "info": #3E97D7
);
```
