### ISSUE TITLE
Dependencies error with new Laravel webpack (npm run dev)

### ISSUE THREAD

**Issue by KakaCarrotCake** [twbs/bootstrap-sass#1107]
**Information**

With the release of the new laravel (5.4) and the default usage of the new webpack instead of gulp to compile all resources using `npm run dev` also came a new way to load url's in sass. Instead of paths like; `../fonts/bootstrap/font.eot` there now a need to have the paths look like this: `~/fonts/bootstrap/font.eot`.

I'm not really sure how non-laravel projects react to this change though since I can't test that unfortunately, thus why I post this as an issue instead of a pull request.

I hope someone else could possibly test this change in a non-laravel environment so I (or someone else) can post the updated path as a pull request.

**The changes that need to be made are as follows:**

1. Go to `node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss` on **line 83**.
2. Change `"../fonts/bootstrap/"` to `"~/../fonts/bootstrap/"`.

**How to duplicate this error**

1. Setup a (fresh) laravel 5.4 environment using the new webpack and npm.
2. Add bootstrap-sass and run the `npm install` command.
3. After the install is done, run `npm run dev`.

**Exact error relevant for the bootstrap-sass module:**
```
These dependencies were not found in node_modules:

* ../fonts/bootstrap/glyphicons-halflings-regular.eot
* ../fonts/bootstrap/glyphicons-halflings-regular.woff2
* ../fonts/bootstrap/glyphicons-halflings-regular.woff
* ../fonts/bootstrap/glyphicons-halflings-regular.ttf
* ../fonts/bootstrap/glyphicons-halflings-regular.svg
```

**Comment by IkRookG** [comment]
Adding `mix.options({processCssUrls: false});` in the `webpack.mix.js` file seems to solve this issue for now.

**Comment by cgweeratunga** [comment]
I think `processCssUrls: false` is not working properly for laravel-mix 0.8.1.
I've updated laravel-mix 0.8.1 to 0.8.2 and now `$icon-font-path: '../fonts/bootstrap/';` working for me.

**Comment by KakaCarrotCake** [comment]
This issue has been solved for a while with new laravel-mix versions.
