### ISSUE TITLE
Stylesheets underscore

### ISSUE THREAD

**Issue by timgrafton** [twbs/bootstrap-sass#1108]
In _bootstrap.scss under the stylesheets section, the @import links need prefixing with an underscore. So instead of @import 'bootstrap/variables' it should be 'bootstrap/_variables'.

**Comment by thomas-mcdonald** [comment]
This is a feature of Sass and the underscore is not necessary - curious what setup you are using that doesn't support [Sass partials](http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#partials).

**Comment by timgrafton** [comment]
Hi thomas, thanks for clarifying, I actually realised this earlier today. I've been using PostCSS to load my Sass. Its not plain sailing like the actual Sass. Anyway, thanks.
