### ISSUE TITLE
Is any documentation when using postcss?

### ISSUE THREAD

**Issue by saeidalidadi** [twbs/bootstrap-sass#1112]
I am already using this module and I want to use `postcss` inside of my own style. So is there any way to import this module and override some variables or use mixins to make customization before transforming to postcss?

**Comment by thomas-mcdonald** [comment]
You run postcss either before or after your Sass pipeline.

**Comment by saeidalidadi** [comment]
I am working on a project and I think instead of importing all `sass` files from an entry point it would be better to import each component style from `js` which have been located in the same directory.
So is there a best practice for using this module mixins, variables and components directly.
think like this:

main entry point for project `app.js`

```javascript

import aComponent from `a.component.js`;


```
component file: ` a.component.js`

```javascript

import style from `style.css`;

...
```

Inside `style.css`:

```css

@import '~bootstrap-sass/variables';
  
// use variables in this css file
```
