### ISSUE TITLE
Error: Popover requires tooltip.js

### ISSUE THREAD

**Issue by ltdev22** [twbs/bootstrap-sass#1113]
I'm getting the following error on Firebug as you can also see here [https://i.stack.imgur.com/sxj2M.png](https://i.stack.imgur.com/sxj2M.png) :

`Error: Popover requires tooltip.js`

I guess this occures because as I can see on my source code, popover loads after tooltip [https://i.stack.imgur.com/Z6VUq.png](https://i.stack.imgur.com/Z6VUq.png)

Is there a way to fix this, or do I have to wait for a new release?

**Comment by bardware** [comment]
Where do the script-tags come from? When you generate them yourself you can simply reorder them,
