### ISSUE TITLE
card class didn't work  

### ISSUE THREAD

**Issue by umair-khanzada** [twbs/bootstrap-sass#1115]
Hey I'am unable to to create card below is my code.
```
<div class="card" style="width: 20rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title">Card title</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
```
other bootstrap components are works good except card.

**Comment by lucyconklin** [comment]
I was able to reproduce this on Rails 5.0.1. Looks like it was recently updated in Bootstrap:

If you’re familiar with Bootstrap 3, cards replace our old panels, wells, and thumbnails. Similar functionality to those components is available as modifier classes for cards.

**Comment by ihouse10** [comment]
I would use panel instead or switch to BootStrap4 

https://getbootstrap.com/docs/3.3/components/#panels

**Comment by glebm** [comment]
This is bootstrap 3, cards are bootstrap 4, please see the first paragraph of the readme.
