### ISSUE TITLE
compass compile error

### ISSUE THREAD

**Issue by captain-sensible** [twbs/bootstrap-sass#1116]
trying to overide bootstrap variables such as color if i keep same indentation & not chage anything except copy & paste & remove // in _bootstrap-variables.scss eg

// $body-bg:               #fff
   $body-bg:               #fff

i get compile error- i just don't get it, yet it did accept 
$gray-base:              #000
compass version 
bash-4.3$ compass -v
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2017 Chris Eppstein

**Comment by Thoulah** [comment]
`;`
