### ISSUE TITLE
Dropdown Menus stopped working after adding Fullcalendar

### ISSUE THREAD

**Issue by NatGarrison** [twbs/bootstrap-sass#1118]
I have a simple Rails application that I am trying to add Fullcalendar to.  After modifying my application.js file with "//= require moment" and "//= require fullcalendar" my dropdown menus stop working.  When you clicked on them nothing at all happened except for a "#" sign was being added to the end of the URL in the browser's address bar.  After a few days of looking for a solution I found information about the order of things in the application.css and the applicatoin.js files.  It turns out that the above two mentioned requires need to be after "//= require jquery" and "//= require jquery_ujs" lines in the application.js file.  I have no idea why, but I sure other people well run into the same problem.

I hope that this information helps.

**Comment by Yammmy** [comment]
@NatGarrison Yeah, I've got the same problem when I updated to rails 5.1.0.
Cuz jQuery no longer a default dependency. So I just add gem 'jquery-rails' to Gemfile and  "//= require jquery" and "//= require jquery_ujs" lines to application.js file.
Thx a lot.

**Comment by thomas-mcdonald** [comment]
Cool, given it seems there's no issue here I'm going to close this out.
