### ISSUE TITLE
[NPM] File import not found or unreadable: bootstrap.

### ISSUE THREAD

**Issue by FuzzzyTTV** [twbs/bootstrap-sass#1123]
When I try to import bootstrap into my sass file using @import "bootstrap" . I get an saying that the import is not found or unreadable. Any help?

**Comment by heinhoang** [comment]
I meet same problem

**Comment by heinhoang** [comment]
but when I import like this, it works:
@import "bootstrap-sass/assets/stylesheets/_bootstrap";

**Comment by marcosnovaesq** [comment]
same here

**Comment by eblatt** [comment]
same
