### ISSUE TITLE
Rails 5.1 - No jQuery

### ISSUE THREAD

**Issue by ryanhageman** [twbs/bootstrap-sass#1125]
As of Rails 5.1 jQuery isn't automatically bundled with Rails apps.

**Comment by ryanhageman** [comment]
I added a step by step to the readme file and submitted a pull request.

**Comment by saulm** [comment]
If someone doesn't want to use Yarn, you can include jquery-rails (https://github.com/rails/jquery-rails) and then in the application.js:

```
//= require jquery
//= require jquery_ujs
```
