### ISSUE TITLE
Solution: Dropdowns and collapse are  not working

### ISSUE THREAD

**Issue by rahul2240** [twbs/bootstrap-sass#1127]
For majority of people,dropdowns and collapse are not working.
The solution is to include  gem 'jquery-rails' in rails 5 or above
add it to readme

**Comment by matthewvolk** [comment]
When testing for responsiveness on desktop browser, if you collapse the mobile nav and then expand the viewport back to desktop size, the nav items still stay hidden. 

Will this jQuery gem also fix that problem?

**Comment by rahul2240** [comment]
for me including this gem fixed that problem.
