### ISSUE TITLE
Table cells vertical-align???

### ISSUE THREAD

**Issue by vs0uz4** [twbs/bootstrap-sass#1129]
Is there any variable in which it is possible to change the vertical alignment of the cells?
For in this section in _tables.scss below, the alignment at the top is explicit. 
```
.table {
  width: 100%;
  max-width: 100%;
  margin-bottom: $line-height-computed;
  // Cells
  > thead,
  > tbody,
  > tfoot {
    > tr {
      > th,
      > td {
        padding: $table-cell-padding;
        line-height: $line-height-base;
        vertical-align: top;
        border-top: 1px solid $table-border-color;
      }
    }
  }
...
```

Is there a way to align in the middle?

**Comment by AwakenTheJaken** [comment]
Wouldn't it be possible just to override the _tables.scss using and inserting whatever your v-align you want? You could do that or you could even define your own variable that sets this something like `$table-cell-alignment = 'middle'` and then declaring it inside of the _tables.scss
```
.table {
  width: 100%;
  max-width: 100%;
  margin-bottom: $line-height-computed;
  // Cells
  > thead,
  > tbody,
  > tfoot {
    > tr {
      > th,
      > td {
        padding: $table-cell-padding;
        line-height: $line-height-base;
        vertical-align: middle; <---HERE (top, bottom, middle, $table-cell-alignment)?
        border-top: 1px solid $table-border-color;
      }
    }
  }
