### ISSUE TITLE
SASS's digits of numeric precision is changed

### ISSUE THREAD

**Issue by parapada73** [twbs/bootstrap-sass#1130]
Starting with SASS 3.5.0, ten digits of numeric precision is default.
Please reflect this in your document.

[http://sass-lang.com/documentation/file.SASS_CHANGELOG.html](url)

**Comment by bardware** [comment]
What used to be the standard?
Correct [link](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html)

**Comment by parapada73** [comment]
I do not know the meaning of the standard you say
My intention is to specify that there is a difference between SASS versions.

**Comment by kyawkyawsoezhu** [comment]
I found numeric value that assign to `$line-height-base` not render correctly, you can see in the screenshot, in `_variables.scss` the value is `1.428571429` but result is browser is `1.42857`, it seems  only 5 digits is accepted after `.`(dot)

![var](https://user-images.githubusercontent.com/14541103/28857561-728f2080-7770-11e7-86c7-0503a0190377.png)

![chrome](https://user-images.githubusercontent.com/14541103/28857560-728e727a-7770-11e7-8770-8f9af86f7a05.png)


@parapada73 it's the same issue ?
