### ISSUE TITLE
I get this error: TypeError: Cannot read property 'tab' of undefined

### ISSUE THREAD

**Issue by janzenz** [twbs/bootstrap-sass#1131]
I'm using the latest version `3.3.7` and I'm getting this error:

```
/node_modules/bootstrap-sass/assets/javascripts/bootstrap/tab.js:128
  var old = $.fn.tab
```

I'm using `jquery:^2.2.4` as well.

Has anyone encountered the same error?

**Comment by thomas-mcdonald** [comment]
If `$.fn` is undefined my guess is that jQuery is not yet loaded at the point that this code is running.
