### ISSUE TITLE
Bootstrap 4 support?

### ISSUE THREAD

**Issue by ming-codes** [twbs/bootstrap-sass#1138]
Bootstrap 4 is in beta. We like to start using it with eyeglass. I believe it is time to get Bootstrap 4 on to the bootstrap-sass project.

**Comment by glebm** [comment]
Please refer to the second sentence of the Readme:

> This is Bootstrap 3. For Bootstrap 4 use the [Bootstrap Ruby gem](http://github.com/twbs/bootstrap-rubygem) if you use Ruby, and the [main repo](http://github.com/twbs/bootstrap) otherwise.
