### ISSUE TITLE
Sass precision (default = 5) too low for $line-height-base calculation

### ISSUE THREAD

**Issue by tsixd** [twbs/bootstrap-sass#1144]
in _variables.scss $line-height-base is set to 1.428571429
Sass cuts this to 1.42857. This leads to different heights in button and text Inputs. Text inputs are 1px higher. (osx, chrome)
In my gruntfile I had to set "precision: 8". Now it calculates to 1.42857143 which makes the buttons and input fields the same height.

Maybe there should be a note about the precision setting in sass to handle this issue.

![bootstrap_sass_precision](https://user-images.githubusercontent.com/7041767/31766294-72465e7e-b4c7-11e7-8f87-c9eb665ed015.png)

**Comment by glebm** [comment]
There is a note: https://github.com/twbs/bootstrap-sass#sass-number-precision

**Comment by tsixd** [comment]
oh man! sorry, reading helps… ;-)
I didn't find it via google, though…
Anyway, what really would be helpful is to put a comment next to the "$line-height-base" definition in _variables.scss.

Thanks a lot!

**Comment by glebm** [comment]
$line-height-base is far from the only variable affected by this, e.g. most of the grid sizes are as well.
Recent versions of Sass also default to precision 10, you are likely using an older version.
