### ISSUE TITLE
Bootstrap 4? Project not active? 

### ISSUE THREAD

**Issue by 1zaak** [twbs/bootstrap-sass#1150]
It doesn't look this project is actively in development. No new releases coming out recently.

**Comment by kamlekar** [comment]
I think this repo is only meant for Bootstrap 2 and 3. For bootstrap 4, I am not sure but you can download the source files (with official sass support) from this [link](http://getbootstrap.com/docs/4.0/getting-started/download/#source-files) . If you visit there [blog](https://blog.getbootstrap.com/), you can see the latest release was nearly around 2 months back.

**Comment by 1zaak** [comment]
Thanks @kamlekar

**Comment by kamlekar** [comment]
👍  Hey, [twbs/bootstrap](https://github.com/twbs/bootstrap) is actually the latest repo :). Even I will unwatch and watch that repo now.

**Comment by glebm** [comment]
The very first sentences in the README say:

> `bootstrap-sass` is a Sass-powered version of [Bootstrap](https://github.com/twbs/bootstrap) 3, ready to drop right into your Sass powered applications.
>
> This is Bootstrap 3. For Bootstrap 4 use the [Bootstrap Ruby gem](http://github.com/twbs/bootstrap-rubygem) if you use Ruby, and the [main repo](http://github.com/twbs/bootstrap) otherwise.
