### ISSUE TITLE
File to import not found or unreadable: bootstrap-sprockets.

### ISSUE THREAD

**Issue by eblatt** [twbs/bootstrap-sass#1152]
Anyone know how to fix this error?

![screen shot 2017-12-26 at 6 45 08 pm](https://user-images.githubusercontent.com/25444549/34368433-fbedc4ec-ea81-11e7-821b-276dde993341.png)

**Comment by feixiaoyang** [comment]
I'm having the same issue

**Comment by thomas-mcdonald** [comment]
`bootstrap-sass` is not in your load paths. Did you restart your dev server after installing the gem?

**Comment by danteskin** [comment]
I'm having the same issue, and restart server
