### ISSUE TITLE
Dropdown not working

### ISSUE THREAD

**Issue by rocLv** [twbs/bootstrap-sass#1154]
My rails version is 5.1.4 and `bootstrap-sass` version is 3.3.7.

Dropdown is working in Safari, but not on Chrome(version 63).

I tried the dummy rails under test directory, and I found its dropdown is not working in either of Safari and Chrome.

Though, alter the order of "jquery" and "bootstrap-sprockets" fix this problem but get more errors.

So, what's the solution?

**Comment by blackpond** [comment]
This is happening to me as well.  It works fine in production, but does not work in development on my local machine.

Rails 5.1.2 
Bootstrap 3.3.4
