### ISSUE TITLE
Bootstrapp@3.3.7 is vulnerable to XSS - Fix is in Bootstrap@3.4.0

### ISSUE THREAD

**Issue by narfk** [twbs/bootstrap-sass#1157]
Bootstrapp@3.3.7 is vulnerable to XSS (https://snyk.io/vuln/npm:bootstrap?lh@3.3.7)
Fixes are available in Bootstrap 3.4.0 or higher.

Please update bootstrap-sass

**Comment by glebm** [comment]
Bootstrap 3.4.0 has not been released yet. This gem will be updated once it's released upstream. You can use branch `next` at this commit in the meantime:

https://github.com/twbs/bootstrap-sass/commit/6e27cce4b9ebc8a745c0eb0191c47245ad31ef48

**Comment by glebm** [comment]
Bootstrap 3.4.0 has not been released yet. This gem will be updated once it's released upstream. You can use branch `next` at this commit in the meantime: https://github.com/twbs/bootstrap-sass/commit/7ac94c96ef4e0007c7ad3cb73b57e1219b3529bd

**Comment by narfk** [comment]
👍

**Comment by samgranger** [comment]
@glebm any updates on 3.4.0 update for this gem?

**Comment by glebm** [comment]
3.4.0 still hasn't been released upstream

**Comment by votw** [comment]
@glebm : Any idea on release timelines for this fix?

**Comment by don-spyker** [comment]
@glebm There are updates in the bootstrap 3.4.0-dev branch. Will they be synced automatically in the next branch of bootstrap-sass?

**Comment by glebm** [comment]
@don-spyker They are in the `next` branch now along with sass -> sassc migration and other minor changes.
