### ISSUE TITLE
Upgrade node-sass

### ISSUE THREAD

**Issue by gavinr** [twbs/bootstrap-sass#1173]
When I try to `npm install` this on Windows 10, I get the following error:

```
> node-sass@3.13.1 install C:\...\calcite-maps\node_modules\grunt-sass\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

This appears to be because that file (https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node) does not actually exist on that release: https://github.com/sass/node-sass/releases/tag/v3.13.1. Because of this, I cannot install this on my machine. I think the simplest solution would be to update to the latest `node-sass`.

**Comment by gavinr** [comment]
Now that I've looked more into the code, it looks like this has been done in the `next` branch here: e4906f420f9e751f0028902a858080f3f42fc975 ... so I guess if/when that branch is released this issue can be closed. Is that the plan @glebm? Thanks!

**Comment by glebm** [comment]
The plan is to release it along with 3.4.0 upgrade. I'll release it earlier if v3.4 is not out before EOY.

For now, you can use the next branch like this:

```ruby
gem bootstrap-sass', git: 'https://github.com/twbs/bootstrap-sass', branch: 'next'
```
