### ISSUE TITLE
Undefined variable: "$alert-padding" in vuejs

### ISSUE THREAD

**Issue by dharmatv** [twbs/bootstrap-sass#1188]
i added bootstrap sass through npm in my project, after that i had included

@import "bootstrap-sass/assets/stylesheets/bootstrap/_alerts.scss";

in scss file like styles.scss. after that i run my project(vuejs). it will show error like

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  padding: $alert-padding;
          ^
      Undefined variable: "$alert-padding".

this is not related to #654 issue

**Comment by igasparetto** [comment]
I don't think this has anything to do with Vue.

```
// functions must be first as they are used by variables
@import "../../../node_modules/bootstrap/scss/functions";

// TRY ADDING THE FOLLOWING LINE:
// we need variables here to provide support for updates/new variables
@import "../../../node_modules/bootstrap/scss/variables";

// our variables
@import "variables";

// components
@import "../../../node_modules/bootstrap/scss/mixins";
...
```

**Comment by XhmikosR** [comment]
Yeah, you need to import the above fisrt.
