### ISSUE TITLE
Problem with v3.4.1 release

### ISSUE THREAD

**Issue by AdamPS** [twbs/bootstrap-sass#1192]
v3.4.0 is still showing up as latest release on https://github.com/twbs/bootstrap-sass/releases and composer fetches v3.4.0.  Please can you check - is the v3.4.1 release not fully available somehow?

**Comment by XhmikosR** [comment]
Composer is unrelated to this repo. Not sure who even handles that TBH. So make an issue upstream.

**Comment by AdamPS** [comment]
Thanks.  Composer seems to be fixed now.
