### ISSUE TITLE
HTML popovers broken in 3.4.1 

### ISSUE THREAD

**Issue by mramato** [twbs/bootstrap-sass#1193]
It looks like the `sanitize` option was added in 3.4.1 (commit 69157ce76df1ccff394803811e582979cda4a993) and defaults to true.  This breaks most existing HTML popovers. Setting it to false gets the old behavior (obviously it's up to dev to ensure the HTML they use is safe).

Was this an accident or intentional?  It wasn't listed in changes and it's a breaking change that ignores semver norms.

It's also odd that 3.4.1 doesn't even have a section in CHANGELOG.md, was it even supposed to be released?

**Comment by Johann-S** [comment]
Hi @mramato,

It was pretty explicit in our blog post: https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
BTW you can tweak sanitizer rules see: https://getbootstrap.com/docs/3.4/javascript/#js-sanitizer

I think it's not in Bootstrap Sass CHANGELOG.md because it's a release of Bootstrap.

**Comment by mramato** [comment]
Thanks, I was just caught offgaurd by the change and wanted to confirm it was intentional. We already handle sanitization elsewhere, so I just disabled the option with `sanitize:false` when creating the pop-over.

**Comment by RudeySH** [comment]
Where is `sanitize: false` documented? I tried setting it via data attributes (`data-sanitize="false"`) but it to my surprise, it didn't work.

**Comment by RudeySH** [comment]
Never mind, of course 1 minute after commenting here I find the answer.

From the docs:

> Note that for security reasons the sanitize, sanitizeFn and whiteList options cannot be supplied using data attributes.

**Comment by symmetriq** [comment]
Note that you have to explicitly whitelist every element, so this example in the docs is a bit misleading:

```js
// To allow table elements
myDefaultWhiteList.table = []
```

This doesn't *really* allow tables; you also have to whitelist `thead`, `th`, `tbody`, `td`, and `tr`, or you will just get empty `<table>` elements.
