### ISSUE TITLE
Rails precompile fails on test/dummy_node_mincer/application.css.ejs.scss

### ISSUE THREAD

**Issue by pvenky** [twbs/bootstrap-sass#1196]
We are switching one of our projects from using bower to using yarn instead. In dev mode, everything works and looks as expected. However, when building on our staging server, the assets:precompile step is breaking on the file `node_modules/@bower_components/bootstrap-sass/test/dummy_node_mincer/application.css.ejs.scss`. I cannot seem to find anyone else that is having this specific issue. Version information below:
- Ruby: 2.5.1
- Rails: 5.2.1
- node: 10.15.3
- bootstrap-sass: 3.3.5
- sprockets: 3.7.2
- sass: 3.5.6

Here are the relevant portions of the build output (the line "Processing..." comes from a modification I made to the sprockets code - without it, I couldn't isolate which file was breaking):
```
Processing bootstrap-sass/test/dummy_node_mincer/application.css//var/www/XXXXX/releases/20190402181604/node_modules/@bower_components/bootstrap-sass/test/dummy_node_mincer/application.css.ejs.scss
rake aborted!
Sass::SyntaxError: Invalid CSS after "...(__p,arguments)": expected "{", was ";};with(obj||{}..."
(sass):1
/var/www/cloudlm/shared/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:1278:in 'expected'
/var/www/cloudlm/shared/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:1208:in 'expected'
```
Everything was working when we were using bower, and we've made minimal changes to other files during the transition process.

**Comment by glebm** [comment]
You shouldn't be trying to compile this file, it's part of the internal tests for bootstrap-sass.

If you can't figure out why your app is trying to compile it, you can try StackOverflow.
