### ISSUE TITLE
Dropdown menu is not working

### ISSUE THREAD

**Issue by louposk** [twbs/bootstrap-sass#152]
Hello,
i am using bootstrap-sass 2.0.3.1 gem and i have included it in my gemfile. 
I have included the javascript into the application.js file:

``` ruby
//= require jquery
//= require bootstrap
//= require jquery_ujs
//= require jquery-ui
```

I have created my dropdown menu:

``` html
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '/' %></li>

              <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", '#' %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", '#' %>
                </li>
              </ul>
            </li>
</nav>
```

but my dropdown does not work. I have cleared the cache and i have tested in all browsers but nothing.
Any ideas??
Thank you

**Comment by Yassir4** [comment]
I had the same issue 
In application.js try to follow this order
`// = require jquery
// = require bootstrap
// = require rails-ujs
// = require turbolinks
// = require_tree .`
