### ISSUE TITLE
Data methods doesn't work inside menu dropdowns

### ISSUE THREAD

**Issue by Linuus** [twbs/bootstrap-sass#193]
Data methods doesn't work in dropdown menus. I.e. if you have a logout link with `method:  : delete` it will still send a GET request. This has been fixed in v2.1.1 (wip) of the original Bootstrap. It's a small .js issue.

I will issue a pull request to get this fixed in v2.1-wip of bootstrap-sass.

**Comment by jakehockey10** [comment]
is this broken again in 3.3.3 for anyone?
