### ISSUE TITLE
Add an optional $prefix to all Bootstrap classes

### ISSUE THREAD

**Issue by adammck** [twbs/bootstrap-sass#253]
It would be very useful (at least to me) to be able to prefix all of the classes provided by Bootstrap, to more clearly distinguish them from my sites' own classes and those provided by other tools. Class names like `row` are far too generic; something like `tb-row` would be much clearer.

Unfortunately, [this idea has been rejected upstream](https://github.com/twitter/bootstrap/issues/1287#issuecomment-3690546), so I'm submitting it here instead. I'd be happy to submit a pull request with this change if you're interested. I'm mostly scratching my own itch, but I'm also hoping that it will help to advocate for the issue to be reconsidered upstream.

Implementation-wise, this:

``` scss
.pagination { }
.pagination ul { }
.pagination ul > li { }
```

Would simply become:

``` scss
.#{$tbPrefix}pagination { }
.#{$tbPrefix}pagination ul { }
.#{$tbPrefix}pagination ul > li { }
```

Configuration-wise, I'd add an (empty by default) `$tbPrefix` variable to the top of `_bootstrap.scss`, which can be set in my app's stylesheet before importing Bootstrap.

Let me know what you think.

**Comment by brycekunkel** [comment]
Im finding this while working on a project that has global styles that are not under my control applied to the page. While using a namespace seems like great option in some use cases, for me, I really need each class to be prepended to prevent class conflicts with the globally loaded stylesheet. Is there any way to do this? Like @adammck said, it'd be great to have a `#{prefix}` before each class, but I haven't been able to figure out a way to do this using SASS.
