### ISSUE TITLE
Mixin for multiple transitions

### ISSUE THREAD

**Issue by cnagel** [twbs/bootstrap-sass#386]
Hi,

a simple Mixin for multiple transitions is missing. It is not possible to use:

``` sass
@include scale(1.25);
@include rotate(120deg);
```

on the same time. Possible solution would be:

``` sass
@mixin transform($transform) {
  -webkit-transform: $transform;
     -moz-transform: $transform;
      -ms-transform: $transform;
       -o-transform: $transform;
          transform: $transform;
}
```

and can be used by:

``` sass
@include transform(scale(1.25) rotate(120deg));
```

**Comment by leggomuhgreggo** [comment]
This is exactly what I was looking for thanks, @cnagel

**Comment by glebm** [comment]
Autoprefixer is required by Bootstrap, so the mixin is no longer necessary, this will work:

```scss
a {
  transform: scale(1.25) rotate(120deg);
}
```

**Comment by leggomuhgreggo** [comment]
Oh really? When did that happen? I didn't see anything about it on the
either the github repo or getbootstrap.com

**Comment by glebm** [comment]
In v3.3.2: https://github.com/twbs/bootstrap-sass/releases/tag/v3.3.2

**Comment by athimannil** [comment]
@cnagel You got solution for the bug ?
