### ISSUE TITLE
form_for form_tag + rails 4 doesn't get bootstrap 3 styles

### ISSUE THREAD

**Issue by aguipluto** [twbs/bootstrap-sass#478]
When I use bootstrap-sass and rails 4 the forms doesn't take the rails styles, what I'm doing wrong?
<%= form_tag do %>
            <%= label :aportacion, "Aportación" %>
            <%= text_field :aportacion, placeholder: "Cantidad total" %>
      <% end %>

and the html rails render:

<form accept-charset="UTF-8" action="/proyectos/15" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="IWRJt4s1PfnTC9mDAtddf30QwlVIKG9kGLgjfSpzWMo="></div>
            <label for="aportacion_Aportación">Aportación</label>
            <input id="aportacion_{:placeholder=&gt;&quot;Cantidad total&quot;}" name="aportacion[{:placeholder=&gt;&quot;Cantidad total&quot;}]" type="text">
</form>

Thanks for the help

**Comment by ezesalas7** [comment]
Thank you @wyaeld, It was very helpful!
