### ISSUE TITLE
Problem with path for fonts ($icon-font-path)

### ISSUE THREAD

**Issue by sh-a-a** [twbs/bootstrap-sass#480]
If $icon-font-path starts from "/" then it's include whole "url('..')" string as path.

Example result:

``` css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("url(/css/fonts/glyphicons-halflings-regular.eot)");
```

**Comment by akhileshojha** [comment]
# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "css"
sass_dir = "scss"
images_dir = "images"
javascripts_dir = "js"
http_fonts_path = "fonts"

It's working good :)
