### ISSUE TITLE
libsass support

### ISSUE THREAD

**Issue by glebm** [twbs/bootstrap-sass#494]
- [x] Compilable with libsass (0.3.8)
- [x] Compilation test 
- [x] docs

~~Blocked by~~
- ~~https://github.com/hcatlin/libsass/issues/231~~
- ~~https://github.com/andrew/node-sass/issues/212~~

**Comment by Pencab** [comment]
> * [x]  Compilable with libsass (0.3.8)
> * [x]  Compilation test
> * [x]  docs
> 
> ~Blocked by~
> 
> * ~[Error: url(fn("str")) sass/libsass#231](https://github.com/sass/libsass/issues/231)~
> * ~[0 exit code on error sass/node-sass#212](https://github.com/sass/node-sass/issues/212)~
