### ISSUE TITLE
Compass build glyphicons issue

### ISSUE THREAD

**Issue by websanya** [twbs/bootstrap-sass#511]
Hi, I'm using Compass extension, and after creating the project and requiring the plugin the compilers says this:

`WARNING: 'glyphicons-halflings-regular.eot?' was not found (or cannot be read) in /Users/alex/Desktop/my-project/fonts/bootstrap`

what am I doing wrong?

I'm using Sass v3.3.0 rc2 and Compas v1.0.0 alpha17

**Comment by soosap** [comment]
Wow so true. This should be added to the readme. "bootstrap-sass-official" folder changed to "bootstrap-sass". So creating **"config.rb"** in the same directory as your Gruntfile and adding the following two lines fixed the problem for me.

`relative_assets = true`
`fonts_dir = "/public/lib/bootstrap-sass/assets/fonts/"`

**Comment by Yajo** [comment]
Sorry to resurrect this. My project is no ruby at all, but I'm getting affected when compiling with sass, and struggled to find a workaround, so I wanted to share it here.

My workaround is to go to the bootstrap assets directory before executing:

```
cd /usr/local/bundle/gems/bootstrap-sass-3.3.6/assets
sass --cache-location /var/cache/sass --compass --require bootstrap-sass --update /app:/app
```

To get rid of those warnings said in https://github.com/twbs/bootstrap-sass/issues/511#issuecomment-63064914.
