### ISSUE TITLE
Fonts with asset pipeline in version 3.1.1

### ISSUE THREAD

**Issue by cyrusstoller** [twbs/bootstrap-sass#533]
Thanks for this awesome gem.

When I bumped my app to version `3.1.1` I was getting 404 errors for the glyphicon asset files. The digest values that were getting being included in my HTML were not matching the ones in my public/assets directory. I've since reverted to `3.0.3` and things are working fine.

**Comment by ruckc** [comment]
When I do an rake assets:precompile, i get this.  (Your grep didn't work as
there is no hyphen after regular).

[ruckc@apps myapp]# cat public/assets/application-_.css | grep -oE
'glyphicons-halflings-regular[^.]_.\w+'
glyphicons-halflings-regular.eot
glyphicons-halflings-regular.eot
glyphicons-halflings-regular.woff
glyphicons-halflings-regular.ttf
glyphicons-halflings-regular.svg


On Sat, Feb 22, 2014 at 11:38 PM, Gleb Mazovetskiy <notifications@github.com

**Comment by ruckc** [comment]
@glebm it was the RAILS_ENV=production, it works properly for me now.
 Thanks
