### ISSUE TITLE
Changing assets.prefix for development, font still loaded from /assets

### ISSUE THREAD

**Issue by donnykurnia** [twbs/bootstrap-sass#550]
Because of the limitation in the vps, I do assets:precompile locally. I follow the guide here http://guides.rubyonrails.org/asset_pipeline.html#local-precompilation to set the different assets.prefix for development. However, I still got this in the application.css:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("/assets/bootstrap/glyphicons-halflings-regular.eot");
  src: url("/assets/bootstrap/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"), url("/assets/bootstrap/glyphicons-halflings-regular.woff") format("woff"), url("/assets/bootstrap/glyphicons-halflings-regular.ttf") format("truetype"), url("/assets/bootstrap/glyphicons-halflings-regular.svg#glyphicons-halflingsregular") format("svg");
}
```

I'm not sure if this is bootstrap-sass problems, sass, or sprocket. I also get same problems with font-awesome gem, and ckeditor. Somehow, ckeditor init.js.erb that use asset_path still return /assets but when I add my own override in app/assets, it return /dev-assets.

I have try to read the source code, but still don't find why the sass helper didn't use the assets.prefix config.

Thanks

**Comment by ypresto** [comment]
I had same issue and `rails (rake for rails < 5) tmp:cache:clear` fixed the issue.
