### ISSUE TITLE
ActionView::Template::Error undefined method environment for nil:NilClass

### ISSUE THREAD

**Issue by Stajor** [twbs/bootstrap-sass#560]
Error:
`
ActionView::Template::Error (undefined method 'environment' for nil:NilClass
  (in /path to project/app/assets/stylesheets/application.css.sass)):
    12:   <%= stylesheet_link_tag 'application', media: 'all' %>
`

Gem:
`
gem 'rails', '4.0.3'
gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass', '~> 3.1.1'`

applicaton.css.sass
`@import "bootstrap"
@import "main.css"`

If I remove  "@import "bootstrap"" all works.

**Comment by StanBoyet** [comment]
+1 while upgrading an app previously on 3.2. This appeared at the 4.1 -> 4.2 mark.
