### ISSUE TITLE
File to import not found or unreadable: mixins/hide-text.

### ISSUE THREAD

**Issue by FireWhale** [twbs/bootstrap-sass#589]
I had this error when using

@import "bootstrap";

I think it's because bootstrap-sass-3.1.1.1 moved some mixin scss files into a mixin directory (vendor/assets/stylesheets/bootstrap/mixin/) and the import cannot find them correctly. 

File to import not found or unreadable: mixins/hide-text.
Load Paths:
  e:/Programming/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets

additional info: bootstrap-sass-3.1.1.0 works fine, but it does not have the mixin directory.

**Comment by LoveAndHappiness** [comment]
Had the same error and got the following solution:

Just whenever you copy the necessary files from your bower_components through gulp in my case, make sure that all files are included like this:

gulp.task('copy-sass', function() {
	return gulp.src([
			'bower_components/bootstrap-sass/assets/stylesheets/*/*/*'
		])
		.pipe(gulp.dest('assets/sass'));
});

Pay attention to the stars at the end.

**Comment by tony13tv** [comment]
For rails 3.2.x
```
# Ugly monkey patch for allowing importation of bootstrap in application sass file
initializer :bootstrap do |config|`
   Sass.load_paths << Gem.loaded_specs['bootstrap-sass'].full_gem_path + '/assets/stylesheets/bootstrap'
end
```
