### ISSUE TITLE
couldn't find file 'bootstrap/glyphicons-halflings-regular.eot' error [bower]

### ISSUE THREAD

**Issue by clyfe** [twbs/bootstrap-sass#592]
Environment:
gem "middleman", "~> 3.1.0"
gem 'middleman-bower', '~> 1.0.2'

Steps to reproduce

```
bower install bootstrap-sass-official -S
```

In `application.css.scss`

```
@import "bootstrap-sass-official";
```

Error:

```
Sprockets::FileNotFound at /
couldn't find file 'bootstrap/glyphicons-halflings-regular.eot' (in /[...]/source/stylesheets/application.css.scss:1)
```

Note:
Not sure how the bower distribution of bootstrap-sass is meant to be used, it seems not not work out of the box. Let me know if I'm doing something wrong.

**Comment by soosap** [comment]
$icon-font-path: "../fonts/bootstrap";

worked for me!
