### ISSUE TITLE
input-group: button is one pixel too small in bootstrap-sass (but not when using Less)

### ISSUE THREAD

**Issue by rluba** [twbs/bootstrap-sass#595]
Without any custom style, the height of buttons in input-group-btn is one pixel less than the height of the corresponding input field (33px vs 34px). (Observed in Safari 7.0.3 and Chrome Canary 36.0.1961.3 using bootstrap-sass 3.1.1+2 with Sass 3.3.6)
![input-group-btn](https://cloud.githubusercontent.com/assets/4600573/2817554/c733fabc-ceda-11e3-8856-36556a54dcbe.png)

The button has the correct height of 34px when using the Less version of bootstrap. The issue is caused by a difference in precision between Less and Sass: The `line-height` of `.btn` is defined as `1.42857143` (Less) vs. `1.42857` (Sass).

**Comment by justintanner** [comment]
When using `rails-assets-bootstrap-sass-official` I was forced to override a bootstrap sass variable to get this to work:

    $line-height-base: 1.428571429;
