### ISSUE TITLE
opening modal shifts page content and navbars to the right

### ISSUE THREAD

**Issue by bscharm** [twbs/bootstrap-sass#610]
when opening a modal the entire content of the underlying page will shift slightly to the right, including the navbar at the top of the page. is this a known bootstrap issue? please see an example at http://enigmatic-brushlands-2071.herokuapp.com/about

each image corresponds to a modal. I am using google chrome, rails 4.1

**Comment by jjwilliams** [comment]
I see this was awhile back, but I am still seeing this issue. Aren't we on 3.3.1 (both bootstrap, and bootstrap-sass looks to be versioning the same)?
