### ISSUE TITLE
Basset/Laravel concat issues with tooltip

### ISSUE THREAD

**Issue by panoply** [twbs/bootstrap-sass#625]
Just a heads up for anyone. 

I'm using Gulp.js with the uglify and concat plugin on Laravel 4.1. Tooltip.js will concat after popover and cause issues in the bootstrap.min.js file. Tooltip will compress after popover, so your console will throw an error. This could also be due to Basset/Laravel or gulp not to sure. To combat this issue and for a quick fix change tooltip.js to "atooltip.js" in your "//= require" and jquery will start to play nice. Another error will be no slide transition in navbar toggle (mobile). Not really an issue with Bootstrap-sass but something maybe someone may come across and hopefully this will be of some help.  

SEO Purposes: Uncaught Error: Popover requires tooltip.js

**Comment by kuraga** [comment]
+1

**Comment by glebm** [comment]
The next release of bootstrap-sass (coming very soon) will reference the concatenated file at [assets/javascripts/bootstrap.js](https://github.com/twbs/bootstrap-sass/blob/847887b0ac523221b80cb986e5e42241bab0158a/assets/javascripts/bootstrap.js) in bower.json's `main`. Meanwhile, use that file, or specify the order explicitly.
