### ISSUE TITLE
Wrong default path of $icon-font-path variable

### ISSUE THREAD

**Issue by felixhayashi** [twbs/bootstrap-sass#650]
Hello,

I am sorry if this is a misunderstanding on my side but is there any reason why the default path for the icon-font is specified as

```
//** Load fonts from this directory.
$icon-font-path: "bootstrap/" !default;
```

and not 

```
$icon-font-path: "../fonts/bootstrap/" !default;
```

When I compile the bootstrap.scss with sass and include the css in my html via

```
<link rel="stylesheet" href="bootstrap-sass-twbs/assets/stylesheets/bootstrap.css" type="text/css" media="screen">
```

the glyphicons (which reside in bootstrap-sass-twbs/assets/fonts/bootstrap) are consequently **not** referenced by the bootstrap.css correctly as the output looks like this:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("bootstrap/glyphicons-halflings-regular.eot");
  ...
```

and not like this

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("../fonts/bootstrap/glyphicons-halflings-regular.eot");
  ...
```

Using the compiled distribution version of bootstrap, the css references the fonts in a correct relative way (`../fonts/glyphicons-halflings-regular.eot`) and looking at the less code in https://github.com/twbs/bootstrap/blob/master/less/variables.less the variable is set to `@icon-font-path: "../fonts/"`

So shouldn't the sass ported version not also be set to something like `../fonts/bootstrap/`?

Thanks

**Comment by hojas** [comment]
Thanks.
