### ISSUE TITLE
Rails, no glyphicons in production

### ISSUE THREAD

**Issue by jrochkind** [twbs/bootstrap-sass#664]
A rails 4.1.4 app (created a fresh one to demonstrate in isolation). 

bootstrap-sass 3.2.0.0

Followed 3.2.0.0 instructions to include bootstrap-sprockets in my .scss:

```
@import "bootstrap-sprockets";
@import "bootstrap";
```

Still, when I precompile assets and load the app in RAILS_ENV=production, all my glyphicons references result in white boxes (unknown glyph) on screen, instead of the proper glyph. 

Exploring further... I see my browser is asking for:
    Failed to load resource: the server responded with a status of 404 (Not Found) 
    http://localhost:3000/assets/bootstrap/glyphicons-halflings-regular.woff

```
Failed to load resource: the server responded with a status of 404 (Not Found) 
http://localhost:3000/assets/bootstrap/glyphicons-halflings-regular.ttf
```

What _would_ have worked was:   

```
 http://localhost:3000/assets/bootstrap/glyphicons-halflings-regular-370498439f583aabf7e5fa44b046cb1b.ttf
```

Confirmed that URL resolves in my app. Recent versions of Rails only generate assets with the hash stamp on the end, it doesn't generate versions un-stamped. 

It looks like bootstrap-sass is supposed to accomodate this, that's what the new `bootstrap-sprockets` file is supposed to do?  And the [sass that references](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_glyphicons.scss#L17)  , with the:

```
if($bootstrap-sass-asset-helper, twbs-font-path ....
```

 For some reason it's not working. Is `$bootstrap-sass-asset-helper` ever actually defined to trigger that `if`?  I'm having trouble figuring out what the intention is here.

**Comment by mahi07101991** [comment]
Remove @import bootstrap and add the cdn. to your scss file.
@import url("//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css");

**Comment by thomas-mcdonald** [comment]
^^^ don't do this, it is not using the assets bundled in the gem.
I'm going to lock this issue, it has not been touched since 2014.
