### ISSUE TITLE
Documentation is misleading

### ISSUE THREAD

**Issue by kenmazaika** [twbs/bootstrap-sass#691]
The documentation is a bit misleading, particularly for beginners.  Instructing people to run this command if the file exists:

```
$ rm app/assets/stylesheets/application.css
```

Will delete the existence of that file, along with what it is doing:

```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the top of the
 * compiled file, but it's generally better to create a new file per style scope.
 *
 *= require_self
 *= require_tree .
 */
```

Really what you want to do is rename the file `app/assets/stylesheets/application.css` to `app/assets/stylesheets/application.css.scss` in order to access the full power of SASS, while maintaining the way the asset pipeline compiles assets, rather than eliminating everything entirely.

**Comment by cvrebert** [comment]
@twbs/sass So, where are we at on this?

**Comment by glebm** [comment]
Documentation is not misleading, should've closed this a few months ago.

**Comment by kenmazaika** [comment]
Hey, @glebm, I get asked multiple times per week by beginners about why their application lost all their CSS styles after running the following command:

![screen shot 2015-01-14 at 5 46 22 pm](https://cloud.githubusercontent.com/assets/233615/5749273/7a2951b4-9c15-11e4-8f87-59648655ca44.png)

Could we change this to be a:

```
mv
```

instead of a:

```
rm
```

Or, if that isn't a viable option something that actually explains what to do?  It's not misleading for someone who has years of rails experience, but if you're just picking it up the notes are super confusing.

**Comment by glebm** [comment]
I see. Perhaps instead we should just say `mv`, and then remove all the `//= require` statements from the CSS file. But previously this lead to beginners opening hard to diagnose tickets where they would not remove `require_tree .` and all hell would break loose.

**Comment by kenmazaika** [comment]
Thanks for fixing this, @glebm.  You rock! :)  :+1:

**Comment by x-yuri** [comment]
I believe I've come up with [a better solution](http://stackoverflow.com/a/28817605/52499), then what the documentation suggests. Particularly, because in my case every stylesheet is served in separate request in development and therefore only those stylesheets that has changed get recompiled. That must be what [@tombh](https://github.com/twbs/bootstrap-sass/issues/79#issuecomment-7062029) suggested.

Actually, this particular part of the docs was confusing to me. It seemed like `bootstrap-sass`'s developers considered it bad the way `sprockets` handles things by default.

**Comment by kirichkov** [comment]
:+1:  for @x-yuri's solution
