### ISSUE TITLE
`@import bootstrap-sprockets` throwing an error

### ISSUE THREAD

**Issue by asgeo1** [twbs/bootstrap-sass#692]
I can't seem to get the icons working with a Rails 4.1 app.

    #Gemfile:
    gem 'bootstrap-sass'   #3.2.0

    #application.css.scss:
    @import "bootstrap-sprockets";
    @import "bootstrap";

I get a `Sprockets::FileNotFound` error: `couldn't find file 'bootstrap/glyphicons-halflings-regular.eot'`

If I remove the `@import "bootstrap-sprockets";` line, then the error goes away, but the the icons don't work.

The only solution is to copy the fonts into my `app/assets/fonts` directory.

Anyone else having the same issue?

**Comment by joepasq** [comment]
I was having largely the same issue as @steveroot, @ok11 and @enricostano. Using Rails 4.1.7 and Bootstrap-sass 3.3.1 I had put an `group :assets do` block in my Gemfile and according to [this StackOverflow post](http://stackoverflow.com/questions/25540575/file-to-import-not-found-or-unreadable-bootstrap-bootstrap-rails-sass-error) realized that was causing the issue for me. That answers cites the [Rails upgrade guide](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0-gemfile) as such:

> Rails 4.0 removed the assets group from Gemfile. You'd need to remove that line from your Gemfile when upgrading. You should also update your application file (in config/application.rb)

    # Require the gems listed in Gemfile, including any gems
    # you've limited to :test, :development, or :production.
    Bundler.require(*Rails.groups)

**Comment by cvrebert** [comment]
@twbs/sass So, is there anything left to do here?

**Comment by thomas-mcdonald** [comment]
I think this is mostly 3/4 separate issues relating to other configuration rather than a bootstrap issue.

Closing & will lock since this seems to hit Google/search etc.
