### ISSUE TITLE
JS //= require bootstrap-sprockets breaks dropdowns

### ISSUE THREAD

**Issue by ahnbizcad** [twbs/bootstrap-sass#714]
I've isolated that the line 
`//= require bootstrap-sprockets` 
in the application.js manifest will prevent dropdowns in navbars from showing for ruby on rails.
Whether this line comes before or after the `//= require bootstrap` line doesn't seem to matter. Either way, it breaks dropdowns.

Using `@import "bootstrap-sprockets";` for the CSS mainfest doesn't break dropdowns. Only including it in the js does.

To reproduce, use:

ruby 2.0.0
rails 4.1.1
    sass-rails (4.0.3)
    bootstrap-sass (3.2.0.1)
    autoprefixer-rails (2.2.0.20140804)
gem 'sprockets-rails', :require => 'sprockets/railtie'

**Comment by sean-perryman** [comment]
Removing the require for bootstrap-sprockets fixed the issue for me as well. Not sure what else it is going to affect, but for now I am leaving it out.

**Comment by 14tinchov** [comment]
@Ugghhh 
Could you solve that problem? the same happens to me

This is my application.js

//= require jquery
//= require jquery_ujs
//= require bootstrap-sprockets
//= require bootstrap
//= require jquery-ui
//= require jquery.validate
//= require jquery.validate.additional-methods
//= require moment
//= require bootstrap-datepicker
//= require bootstrap-datetimepicker


In production doesn't work... Is there any alternative for drop down?

**Comment by dougharman** [comment]
It has to do with the order of the files.  Bootstrap and
bootstrap-sprockets need to be BELOW your jQuery in application.js:

 

Javascript / application.js

 

//= require jquery

//= require jquery.turbolinks

//= require jquery_ujs

//= require jquery-fileupload

//= require jquery-ui

//= require jquery-ui/datepicker

//= require bootstrap-sprockets

//= require bootstrap

//= require bootstrap-select

//= require bootstrap/alert

//= require bootstrap/dropdown

//= require turbolinks

//= require_tree .

 

Stylesheets / application.css.scss

 

 @import "jquery-ui";

@import "bootstrap-sprockets";

@import "bootstrap";

@import "custom";

@import "bootstrap-progressbar-3.3.0";

@import "bootstrap-progressbar-3.3.0.min";

@import "bootstrap-select";

@import "jquery.fileupload";

@import "jquery.fileupload-ui";

 

Also, if you add turbolinks, you'll need to do this in the View:

<li><%= link_to 'Sign in', new_user_session_path, "data-no-turbolink" =>
true %><br/>

 

I can't recall why that was needed...

 

Best, Doug Harman

 

 

________________________________

**Comment by glebm** [comment]
Do not require both bootstrap and bootstrap-sprockets in the JavaScript, you only need one of them

**Comment by humpback** [comment]
Hi, sorry to bring this up again, what was the solution that works for this? I am having this issue now.

The css ::after (down arrow) is not appearing on the navigation.

application.scss
```
*= require_tree .
 *= require_self
 *= require font-awesome
```

application.js
```
//= require jquery
//= require jquery_ujs
//= require jquery.turbolinks
//= require turbolinks
//= require bootstrap-sprockets
//= require bootstrap/dropdown
//= require_tree .
//= require brave/placeholders.js
//= require brave/respond.min.js
//= require brave/html5shiv.js
//= require brave/main.js

$(document).ready(function(){
    $('.dropdown-toggle').dropdown();
});

```

Thanks in advanced!

**Comment by dougharman** [comment]
That was a long time ago.  My recollection is that the key is the order
of the require's.  Just taking a quick look at your code (a) tree
belongs at the bottom and (b) so does turbolinks (before tree).  I also
believe / recollect that turbolinks needs to be below bootstrap
require's.  Good luck with it, Doug

 

________________________________

**Comment by railsr** [comment]
Here's what I have in my latest proj

application.scss

```
 *= require_tree .
 *= require_self
 *= require foundation_and_overrides
```

application.js

```
//= require jquery
//= require jquery_ujs
//= require_tree .
//= require jquery.turbolinks    
//= require foundation  
//= require turbolinks
```

**Comment by everestlab** [comment]
Hi @dougharman and @railsr thank you so much for giving me the clue! I play around with the order and just dumping all the js from template and managed to somehow make it work!

Just in case any next fellow experiencing similar issue, I only fixed application.js which look like this now

```
//= require jquery
//= require jquery_ujs
//= require jquery.turbolinks
//= require bootstrap-sprockets
//= require brave/placeholders
//= require brave/jquery.magnific-popup.min
//= require brave/owl.carousel.min
//= require brave/respond.min
//= require brave/html5shiv
//= require brave/main
//= require_tree .
//= require turbolinks
```

Thanks a lot again!

**Comment by dougharman** [comment]
Not sure about your css / scss file - I don't have tree in mine.
Believe it should be at the bottom if needed.

 

Application.js file should be in this order:

//= require jquery
//= require jquery.turbolinks    
//= require jquery_ujs
Other files, e.g., //= require foundation , do here
//= require turbolinks
//= require_tree .

 

 

________________________________

**Comment by everestlab** [comment]
the require_tree in scss seems to be fine as of now

ah yes thanks for your advice, moved //= require_tree . to the lowest line possible.

**Comment by dougharman** [comment]
I'm glad it worked.  One further suggestion, this order for turbolinks
and tree:
//= require turbolinks
//= require_tree . 

 

Best, Doug

 

________________________________

**Comment by everestlab** [comment]
Yup!

**Comment by bmckibben** [comment]
I realize this thread is a bit old, but I had a the same issue with the dropdowns. The cause was that I had jquery js files that were being included by //=require_tree .  

Once I removed those files, it worked.
