### ISSUE TITLE
Placeholders in addition to classes

### ISSUE THREAD

**Issue by Misiur** [twbs/bootstrap-sass#721]
Hello. Would it be possible to add additional file with placeholders only? So, instead
    @extend .col-sm-4;
We could use
    @extend %col-sm-4;

Why is that? Well, [in less you can import file as reference only](http://stackoverflow.com/questions/14453737/reference-a-class-mixin-without-completely-importing-the-less-file/14463540#14463540), however sass [https://github.com/sass/sass/issues/1317](isn't capable of that %28[see also this]%28https://github.com/sass/sass/issues/320%29%29). Currently I have subpage which requires global css file + specific for this page css file. Now if I import bootstrap in both of them, the code is no longer DRY and precious bandwidth is wasted. 

Thanks

**Comment by vetalstar** [comment]
My fork resolving this problem
https://github.com/vetalstar/bootstrap-grid-placeholders
