### ISSUE TITLE
.navbar-form is not correct compared to Bootstrap LESS

### ISSUE THREAD

**Issue by monkeymonk** [twbs/bootstrap-sass#723]
Hi there,

it seems that is missing something to make `.navar-form` showing correctly in bootstra-sass.

![bepark_-_0_0_1](https://cloud.githubusercontent.com/assets/574338/4269329/de7e4cce-3cba-11e4-97c3-e872fdb9565b.png)

It seems that the `@extend .form-inline;` at line 313 in `stylesheets/bootstrap/_navbar.scss` is not working properly.
When I try to change `.form-inline` in `stylesheets/bootstrap/_forms.scss` to a mixin and then doing `@include form-inline();` in `stylesheets/bootstrap/_navbar.scss`, it work properly.

I hope this is helping !

**Comment by huafu** [comment]
@glebm I am on latest version (`3.3.4`) and I still have this issue (tried with `next` tag but same issue):
```
bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_forms.scss, line 189

You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .input-sm" on line 48 of bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_input-groups.scss
```

FYI I am using `ember-cli-sass` which is using `broccoli-sass-source-map` being an updated fork of `broccoli-sass` using `3.0.0-beta1` of `node-sass`.

**Comment by glebm** [comment]
See https://github.com/twbs/bootstrap-sass/issues/879 about the bug in node-sass@3.x

**Comment by huafu** [comment]
thanks!
