### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap-sass#728]
Correct me if I'm wrong, but I don't think we're including a license or banner as part of our SCSS files?

**Comment by cvrebert** [comment]
The LICENSE file is also confusing, given that the conversion script is under Apache 2 per its header, yet the LICENSE file says MIT, presumably referring to the conversion script's output.

**Comment by glebm** [comment]
The converter is Apache 2 for historical reasons, but the output is MIT licensed, same as upstream. Would it be sufficient to include the license just on top of the `_bootstrap.scss` file?

**Comment by mdo** [comment]
> Would it be sufficient to include the license just on top of the `_bootstrap.scss` file?

Probably. (Apologies for resurrecting such an old thread!)

**Comment by LaurentGoderre** [comment]
This seems to have been fixed to v3.3.5

**Comment by glebm** [comment]
Indeed, this has been fixed (https://github.com/twbs/bootstrap-sass/blob/a73cc0f0e5c794206e9a70bc0b67e67cf37c1bca/assets/stylesheets/_bootstrap.scss#L1)
