### ISSUE TITLE
glyphicons are not showed on bootstrap sass

### ISSUE THREAD

**Issue by Gusduenas** [twbs/bootstrap-sass#746]
Hello Ive been trying to make this glyphicons to work with my bootstrap sass, I change the bootstrap-variables file (not sure if erase the// from the sass file) but so far I cannot get the glyphicons to work.
I also change the path to ../bootstrap but nothing at all, someone please help me. using compass and sass

**Comment by cvrebert** [comment]
@twbs/sass Seems like https://github.com/twbs/bootstrap-sass#fonts already sufficiently covers this?

**Comment by glebm** [comment]
That's right, closing this, if you are having problems please have a look at the Readme section linked in the comment above

**Comment by ianheggie** [comment]
FYI rails 5.0.2, I had to add `$icon-font-path: "bootstrap/";` before
`
@import 'bootstrap-sprockets';
@import 'bootstrap';
` 
For some (unknown) reason the icon-font-path was not being changed by bootstrap-sprockets.

**Comment by siwilkins** [comment]
Thanks @ianheggie, you've just saved me a lot of head-scratching :-)

**Comment by saidsoualhi** [comment]
Try change the source folder of your **glyphicons fonts** files to "bootstrap", or create a new folder in your fonts folder, with this name "bootstrap" and put your **glyphicons fonts** there.

**Comment by jerome-diver** [comment]
i read you all, but sorry, could you be more precise please ?
@saidsoualhi where is supposed to be the "fonts folder" and the "source folder of your glyphicons fonts" ? (I'm using Rails-5.2 actually, and what ever i done about change stylesheet import call the result stay the same: no glyphicons).
thank you for your precisions.
