### ISSUE TITLE
"Incompatible units" compile error

### ISSUE THREAD

**Issue by bendrexl** [twbs/bootstrap-sass#750]
I get "incompatible units" errors when compiling with Ruby Sass or node-sass (libsass). I'm following the "Bower" install in the readme, which says that it's compatible with node-sass 0.8.3+.  Am I doing something wrong or is this a bug?

**Comment by abea** [comment]
Does anyone have a clue why it's doing this? Is there a way to avoid the error? It seems better practice to reassign variables that are used elsewhere than to add a new one and have to rewrite all the other styles that use it.
