### ISSUE TITLE
DXImageTransform error during assets:precompile

### ISSUE THREAD

**Issue by dougfarre** [twbs/bootstrap-sass#767]
Trying to precompile bootstrap-sass with Rails 4 and rails sass gem.
gem 'sass-rails'  , '~> 4.0.3'
gem 'jquery-rails'
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'handlebars_assets'
gem 'iconv'

ake aborted!
Sass::SyntaxError: Invalid CSS after "    filter: progid": expected ";", was ": DXImageTransf..."
  (in /home/ubuntu/spice-conduit/app/assets/stylesheets/application.css)
(sass):3566
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:1147:in `expected'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:1085:in `expected'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:1080:in `tok!'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:586:in `block in declaration_or_ruleset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:1123:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:1123:in `rethrow'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:592:in `declaration_or_ruleset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:554:in `block_child'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:546:in `block_contents'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:535:in `block'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:529:in `ruleset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:553:in `block_child'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:546:in `block_contents'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:82:in `stylesheet'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/scss/parser.rb:27:in `parse'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/engine.rb:342:in `_to_tree'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/sass_compressor.rb:24:in `evaluate'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/context.rb:197:in `block in evaluate'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `each'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `evaluate'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/bundled_asset.rb:25:in `initialize'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `new'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `build_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/index.rb:94:in `block in build_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/caching.rb:58:in `cache_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:257:in `benchmark'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:210:in `find_asset'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:119:in `block in compile'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `each'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `compile'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-rails-2.2.0/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-2.11.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/ubuntu/.rvm/gems/ruby-2.1.3/gems/sprockets-rails-2.2.0/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/home/ubuntu/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by cvrebert** [comment]
X-Ref https://github.com/sass/sass/issues/467 possibly

**Comment by glebm** [comment]
The error is most likely coming from your code, as we already applying the workaround for  https://github.com/sass/sass/issues/467. We also test with Sass 3.2.19 and bootstrap-sass compiles OK.
Perhaps you are using a much older version of bootstrap-sass?
