### ISSUE TITLE
Create 3.0.stable branch

### ISSUE THREAD

**Issue by radar** [twbs/bootstrap-sass#775]
As it says in the title. You've got a 2.0.stable branch and a 2.1.stable branch, and I would like there to be a 3.0.stable branch. My reasons are that I link people to use the `~> 3.0.0` version of `bootstrap-sass` in Rails 4 in Action, and then mention that they can pick-and-choose the assets to import, rather than just doing `@import "bootstrap";`. By being able to link to a 3.0.stable branch, they would have the latest asset lists rather than potentially an asset list from an older version of bootstrap-sass.

**Comment by cvrebert** [comment]
@twbs/sass Ping.

**Comment by glebm** [comment]
To do for 3.3.2 release.

**Comment by glebm** [comment]
There are now stable branches for all the 3.x releases. @radar Sorry about the delay.
