### ISSUE TITLE
Caching Bootstrap Sass

### ISSUE THREAD

**Issue by isaacalves** [twbs/bootstrap-sass#784]
Is it possible to write Sass on top of Bootstrap-Sass without having to compile Bootstrap Sass every time I make changes to my own Sass?

My **main.scss** looks like this:

```
// MY PROJECT DEFAULTS
@import “my_project/variables";

// bower:scss
@import "../bower_components/bootstrap-sass-official/vendor/assets/stylesheets/bootstrap.scss";
// endbower

// ...
```

Bootstrap.scss takes 4-5 seconds to compile with `gulp-ruby-sass`. I don't understand why it is not cached.

**Comment by cvrebert** [comment]
@isaacalves What caching feature are you referring to? Could you give a link to the relevant code/docs?

**Comment by glebm** [comment]
The caching in Ruby Sass does not keep track of the variables *as far as I know*, so it has to recompile everything below the import that changed. This is really a question for http://github.com/sass/sass.
