### ISSUE TITLE
It would be nice to explain why you recommend this?

### ISSUE THREAD

**Issue by behrangsa** [twbs/bootstrap-sass#79]
So on the home page you have mentioned that:

> Import "bootstrap" in your SCSS file of choice to get all of Bootstrap's styles, mixins and variables! Don't use Sproket's //= require directives for SASS files, because they're horrible and will kill your cat.

Why are Sprocket's `//= require` directives horrible? Why do you prefer `@import`? That sentence is not any helpful at all. It is just confusing.

**Comment by jabr** [comment]
Is there an `@import` way to do the equivalent of Sprocket's `= require_tree`?

**Comment by glebm** [comment]
@jabr Glob imports (`@import "a/*"*`) are provided by [sass-rails](https://github.com/rails/sass-rails), and alternatively by [sass-globbing](https://github.com/chriseppstein/sass-globbing). These are both for the ruby Sass, not sure if there is anything for libsass.
