### ISSUE TITLE
strange issue in bootstrap 3 with sass

### ISSUE THREAD

**Issue by Gusduenas** [twbs/bootstrap-sass#791]
I have this problem it seems that bootstrap doesn't look good on my android tablet using android 4.1.2 stock browser and Google chrome. 
![screenshot_2014-12-02-21-51-56](https://cloud.githubusercontent.com/assets/3916674/5275395/9e1ad482-7a71-11e4-8bb8-da3381100d32.png)
The page is on http://realsteelautomotive.com make click on services...thanks for your
Help.

Gus

**Comment by cvrebert** [comment]
See https://github.com/twbs/bootlint/wiki/E014
In the future, please only post issues when you are reasonably sure there is a bug in Bootstrap itself. [Bootlint](https://github.com/twbs/bootlint) your page and ask for troubleshooting help on StackOverflow beforehand next time. Thanks!
