### ISSUE TITLE
Easy font generation

### ISSUE THREAD

**Issue by webfacer** [twbs/bootstrap-sass#792]
Hi,

i wrote a usefull font family generation for sass which i needed in my project, i would need it because it is more than one file to include. Here you can find my snippet:

https://gist.github.com/webfacer/5e9911051d3684ef421f

**Comment by glebm** [comment]
Hi. This is nice, but I'll close this for now as Bootstrap only provides one font

**Comment by webfacer** [comment]
i would recommend it because of some fonts require more than one include, because they are splitted into font-styles and font-weights Bold, Heavy Bold, Italic and so on. Therfore only one include is not enough.
