### ISSUE TITLE
Why the lack of a /dist folder, with minified files?

### ISSUE THREAD

**Issue by cjaoude** [twbs/bootstrap-sass#794]
Why the lack of minified css files? Hating on the SASS users? :)

Rather than set-up a simple /dist copy with Grunt/Gulp, SASS users have to set-up and run this whole workflow just to get these files. Seems arbitrary.

**Comment by thomas-mcdonald** [comment]
Closing because neither of us seem to understand the utility of the request - if you want the distributed minified CSS then you don't need to use the Sass bower project, just use the main one.

**Comment by cjaoude** [comment]
Sorry, I meant to give a response. Got swamped with holidays and moving cities.

To avoid bloat and provide certainty that the end-point is the same. It may happen only once in a blue moon, but it could be that the LESS end-point and the SASS end-point are different. Who knows, they may compile different. (by end-point I mean the dist version)

No disrespect to LESS, but for those of us using SASS, it would be great not to have both packages bloating our projects.
