### ISSUE TITLE
"Sprockets::FileNotFound: couldn't find file 'bootstrap-sprockets'" when processing application.js

### ISSUE THREAD

**Issue by ok11** [twbs/bootstrap-sass#795]
In production environment precompilation fails with the following diagnostics:

remote: rake aborted!
remote: Sprockets::FileNotFound: couldn't find file 'bootstrap-sprockets'
remote:   (in /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/app/assets/javascripts/application.js:15)
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/context.rb:106:in `resolve'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/context.rb:146:in`require_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:217:in `process_require_directive'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:167:in`block in process_directives'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:165:in `each'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:165:in`process_directives'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/directive_processor.rb:99:in `evaluate'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/tilt-1.4.1/lib/tilt/template.rb:103:in`render'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in`each'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in`initialize'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in`block in build_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in`build_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in`cache_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'[K
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in`find_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'[K
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in`initialize'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in`build_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in`cache_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in`find_asset'[K
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:211:in`block in find_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:257:in `benchmark'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:210:in`find_asset'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:119:in `block in compile'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in`each'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/sprockets/manifest.rb:118:in `compile'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:70:in`block (3 levels) in define'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-2.12.3/lib/rake/sprocketstask.rb:146:in `with_logger'
remote: /var/lib/openshift/541424415004469f3a000b85/app-root/runtime/repo/vendor/bundle/ruby/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:69:in`block (2 levels) in define'

Rails 4.1.8, bootstrap-sass 3.3.1.0, also tried 3.3.0.1, same result.

application.js: 

//= require jquery
//= require jquery_ujs
//= require bootstrap-sprockets
//= require tinymce-jquery
//= require jquery.colorbox
//= require jquery.datetimepicker
//= require jquery.raty
//= require cocoon
//= require pagination

**Comment by CJBrew** [comment]
Note: this is broken for me using RefineryCMS but not vanilla Rails.

https://gist.github.com/CJBrew/23183647e23386d4800f
