### ISSUE TITLE
Is it possible to add condition for each bootstrap component file include?

### ISSUE THREAD

**Issue by trk** [twbs/bootstrap-sass#804]
What I mean ?

If you add variables to "_variables.scss" file like :
```scss
$use-navbar: true !default;
$use-navbar-default: true !default;
$use-navbar-inverse: true !default;
```
and usage inside "_navbar.scss" file should be like :

```scss
@if $use-navbar == true {
     // Create navbar css terms.... 
}
@if $use-navbar-default == true {
     // Create default-navbar css terms.... 
}
@if $use-navbar-inverse == true {
     // Create inverse-navbar css terms.... 
}
```
Bootstrap users can overwrite to default settings by importing custom "_variables.scss" file before importing "_bootstrap.scsss" file like:
```scss
// Import Custom Bootstrap Variables
@import "theme/my_custom_bootstrap_variables";
// Import Bootstrap
@import "bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
```
And if we don't need extra navbars or other things "Common CSS, Components, JavaScript components" files, we can quickly disable them bye setting options "true < to > false" and we can apply bootstrap updates quickly via bower and other tools.

**Comment by cvrebert** [comment]
@glebm I presume you'd want this sort of change made upstream (if at all) rather than at the Sass conversion level?

**Comment by glebm** [comment]
This is not possible even in the latest Sass (3.4.9). Attempting to compile such code results in:

```
Error: Import directives may not be used within control directives or mixins.
```

**Comment by thomas-mcdonald** [comment]
Is it possible to push the imports inside of the partials?

**Comment by glebm** [comment]
Yeah, that would work. :+1:

**Comment by cvrebert** [comment]
Perhaps we should punt this to Bootstrap v4?

**Comment by glebm** [comment]
Done

**Comment by mdo** [comment]
Breaking it down by sub-component is interesting, but might be overkill. Could be interesting to explore though.

**Comment by abhilashlr** [comment]
Looks like this an overkill. 
I have the same requirement where only components I need are compiled (am using bower). I replicated the _variables.scss and _bootstrap.scss(renamed this to copy _bootstrap-theme.scss)

You can comment out all unnecessary imports inside your bootstrap-theme leaving out the bower bootstrap folder.

In your app.scss just import bootstrap-theme and your variables copy. Bootstrap-theme will use the components you need and compile it with your variable theming. And updating the bootstrap version will have no impact in your output.
