### ISSUE TITLE
rails 3.2.11 issue

### ISSUE THREAD

**Issue by xingle** [twbs/bootstrap-sass#806]
According to documentation, I used following versions of sass-rails and bootstrap-sass.
<pre>
ruby '1.9.3'
gem 'rails', '3.2.11'
....
gem 'sass-rails', '>= 3.2'
gem 'bootstrap-sass', '~> 3.1.1.0'
</pre>

It throws the following error:
<pre>
File to import not found or unreadable: mixins/hide-text.
Load paths:
  Sass::Rails::Importer( ... /app/assets/stylesheets/admin/global.css.scss )
</pre>

**Comment by cvrebert** [comment]
Please upgrade to bootstrap-sass v3.3.1.0. If that doesn't fix the problem, I'll be happy to reopen this issue.

**Comment by glebm** [comment]
Rails 3.2 is no longer supported. However, you could try with the following gems:

```ruby
# Backport asset pipeline gems for Bootstrap compatibility
gem 'sprockets-rails', '=2.0.0.backport1'
gem 'sprockets', '=2.2.2.backport2'
gem 'sass-rails', github: 'DenisColeman/sprockets-2.2.2.backport'
```

See #523 and #764 for more information.

**Comment by D-system** [comment]
A workaround in application.rb:
```
    config.sass.load_paths ||= []
    config.sass.load_paths << "#{Gem.loaded_specs['bootstrap-sass'].full_gem_path}/assets/stylesheets"
    config.sass.load_paths << "#{Gem.loaded_specs['bootstrap-sass'].full_gem_path}/assets/stylesheets/bootstrap"
```

**Comment by benlangfeld** [comment]
Prefixing all files in `assets/stylesheets/bootstrap/_mixins.scss a lá https://github.com/rails/sass-rails/issues/137#issuecomment-34282875 also worked for me. Would you accept a PR to that effect, @glebm?
