### ISSUE TITLE
Media-left?

### ISSUE THREAD

**Issue by sinrise** [twbs/bootstrap-sass#807]
The Bootstrap website has this in the media object area. .media-left and .media-right don't exist in Bootstrap Sass...

From http://getbootstrap.com/components/#media
"The classes .pull-left and .pull-right also exist and were previously used as part of the media component, but are deprecated for that use as of v3.3.0. They are approximately equivalent to .media-left and .media-right, except that .media-right should be placed after the .media-body in the html."

**Comment by glebm** [comment]
They do exist in bootstrap-sass as well: https://github.com/twbs/bootstrap-sass/blob/v3.3.1/assets/stylesheets/bootstrap/_media.scss#L15
