### ISSUE TITLE
Why are all the table classes prefixed by table-?

### ISSUE THREAD

**Issue by kevdotbadger** [twbs/bootstrap-sass#809]
As the title suggests, why are they prefixed? `<table class="table table-bordered table-condensed">` seems a lil backwards, wouldn't `<table class="table bordered condensed">` make more sense, or is this intentional?

**Comment by Tuckie** [comment]
That would be a debate for https://github.com/twbs/bootstrap

**Comment by thomas-mcdonald** [comment]
Found these buried in a Bootstrap issue

http://markdotto.com/2012/02/16/scope-css-classes-with-prefixes/

http://markdotto.com/2012/03/02/stop-the-cascade/
