### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$alert-padding".

### ISSUE THREAD

**Issue by forever-sumit** [twbs/bootstrap-sass#810]
Hi I'm having the this issue with comfortable-mexican-sofa gem.
I've this issue while assets precompile, during deployment on my staging server, using capistrano script.

    rake aborted!
    DEBUG[df74fefa]     Sass::SyntaxError: Undefined variable: "$alert-padding".
    DEBUG[df74fefa]       (in /home/deploy/apps/cbu_staging/shared/bundle/ruby/2.1.0/gems/bootstrap-sass-3.3.1.0/assets/stylesheets/bootstrap/_alerts.scss:10)
I'm using

  Ruby : '2.1.3'
  Rails : '4.1.5'

Here is my gist url :

   https://gist.github.com/forever-sumit/1de3aa8a878323989ad1

In my gem file I've three Gems which are mostly using

    gem 'devise'
    gem 'activeadmin', github: 'activeadmin'
    gem 'comfortable_mexican_sofa', '~> 1.12.0'

when I've applied the 'active_admin' gem and push to server I've got error in assets precompile 
so I've added this solution for fix the issue (I don't know what issue at that time)

     config.assets.precompile += %w(*.svg *.eot *.woff *.ttf *.gif *.png *.ico)
     config.assets.precompile << /\A(?!active_admin).*\.(js|css)\z/ 

Now I've added gem "'comfortable_mexican_sofa', '~> 1.12.0'" and I've this issue : Sass::SyntaxError: Undefined variable: "$alert-padding"

I've tried with the one solution by adding

    config.assets.precompile += %w(*.js *.css *.svg *.eot *.woff *.ttf *.gif *.png *.ico)

but after this I've got another issue with active admin

    rake aborted!
    DEBUG[d30d2808]     Sass::SyntaxError: Undefined mixin 'global-reset'.
    DEBUG[d30d2808]       (in /home/deploy/apps/cbu_staging/shared/bundle/ruby/2.1.0/bundler/gems/activeadmin-5af560b2b6cd/app/assets/stylesheets/active_admin/_base.css.scss:3)
    DEBUG[d30d2808]     /home/deploy/apps/cbu_staging/shared/bundle/ruby/2.1.0/bundler/gems/activeadmin-5af560b2b6cd/app/assets/stylesheets/active_admin/_base.css.scss:3:in `global-reset'
    DEBUG[d30d2808]     /home/deploy/apps/cbu_staging/shared/bundle/ruby/2.1.0/bundler/gems/activeadmin-5af560b2b6cd/app/assets/stylesheets/active_admin/_base.css.scss:3

I don't have 'apllication.css.scss' file in my assets.
I've tried with rename my application.css file to application.css.scss and remove all the *= require and add the these two lines.

    @import "bootstrap-sprockets";
    @import "bootstrap";

but I didn't get success.
Please let me know what is the exact solution for the issue.

**Comment by forever-sumit** [comment]
I've found the solution. I've these lines in my `application.rb'

    config.assets.precompile += %w(*.svg *.eot *.woff *.ttf *.gif *.png *.ico)
    config.assets.precompile << /\A(?!active_admin).*\.(js|css)\z/ 

after remove them I've no issue with precompile asstes in production env

**Comment by cvrebert** [comment]
X-Ref: #654
