### ISSUE TITLE
requiring javascript from npm does not work

### ISSUE THREAD

**Issue by adamschoenemann** [twbs/bootstrap-sass#812]
I may be using this incorrectly, but I cannot require the bootstrap javascript using `require('bootstrap-sass')`.

Changing the `main` key in `package.json` to point to `assets/javascripts/bootstrap.js`, instead of the non-existent `index.js` appears to fix the issue.

**Comment by cvrebert** [comment]
Yeah, the current `main` value makes no sense.

**Comment by gitnik** [comment]
How would I require just a single file?

**Comment by cvrebert** [comment]
@gitnik Use [require.resolve()](https://nodejs.org/api/globals.html#globals_require_resolve) and combine the result with the relative path to the file you want.
