### ISSUE TITLE
Take over bootstrap-sass in bower

### ISSUE THREAD

**Issue by kenips** [twbs/bootstrap-sass#813]
bootstrap-sass has been unregistered from bower for transfer to twbs so please take it over! See https://github.com/jlong/sass-bootstrap-defunct/issues/143.

**Comment by glebm** [comment]
:tada:

**Comment by thomas-mcdonald** [comment]
How does this work for people currently on bootstrap-sass-official? Can we display a message to people trying to upgrade?

**Comment by glebm** [comment]
Both of the names are pointing to the same git repo, so they don't have to change. I don't see how we could display a message, since we can't access the Bower data from just Sass.
