### ISSUE TITLE
_carousel.scss misses vendor prefixes for translate3d and transform

### ISSUE THREAD

**Issue by kozlitinaelja** [twbs/bootstrap-sass#820]
in _carousel.scss Line #30, Line #36, Line #41, Line #47 doesn't use vendor prefixes mixins. Because of that carousel's slide effect is broken on Safari (Safari still needs prefixes for translate3d). However, the compiled version  frpm CDN (https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.css) has all prefixes in place. 

P.S. Vendor prefixes may be missed not only in _carousel.scss, I haven't check other files.

**Comment by glebm** [comment]
This is a known issue and has already been fixed in the next branch. Please use autoprefixer meanwhile, it's best to do so anyway. See #771 for more information.
