### ISSUE TITLE
Sass Number Precision with node-sass (libsass)

### ISSUE THREAD

**Issue by eddiegroves** [twbs/bootstrap-sass#821]
I'm using node-sass and configured precision to 10. Example of compiled sass:

```
.col-xs-1 {
  width: 8.3333333333%;
}

```

However when comparing this to the [standard bootstrap.css](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L1638) it has less precision (8):

```
.col-xs-1 {
  width: 8.33333333%;
}
```

Should I just use 8 as the precision with node-sass?

**Comment by glebm** [comment]
Yes, 8 should be OK. Good catch. We erred on the side of caution here, but since it's not causing issues for the upstream, bootstrap-sass should specify 8 as well.
