### ISSUE TITLE
gradient-vertical not working in Firefox 35 Mac

### ISSUE THREAD

**Issue by allaire** [twbs/bootstrap-sass#825]
Can't get Firefox to play nice with gradient-vertical mixin:

`@include gradient-vertical(#ffffff, #f1f1f1, 0%, 100%);`

Bourbon works well (https://github.com/thoughtbot/bourbon/blob/bd861f84d5452be9d8b73a196006cf43ffd10013/app/assets/stylesheets/css3/_linear-gradient.scss):

`@include linear-gradient(to bottom, #ffffff 80%, #f1f1f1 100%);`

**Comment by glebm** [comment]
Bootstrap requires the use of [Autoprefixer](https://github.com/postcss/autoprefixer) to add browser vendor prefixes automatically. For Rails integration see [autoprefix-rails](https://github.com/ai/autoprefixer-rails).

**Comment by cvrebert** [comment]
Closing since that's most likely the right explanation and it's been 5 days.

**Comment by mravery** [comment]
@allaire: Were you able to resolve your Autoprefixer issue? I have the exact same problem. I'm using a rails system and the gem is installed as `autoprefixer-rails (5.1.11)`. Unfortunately I can't just use the autoprefixer syntax... it's clear that auto-prefixed isn't working but I don't know how to start trouble shooting it. More details here: http://stackoverflow.com/questions/29987528/how-do-i-trouble-shoot-autoprefixer

**Comment by allaire** [comment]
@mravery Used bourbon.io
