### ISSUE TITLE
Glyphicons broken on version 3.3.3

### ISSUE THREAD

**Issue by maurosbu** [twbs/bootstrap-sass#828]
Hi, glyphicons broken on version 3.3.3. 
They works on version 3.3.2.1.

**Comment by jwallerf** [comment]
We are having this same issue.

**Comment by glebm** [comment]
Are you using Rails? Please make sure `bootrap-sprockets` is imported before `bootstrap`.

**Comment by maurosbu** [comment]
Hi, yes I'm using rails 4.2.0 and I import bootstrap-sprockets before bootstrap.

    @import "bootstrap-sprockets";
    @import "bootstrap";

It works with version 3.3.2.1, it is broken in version 3.3.3.

**Comment by glebm** [comment]
Are there any `//= require` statements in the file that imports bootstrap? What version of Sass are you using? Which web browser?

**Comment by glebm** [comment]
v3.3.2.1 code is [the same](https://github.com/twbs/bootstrap-sass/compare/v3.3.2+1...v3.3.3) as v3.3.3. Please try clearing the cache ( `rm -rf tmp/cache`) and restarting the server.

**Comment by ethanclevenger91** [comment]
I've noticed that adding quotes around the content in `_glyphicons.scss` gets mine to show up. Otherwise, upon inspection, they don't get a `before` element, which implies to me the content isn't being read correctly. Compiling with gulp-sass.

**Comment by ethanclevenger91** [comment]
Which I just noticed is the case. Is the compressed bootstrap on the bootstrap site up to date?

**Comment by cvrebert** [comment]
@ethanclevenger91 The content is quoted in bootstrap-sass v3.3.3: https://github.com/twbs/bootstrap-sass/blob/21098b331e67a223349d271e646ebec775ffa4d3/assets/stylesheets/bootstrap/_glyphicons.scss#L35

**Comment by cvrebert** [comment]
Closing for now due to lack of response from OP. Presumably this is just the caching issue that glebm mentioned.

**Comment by ctilley83** [comment]
not a caching issue for me. Same problem same version of rails and bootstrap-sass

**Comment by kkirsche** [comment]
I think it's due to incorrect display code @ctilley83 

See my post on StackOverflow: http://stackoverflow.com/questions/28284313/rails-twbs-bootstrap-sass-trouble-accessing-glyphicons

**Comment by kkirsche** [comment]
@cvrebert the stackoverflow answer I provided was accepted as solution by @ctilley83, I would say if the  OP doesn't follow up this could be closed, but obv. that's your call

**Comment by helmutrs** [comment]
when you double quote the content, the only it does is give you an empty square, without the quotes, it doesn't show anything.
