### ISSUE TITLE
Navbar (fixed navbar) dropdown menu broken on 3.3.3, 3.3.2

### ISSUE THREAD

**Issue by FranzZemen** [twbs/bootstrap-sass#829]
Works on 3.3.1, not on 3.3.2 or 3.3.3.

Clicking on the drop down does nothing.  Regular <li> menu items work.

**Comment by FranzZemen** [comment]
Also works on 3.3.2

**Comment by cvrebert** [comment]
What OS and browser are you using?

**Comment by FranzZemen** [comment]
Chrome, Windows OSX centOS

**Comment by FranzZemen** [comment]
In addition, here is the relevant markeup.  The products menu doesn't
expand under the said versions.  All I change is the sassbootstrap version
back to .1 and it works.

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <nav class="navbar navbar-default navbar-fixed-top">
                        <div class="container">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle
collapsed" data-toggle="collapse"
                                        data-target="#nav1">
                                    
                                    <span class="sr-only">Toggle
Navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="#"><img
src="assets/images/PAVOCOM_LOGO.svg"></a>
                            </div>
                            <div class="collapse navbar-collapse" id="nav1">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a id="homeMenu"
href="#" ng-click="menu('homeMenu')">Home</a></li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle"
data-toggle="dropdown" role="button">Products
                                            <span class="caret"></span></a>
                                        <ul class="dropdown-menu"
role="menu">
                                            <li><a id="fleetmanagementMenu"
href="#" ng-click="menu('fleetmanagementMenu')">Fleet Management</a></li>
                                            <li><a id="networkservicesMenu"
href="#" ng-click="menu('networkservicesMenu')">Network Services</a></li>
                                            <li><a id="cloudservicesMenu"
href="#" ng-click="menu('cloudservicesMenu')">Cloud Services</a></li>
                                            <li><a id="mobileservicesMenu"
href="#" ng-click="menu('mobileservicesMenu')">Mobile Services</a></li>
                                        </ul>
                                    </li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    <li><a id = "contactUsMenu" href="#"
ng-click="menu('contactUsMenu')">Contact Us</a></li>
                                    <li><a id = "ourFirmMenu" href="#"
ng-click="menu('ourFirmMenu')">Our Firm</a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
blah blah blah stuff goes here.
</div>

**Comment by cvrebert** [comment]
@FranzZemen Could you post an example that doesn't involve Angular?

**Comment by shawnacscott** [comment]
Here's a reproduction case: https://gist.github.com/shawnacscott/e4b5054cf61589b14cc7

I'm having this issue as well, though with a Rails installation. Reverting to 3.3.1 fixes the problem for me.

OS X 10.10.1
Firefox Developer Edition 37.0a2 (2015-02-03)

**Comment by cvrebert** [comment]
@shawnacscott Please confirm that you're using Autoprefixer.

**Comment by shawnacscott** [comment]
I have `gem 'autoprefixer-rails', '>= 5.0'` in my Gemfile, and Gemfile.lock shows:
````
autoprefixer-rails (5.1.1)
      execjs
      json
````
and

````
bootstrap-sass (3.3.3)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
````

Here's a gist of my full Gemfile: https://gist.github.com/shawnacscott/08c89617d339da88ca02

**Comment by calderon** [comment]
I have a very similar problem indeed. I'm using latest version of bootstrap-sass, and I get bootstrap menu collapse/expand, but after clicking a menu item, it doesn't change the text/value of the button. I've tried with bootstrap-sass 3.3.1, 3.3.2 and 3.3.3. HTML markup is ok, I've revised this, even I copied a dropdown example from bootstrap web, with same result.

**Comment by glebm** [comment]
How are you including the JavaScript?

**Comment by FranzZemen** [comment]
In my case I'm using angular-fullstack, so its via bower components and
then concatenated, minified etc.  However, I have a dev build that doesn't
concatenate or minify, just includes the bower files via script tag, same
result.

**Comment by shawnacscott** [comment]
Your wish is my command, @glebm :)

**Comment by glebm** [comment]
@shawnacscott In your example Bootstrap javascript is included twice: `bootstrap-sprockets` provides individual bootstrap JS files (alert.js, dropdown.js), while
`bootstrap` provides a concatenated file with all of the bootstrap JS in it. Only one of these should be required, not both. I realize how confusing this must be given that for Sass, both `bootstrap-sprockets`, which provides Sprockets asset path support, and `bootstrap` must be imported.

**Comment by shawnacscott** [comment]
Thanks, that was it. I'll send a PR adding a caveat in the README.
