### ISSUE TITLE
sass-rails 5.0 and sprockets 3.0 drop support for .css.scss extensions

### ISSUE THREAD

**Issue by jaredbeck** [twbs/bootstrap-sass#831]
**sass-rails 5.0 "dropped support to .css.scss extensions** on sass-rails master" -Rafael França (https://github.com/rails/sass-rails/issues/290)

- The commit that drops support:
  https://github.com/rails/sass-rails/commit/d355de9b5aa8b79576c9afcadb58ebe164155861
- Discussion: https://github.com/rails/sass-rails/issues/290

**sprockets 3.x deprecates .css.scss extensions.**

> [.js.coffee, .css.scss] will be completely unsupported in Sprockets 4.x. Which is why they're now soft deprecated in 3.x" - Joshua Peek (https://github.com/rails/sass-rails/issues/290)

- The commit that drops support:
  [Remove support for .js.coffee, .css.scss, just use .coffee or .scss][1]
- [Announcement, sprockets 3.0][2]
- [Discussion, sprockets 4.0][3]

**However, the boostrap-sass readme says:**

> Import Bootstrap styles in app/assets/stylesheets/application.css.scss .. 
> Make sure the file has .css.scss extension ..

So, I think that the readme must be updated?

[1]: https://github.com/sstephenson/sprockets/commit/da2f1d176de6fae0bafc71e9cbf7805271856933
[2]: https://github.com/sstephenson/sprockets/issues/643
[3]: https://github.com/sstephenson/sprockets/pull/632

**Comment by glebm** [comment]
Thanks!
