### ISSUE TITLE
Incorrect glyphicon displayed inside button

### ISSUE THREAD

**Issue by onebree** [twbs/bootstrap-sass#834]
- **Ruby 1.9.3., Rails 4.2.0**
-  **bootstrap-sass (3.3.3)**
- **Firefox ESR 31.3.0**

I am editing the view of a page, and replacing a text link with a button link. I figured out how to correctly do so; however, the glyphicon generated does not match what I chose in the view.
```haml
%a{class: "btn btn-warning", role: "button", href: edit_ip_path(ip)}
  %span.glyphicon.glyphicon-pencil
```
Instead, some envelope (or whatever) appears. Interestingly enough, even the browser's dev panel shows I entered `glyphicon-pencil`: 
![screenshot from 2015-01-22 16 53 40](https://cloud.githubusercontent.com/assets/9038433/5865433/43217668-a257-11e4-8104-792a30934060.png)

To make sure the icon was not a weird-shaped pencil, I tested `glyphicon-star`:
![screenshot from 2015-01-22 16 55 54](https://cloud.githubusercontent.com/assets/9038433/5865463/8d0b438a-a257-11e4-90da-39d871233f80.png)

As a real kicker, this is `glyphicon-remove`:
![screenshot from 2015-01-23 11 41 02](https://cloud.githubusercontent.com/assets/9038433/5878425/bddb6ad8-a2f4-11e4-8dac-6137a19bca31.png)

**Comment by cvrebert** [comment]
Please upgrade to bootstrap-sass v3.3.3

**Comment by glebm** [comment]
This looks like the Sass (_glyphicons.scss) in not the same version as the icon font files. Perhaps this is caused by a stale cache, try:

```
rm -rf tmp/cache
# Then restart the server
```

Are any icon fonts present in `app/vendor/assets/fonts/bootstrap`? What is the $icon-font-path variable set to?

**Comment by onebree** [comment]
@cvrebert I updated the gem, and no success.

@glebm I have `glyphicons-halflings-regular` in eot/svg/ttf/woff/woff2 in `app/assets/fonts/`. Should I move the files to `/fonts/bootstrap/`?
```scss
//app/assets/stylesheets/bootstrap_and_overrides.scss
$iconSpritePath: asset-url('glyphicons-halflings.png');
$iconWhiteSpritePath: asset-url('glyphicons-halflings-white.png');

//app/assets/stylesheets/_colors.scss
$icon-font-path:    "../fonts/";
$icon-font-name:    "glyphicons-halflings-regular";
```

**Comment by glebm** [comment]
@onebree Try removing all of the variables above:

The `$iconSpritePath` and `$iconWhiteSpritePath` variables are from Bootstrap 2 and are no longer used in Bootstrap 3.

On Rails, default settings take care of the icons. The gem's icons are used, so there is no need to copy them. The default `$icon-font-path` is `"bootstrap/"`. Remove the old version of Bootstrap fonts from `app/assets/fonts/`.

Please also make sure that `bootstrap-sprockets` gets [@imported](https://github.com/twbs/bootstrap-sass#a-ruby-on-rails) before `bootstrap`.

**Comment by onebree** [comment]
Should I remove those sprite variables then?

At the moment, our repo does not have a folder for fonts, nor a bootstrap folder. Will the icons still display on other computers that do not have glyphicon fonts installed? I am new to web design and just trying to get a grasp.

`bootstrap-sprockets` is the first thing imported in our file.

**Comment by burnt43** [comment]
@onebree  in your `app/assets/stylesheets/_colors.scss` file try using:
```sass
$icon-font-path:          "../assets/";
```

I had a similar issue.

**Comment by onebree** [comment]
Thank you! That helped.
