### ISSUE TITLE
Glyphicons don't render on Rails served with Unicorn/Nginx

### ISSUE THREAD

**Issue by shawnacscott** [twbs/bootstrap-sass#838]
I am attempting to convert a Rails app from using included Bootstrap source files to using the bootstrap-sass gem. Glyphicons are not served on development or staging served through our normal Nginx/Unicorn configuration. 

If I force the app to serve through the default Rails server, it serves Glyphicons correctly. All of these different environments appear to request from the same URL (GET http://example.com/assets/bootstrap/glyphicons-halflings-regular.woff), but the Nginx/Unicorn configuration results in a 404, while the default Rails server gets a 200.

I haven't created a test case, since it would likely require duplicating our virtual machine's environment, but if necessary, I can try and do that.

## Versions:
Rails version: 4.1.8
Boostrap-sass version: ~> 3.3.1
Sass-rails version: ~> 5.0.0
Autoprefixer-rails version: ~> 4.0.2.2
Unicorn version: 4.6.3

## Configuration:
development.rb
````
  config.cache_classes = false
  config.eager_load = false
  config.consider_all_requests_local  = true
  config.action_controller.perform_caching = false
  config.serve_static_assets  = true
  config.assets.debug = true
````

production.rb
````
config.cache_classes = true
config.eager_load = true
config.consider_all_requests_local = false
config.action_controller.perform_caching = true
config.serve_static_assets = false
````

application.css.scss
````
@import 'bootstrap-sprockets';
@import 'bootstrap';
````

cc @benprew in case more information is needed

Thanks in advance for any help or insight you can offer!

**Comment by shawnacscott** [comment]
After taking another look at this, @benprew was able to narrow it down to an Nginx configuration problem. I'll close this issue, and document what we find here once we discover the final culprit.

Thanks!

**Comment by KevinBongart** [comment]
Hi, I'm having the same issue but can't find a solution:

The glyphicons halflings fonts are served fine in development using Thin, and in production they are compiled with the other assets (see below), but Nginx gets 404s for the `ttf` and `woff` ones.

```
public/assets/bootstrap/glyphicons-halflings-regular-be7f9c3a65ad4f8e0fb23fdfef309fa0.eot
public/assets/bootstrap/glyphicons-halflings-regular-5ddb81039225535d2a9995803dd92dd4.svg
public/assets/bootstrap/glyphicons-halflings-regular-d104137b610a62d32b2e8999d563147e.ttf
public/assets/bootstrap/glyphicons-halflings-regular-5c464455e1f35ca671a4d37aa6e7a8f0.woff
public/assets/bootstrap/glyphicons-halflings-regular-bab5a6ea5851706ad2df31b9e866b3c7.woff2
```

This used to work with bootstrap-sass (3.3.1.0), sass (3.4.9) and sass-rails (5.0.1), but broke when upgrading to bootstrap-sass (3.3.3) and sass (3.4.12).

Any help would be greatly appreciated!
