### ISSUE TITLE
Angular bootstrap-ui carousel broken in 3.3.3 [Chrome only]

### ISSUE THREAD

**Issue by aromanyuk** [twbs/bootstrap-sass#840]
I must use 3.2.0, because in Chrome  40.0.2214.94 (64-bit) [MAC OS Yosemite] in some case transform3d didn't work, i can give you link for site where this issue can be reproduced to test in private messaging

**Comment by cvrebert** [comment]
We cannot help you with Angular-related problems. Can you reproduce the problem without Angular? 
Are you using Autoprefixer?
Can you reproduce the problem with Less-based Bootstrap?

**Comment by cvrebert** [comment]
Closing due to lack of response.
