### ISSUE TITLE
How to use bootstrap-sass with Rails 4.2

### ISSUE THREAD

**Issue by stopanko** [twbs/bootstrap-sass#843]
How i Connect Bootstrap for Rails 4.2
1--After add bootstrap make shure that your active admin(if you use it) don`t include his styles into your other pages.
create admin folder into javascripts and stylesheets directories and move active admin css and js files into. Change *= require_tree .
into
*= require_directory .
in application js and css files and add in
config/initialize/active_admin.rb

config.clear_stylesheets!
config.register_stylesheet 'admin/active_admin'
config.clear_javascripts!
config.register_javascript 'admin/active_admin'

config/initialize/assets.rb
Rails.application.config.assets.precompile += %w( admin/active_admin.css )
Rails.application.config.assets.precompile += %w( admin/active_admin.js )

restart server!!

2---Then connect bootstrap
Add to ypur gamefile
gem 'bootstrap-sass'
gem 'sass-rails', '~> 5.0'  #if not required

bundle install 

rename application.css to application.css.scss
and add to the and
@import "bootstrap-sprockets";
@import "bootstrap";

After add in application.js
//= require  bootstrap

restart server!!

**Comment by gkatsanos** [comment]
and how do you get sourcemaps?

**Comment by stopanko** [comment]
Where you see a sourcemaps files?
http://storage3.static.itmages.com/i/15/0220/h_1424455668_6825667_7667d30162.png
And why you need this files? In production Rails will compile all assets.

**Comment by gkatsanos** [comment]
That's my problem, I don't see them.

Why ? For debugging of course. I'm guessing you've never used them ? Look it up, it's a necessary feature.

**Comment by glebm** [comment]
Active Admin has nothing to do with Bootstrap setup. There is already a guide for Rails in the Readme. Not sure if there is a good solution for source maps at the moment, but they are on the roadmap for Sprockets 4.0 https://github.com/sstephenson/sprockets/issues/643

**Comment by stopanko** [comment]
Active Admin as default will connect in your stylesheets folder and can overwrite you pages styles. After some configurations you can connect active admin styles only on admin page.
