### ISSUE TITLE
renamed bower package?

### ISSUE THREAD

**Issue by markusfalk** [twbs/bootstrap-sass#844]
is the official sass port no more available under the bower name of "bootstrap-sass-official"?

I can't update my project's dependencies.

**Comment by glebm** [comment]
It's just `bootstrap-sass` now, though the other package should still work, strange.

**Comment by markusfalk** [comment]
This is what I get:

```bower ENORESTARGET  Tag/branch ~3.2.0+2 does not exist``` 

looks like it has nothing to do with the rename. Its just that ```bower search boostrap-sass-official``` returns "no results"

**Comment by cvrebert** [comment]
I can confirm that `bootstrap-sass` works and `bootstrap-sass-official` doesn't.
Not sure it's worth trying to take any action here. Bower doesn't have any notion of deprecation or renaming, AFAICT. And we don't want `bootstrap-sass-official` to be a permanent alias, so...

**Comment by glebm** [comment]
Please use `bootstrap-sass`.
