### ISSUE TITLE
Comment out codes in _bootstrap-variables.scss are written in sass syntax(missing semicolon).

### ISSUE THREAD

**Issue by kanonji** [twbs/bootstrap-sass#846]
I installed bootstrap-sass and try to change some variables in _bootstrap-variables.scss.
I have found all lines missed semicolon.
This is not big problem, but bit troublesome to override variables.
I hope this will be fixed.
I guess just replacing templates/project/_bootstrap-variables.sass with _bootstrap-variables.scss written in scss syntax.

```
// Override Bootstrap variables here (defaults from bootstrap-sass v3.3.3):

//
// Variables
// --------------------------------------------------

//== Colors
//
//## Gray and brand colors for use across Bootstrap.

// $gray-base:              #000
// $gray-darker:            lighten($gray-base, 13.5%) // #222
// $gray-dark:              lighten($gray-base, 20%)   // #333
// $gray:                   lighten($gray-base, 33.5%) // #555
// $gray-light:             lighten($gray-base, 46.7%) // #777
// $gray-lighter:           lighten($gray-base, 93.5%) // #eee
[snip]
```
_bootstrap-variables.scss

```
$ compass install bootstrap -r bootstrap-sass --force
directory public/assets/fonts/bootstrap/
directory public/assets/js/bootstrap/
directory public/assets/sass/
   create public/assets/sass/styles.scss
   create public/assets/sass/_bootstrap-variables.scss
   create public/assets/js/bootstrap/affix.js
   create public/assets/js/bootstrap/alert.js
   create public/assets/js/bootstrap/button.js
[snip]
```
I opened _bootstrap-variables.scss just after `compass install`.

**Comment by glebm** [comment]
@chriseppstein Is there a way to provide the template in the right syntax?

**Comment by graemeblackwood** [comment]
I've just discovered the same thing – not a huge deal but a bit annoying and possibly confusing for people new to sass. I see it's in the roadmap to fix, which is great, thanks!

**Comment by glebm** [comment]
@graemeblackwood It's in the roadmap but unfortunately I have no idea how to tell compass to provide the template based on the user's preferred syntax

**Comment by martonbaranyai** [comment]
@glebm how do you normally use the template file / override variables then? I understood this semicolon thing would be an extra possibility only, or? Thanks!

**Comment by cvrebert** [comment]
@glebm Where are we at on this? Perhaps we should WontFix this?

**Comment by glebm** [comment]
@cvrebert There is still no way to provide the template in the matching syntax AFAIK. Closing as won't fix.

**Comment by aurora-johansen-wardigo** [comment]
I just sat and fixed this file as a result of having to poach somethings from a formerly config'd LESS file. Just change the extension on it.
[_bootstrap-variables.txt](https://github.com/twbs/bootstrap-sass/files/448345/_bootstrap-variables.txt)
