### ISSUE TITLE
Glyphicons don´t show up with rails 4.2 and bootstrap 3.3.3 in development environment

### ISSUE THREAD

**Issue by fjdeveloper** [twbs/bootstrap-sass#849]
I have fonts in /app/assets/fonts/bootstrap

In the file applications.js 
//= require bootstrap-sprockets	
//= require bootstrap	

In the file application.css.scss
@import "bootstrap-sprockets";
@import "bootstrap";

In the file Gemfile
gem 'bootstrap-sass', '~> 3.3.3'
gem 'sprockets-rails'
gem 'sass-rails', '~> 5.0'

I don´t see the glyphicons when I load the main page with a proper code.

Can anybody help me?

**Comment by crispinh2o** [comment]
Check your Chrome-browser console, you have any font path error?

**Comment by cvrebert** [comment]
Based on #831, seems like your file is supposed to be named `application.scss` instead of `application.css.scss`

**Comment by cvrebert** [comment]
Closing due to lack of further response from OP.
