### ISSUE TITLE
$state-succes-border not used

### ISSUE THREAD

**Issue by plyworks** [twbs/bootstrap-sass#859]
Hi,

For Feedback states in the variables.scss the Feedback State values * $state-succes-border, $state-info-border and state-warning-border* variable are defined:

However, in the * _forms.scss* file the feedback states starting at line 352 don't use the declared border values in the call to the mixin, but the text values instead

    .has-success {
    @include form-control-validation($state-success-text, $state-success-text, $state-success-bg);
    }

Is it possible to change this to

    .has-success {
    @include form-control-validation($state-success-text, *$state-success-border*, $state-success-bg);
   }

Thanks in advance!

Kind regards,
Theo

**Comment by cvrebert** [comment]
Requests for substantive style changes should be filed with the upstream project (https://github.com/twbs/bootstrap ), rather than here.

**Comment by cvrebert** [comment]
Duplicate of https://github.com/twbs/bootstrap/issues/12731
