### ISSUE TITLE
How to set $icon-font-path for development vs. production

### ISSUE THREAD

**Issue by nareshbhatia** [twbs/bootstrap-sass#860]
I am using bootstrap-sass with bower, gulp and gulp-sass (there is no Ruby involved). To get icons working, I am setting up `$icon-font-path` as follows in my main.scss:

    $icon-font-path: "../bower_components/bootstrap-sass/assets/fonts/bootstrap/";
    @import "../bower_components/bootstrap-sass/assets/stylesheets/bootstrap";

This works perfectly for the dev build - the icon fonts are picked up correctly from the bower_components directory. However for my production build, this does not work. My production folder structure is as follows:

    /
    |--- fonts
    |    `--- glyphicons-hallings-xxx
    `--- styles
         `--- main.css

To make this work I have to change my main.scss as follows:

    $icon-font-path: "../fonts/";
    @import "../bower_components/bootstrap-sass/assets/stylesheets/bootstrap";

What's the best approach to make the dev and production builds to work correctly without making changes to my main.scss?

**Comment by cvrebert** [comment]
General non-Bootstrap-specific Sass questions like this are outside the scope of this issue tracker, which is for bug reports and feature requests only. Try asking on a general Sass community forum instead, such as https://groups.google.com/forum/#!forum/sass-lang or perhaps http://stackoverflow.com/questions/tagged/sass.
Good luck!

**Comment by nareshbhatia** [comment]
@cvrebert, thanks for pointing me in the right direction.
