### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by mbillard** [twbs/bootstrap-sass#861]
The latest release is `3.2.0`, yet the less version is at `3.3.2` and the tags go up to `3.3.3`.

Thanks

**Comment by shadowii** [comment]
Also, for what it's worth, the getbootstrap site still links to the 3.3.2, which has the glyphicon bug fixed by [this](https://github.com/twbs/bootstrap-sass/commit/daeb43dcc7b0ab06328acaca0549ee68c039aaa6) in 3.3.3.

**Comment by cvrebert** [comment]
Fixed by adding proper [GitHub Release entries](https://github.com/twbs/bootstrap-sass/releases) for the relevant versions.

**Comment by cvrebert** [comment]
@twbs/sass Friendly reminder: Going forward, y'all will need to create [GitHub Release](https://github.com/twbs/bootstrap-sass/releases) entries when releasing new versions; otherwise the "Latest release" badge will become outdated like this again.

**Comment by glebm** [comment]
@cvrebert Thanks a lot for fixing it! We've been using Changelog, but I will copy the notes from changelog over to releases from now on.
