### ISSUE TITLE
rake aborted! Sass::SyntaxError: Undefined variable: "$alert-padding"

### ISSUE THREAD

**Issue by jitendravyas** [twbs/bootstrap-sass#863]
I downloaded Bootstrap's Sass port via Bower yesterday and my project is in ruby on rails. During precompilation process I'm getting this error for _alerts.scss.

https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_alerts.scss

```
rake aborted!
Sass::SyntaxError: Undefined variable: "$alert-padding".
  (in /Users/jitendravyas/Sites/milaap/vendor/assets/components/bootstrap-sass-official/assets/stylesheets/bootstrap/_alerts.scss:10)
```

**Comment by glebm** [comment]
Have you followed the instructions here? https://github.com/twbs/bootstrap-sass#bower-with-rails
How are you importing bootstrap?

**Comment by westonganger** [comment]
Im having this issue too. Im using the gem version. heres my application.css.scss

```
/*
 *= require_tree .
 *= require_self
*/

@import "bootstrap-sprockets";
@import "bootstrap";
```

**Comment by westonganger** [comment]
the problem actually lies in config/intializers/assets.rb or config/environments/production.rb

Rails.application.config.assets.precompile += %w( * )
You shouldnt precompile all, instead selectively precompile additional assets as needed

**Comment by akz92** [comment]
Thank you @westonganger. After remove that precompile all line I was still getting the "undefined alert-padding" error and to solve it I had to remove this line:
```javascript
config.assets.precompile =  ['*.js', '*.css', '*.css.erb']
```
from config/environments/production.rb

**Comment by alirezaa** [comment]
There is stackoverflow about this too
http://stackoverflow.com/questions/21911620/rails-bootstrap-sass-assets-compilation-error-undefined-variable-alert-padding

**Comment by brauliobo** [comment]
yeah, I confirm that the problem is with `*.css` on `config.assets.precompile`. You need to be more specific.

**Comment by cvrebert** [comment]
Refs #654.
