### ISSUE TITLE
img-retina mixin lower the value of 2?

### ISSUE THREAD

**Issue by tehmaestro** [twbs/bootstrap-sass#864]
Hey, so I'm using `img-retina` mixin and I think we need to change the value of 2, with something smaller, like 1.5 . I'm looking at a Sony Ericsson with 540 x 960 and the images are blurry.

What do you guys think?

**Comment by cvrebert** [comment]
Non-Sass-specific change proposals should be directed to the upstream repo instead: https://github.com/twbs/bootstrap/issues
