### ISSUE TITLE
packagist.org not updated with 3.3.4

### ISSUE THREAD

**Issue by martinlindhe** [twbs/bootstrap-sass#870]
https://packagist.org/packages/twbs/bootstrap-sass

maybe is github service hook not working?

/m

**Comment by glebm** [comment]
Seems to be working for me. There is no service hook, I think it just polls, and perhaps there is a slight delay due to caching.

**Comment by glebm** [comment]
I'll set up a service hook

**Comment by glebm** [comment]
Should be working now

**Comment by martinlindhe** [comment]
awesome, thanks!
