### ISSUE TITLE
Strange file mode

### ISSUE THREAD

**Issue by ukoloff** [twbs/bootstrap-sass#873]
For v3.3.4 all installed files has strange file mode 0640 (not world readable).

As a result font files are not accessible to Web server (HTTP/403)

This happens inside gem file. In git repo file has 0644 mode.

**Comment by kolodovskyy** [comment]
After each deploy got same

**Comment by glebm** [comment]
This is really strange, I am having a look

**Comment by glebm** [comment]
I have confirmed the issue. Rebuilding the gem from source (the same everything) does not reproduce the issue. :astonished:

**Comment by glebm** [comment]
Just realized I've built the gem on my office machine. My office machine has a custom version of Linux with all sorts of security lockdowns, so this could be it.

**Comment by glebm** [comment]
Yanked 3.3.4, released 3.3.4.1. Thank you for a great bug report and apologies for the pain this must have caused.
