### ISSUE TITLE
bootstrap-compass font path force to be absolute

### ISSUE THREAD

**Issue by simongcc** [twbs/bootstrap-sass#875]
I upgraded the Boostrap Sass to 3.3.4.1 from 3.3.3, using Compass 1.1.0.alpha.3 in Win8/Pro

Because I need to use a relative path for the Boostrap Sass, I try to find the solution.
And I come up with #650 

I am using the import like:
@import "bootstrap-compass";
@import "bootstrap";

However the path is still absolute, not relative. I have refer to #662 also.
So, how to change the path correctly?

**Comment by glebm** [comment]
By default, when using Compass `$icon-font-path` will be `"bootstrap/"`, but you can override it:

```
$icon-font-path: "../fonts/bootstrap/"
```

**Comment by simongcc** [comment]
@glebm Thanks for your suggestion, but then it appear an error `(not enough parent directories) 'font-url'`
If I remove the "..", it work again, not sure how's it operate.
