### ISSUE TITLE
Button mixins

### ISSUE THREAD

**Issue by Cogax** [twbs/bootstrap-sass#877]
My problem was that in Drupal (CMS) i can't access every HTML tag for a link. When i don't access it, i add the .btn class to the a tag by using jQuery (dirty solution). I know i should access the html but in Drupal sometimes this is difficult. 

So i decided to make/change some mixins wich i can include on the links. I've not yet finished but i wonder why this is not standard? 
My solution: https://github.com/Cogax/bootstrap-sass/commit/f99a381781cfb6e8bd34ccfcb195ee5509d381b9

ps: sorry for my bad english

**Comment by cvrebert** [comment]
Issues not related to neither the Less=>Sass translation process nor to packaging should be reported upstream to https://github.com/twbs/bootstrap/issues instead of to here.
