### ISSUE TITLE
node-sass 3.0.0 beta support

### ISSUE THREAD

**Issue by Soliah** [twbs/bootstrap-sass#879]
Looks like bootstrap-sass can't be built with latest beta builds of node-sass (3.0.0-beta.4). 

```
192-168-1-10.tpgi.com.au ❯❯❯ ~/Code/bootstrap-sass
❯ node-sass -v
node-sass	3.0.0-beta.4	(Wrapper)	[JavaScript]
libsass  	3.2.0-beta.2	(Sass Compiler)	[C/C++]

192-168-1-10.tpgi.com.au ❯❯❯ ~/Code/bootstrap-sass
❯ test/node_sass_compile_test.sh
{
  "message": "You may not @extend an outer selector from within @media.\nYou may only @extend selectors within the same directive.\nFrom \"@extend .input-sm\" on line 48 of assets/stylesheets/bootstrap/_input-groups.scss\n",
  "column": 39,
  "line": 189,
  "file": "/Users/Chris/Code/bootstrap-sass/assets/stylesheets/bootstrap/_forms.scss",
  "status": 1
}
node-sass compilation failed
```

There doesn't seem to be an issue tracking compatibility with the betas so I thought I'd raise an issue.

**Comment by glebm** [comment]
This may be a know bug in libsass: https://github.com/sass/libsass/issues/943

**Comment by Kuzirashi** [comment]
+1, same problem.

**Comment by charlatan154** [comment]
+1, same issue.

**Comment by rgaidot** [comment]
+1, same issue.

**Comment by joostfarla** [comment]
I've tested with the latest libsass version, but the problem remains. For now I've created a workaround by adding a custom requirement to my ```package.json```, which points to an older (working) version of ```node-sass```:

```yaml
...
"node-sass": "sass/node-sass#v3.0.0-pre",
...
```

**Comment by AW-UC** [comment]
@joostfarla if you experience this issue with latest beta of libsass, you should comment here: https://github.com/sass/libsass/issues/943

**Comment by dalvarez** [comment]
I'm getting the same issue I believe

```
Error: You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .input-sm" on line 48 of bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_input-groups.scss
```

**Comment by justtal** [comment]
@dalvarez I got the same error :+1:

**Comment by xzyfer** [comment]
@dalvarez @justtal can you show the output of `sassc -v`? The fix for this is not in node-sass yet.

**Comment by dalvarez** [comment]
I'm not using sassc. I have an ember-cli project where I included bootstrap-sass@3.3.4 and broccoli-sass@0.6.3. I found that by downgrading my broccoli-sass to 0.3.3 (this is the version we used before upgrading) it solved our problems with compiling sass. While we wait for a fix, I'm going to see what the latest version of broccoli-sass is that we can use without breaking.

**Comment by glebm** [comment]
Closed as this is not a bootstrap-sass issue, see my comment above https://github.com/twbs/bootstrap-sass/issues/879#issuecomment-87880504

**Comment by c0achmcguirk** [comment]
Thanks for the heads up @dalvarez. I downgraded brccoli-sass to version 0.5 and that fixed it for me.
