### ISSUE TITLE
Color overrides don't work

### ISSUE THREAD

**Issue by nitsujri** [twbs/bootstrap-sass#883]
I follow the docs:

    $navbar-default-bg: #312312;
    $light-orange: #ff8c00;
    $navbar-default-color: $light-orange;
    
    @import "bootstrap-sprockets";
    @import "bootstrap";

But the background color does not change. 

https://github.com/twbs/bootstrap-sass/issues/855 - Exact issue, but there's no resolution? It's just closed.

**Comment by cvrebert** [comment]
How are you compiling bootstrap-sass?

**Comment by nitsujri** [comment]
I created an empty project and ran this, it works there, so clearly there's something wrong with the project I'm working on.

I'll update if there's any definitive findings.

Thanks cvrebert.

**Comment by jvanbaarsen** [comment]
@nitsujri Did you find out what the problem was? Running into the same issue here

**Comment by jvanbaarsen** [comment]
In my case it turns out the be because a conflicting library: "bootstrap-datepicker", which I loaded via rails-assets.

When I removed that one from my app, the colors are used that I try to override.
