### ISSUE TITLE
Incompatible units. 'px' , '%'

### ISSUE THREAD

**Issue by dompl** [twbs/bootstrap-sass#884]
I know this issue was raised before but is seems that there is no straight forward answer.

from clean install ( bower ) I am getting Incompatible units error ( _variables line 209 )

Any ideas please?

**Comment by cvrebert** [comment]
Please post the full error message and state which Sass compiler you're using.

**Comment by glebm** [comment]
This can happen when you override a variable using units that are not the same as the default.
See #750.
