### ISSUE TITLE
Javascript files of Nuget package

### ISSUE THREAD

**Issue by fredgate** [twbs/bootstrap-sass#886]
Why are the javascript files placed in the folder javascripts instead of the folder Scripts as is the case for all other packages ?
It would allow applications that use this package to remain consistent and to avoid having multiple folders.

**Comment by cvrebert** [comment]
The NuGet packages are not maintained by us; they are maintained by third parties.
Please use the "Contact Owners" link on the package's NuGet webpage to contact the actual maintainers regarding problems with their packagings. Thanks.

**Comment by cvrebert** [comment]
I'm guessing you're using https://www.nuget.org/packages/Twitter.Bootstrap.Sass , which is really https://github.com/jamez14/bootstrap-sass-nuget

**Comment by fredgate** [comment]
Yes I am using https://www.nuget.org/packages/Twitter.Bootstrap.Sass which is referencing https://github.com/twbs/bootstrap-sass as the project site.
I follow the issue to jamez14 repository.
