### ISSUE TITLE
Minor mistake in Documentation.

### ISSUE THREAD

**Issue by bigomega** [twbs/bootstrap-sass#889]
In [Sass Usage](https://github.com/twbs/bootstrap-sass#sass-1)
```sass
$navbar-default-bg: #312312;
$light-orange: #ff8c00;
$navbar-default-color: $light-orange;

@import "bootstrap";
```

Importing [bootstrap](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss) will override the custom variables by importing the variables again.
```sass
// Core variables and mixins
@import "bootstrap/variables";
@import "bootstrap/mixins";

// Reset and dependencies
@import "bootstrap/normalize";
...
```

So the custom variables will not be overridden.

#### Solution
The solution to override is to have a file that does the work of bootstap.sass and have the variables included there. Eg.,
*custom-bootstrap.sass*
```sass
// Core variables and mixins
@import "lib/bootstrap/variables";
@import "lib/bootstrap/mixins";

// Overriding variables
@import "custom-variables";

// OR
$navbar-default-bg: #312312;
$light-orange: #ff8c00;
$navbar-default-color: $light-orange;


// Reset and dependencies
@import "lib/bootstrap/normalize";
...
```

**Comment by glebm** [comment]
Importing bootstrap does not override the variables as they are declared with the `!default` qualifier.
