### ISSUE TITLE
Document Autoprefixer browserslist setting

### ISSUE THREAD

**Issue by maxwell** [twbs/bootstrap-sass#899]
I noticed that the minified bootstrap.min.css from getbootstrap.com includes a rule: 

```css
*{
  -moz-box-sizing:border-box;
}
```

to help with old Firefox shenanigans. (in this case, I was using Firefox 10 ::shudders::)

When I included

```scss
@import "bootstrap-sprockets";
@import "bootstrap";
```
in my app, that declaration was missing.

adding it back in manually made columns work as I expected.

Thanks for bootstrap-sass! It is fantastic and I love using it.

**Comment by cvrebert** [comment]
Did you setup Autoprefixer, as mentioned in the README?

**Comment by cvrebert** [comment]
Also, what are you using to compile the Sass code?

**Comment by maxwell** [comment]
Howdy!

I am just using the RoR instructions  here: 

```
gem 'bootstrap-sass', '~> 3.3.4'
gem 'sass-rails', '>= 3.2'
```

```
// "bootstrap-sprockets" must be imported before "bootstrap" and "bootstrap/variables"
@import "bootstrap-sprockets";
@import "bootstrap";
```

Do I have to do something extra to use autoprefixer? is it not vendored with the sass includes?

**Comment by glebm** [comment]
Autoprefixer is set up by default on Rails (it's a dependency of the bootstrap-sass gem), but you may need to specify the browser versions. See autoprefixer-rails documentation for reference: https://github.com/ai/autoprefixer-rails#ruby-on-rails

**Comment by cvrebert** [comment]
And the original Sass already has this particular bit of prefix code for good measure:
https://github.com/twbs/bootstrap-sass/blob/1f269b15ff91ebe35fc04959a6e38caecb19dc4f/assets/stylesheets/bootstrap/_scaffolding.scss#L12
https://github.com/twbs/bootstrap-sass/blob/1f269b15ff91ebe35fc04959a6e38caecb19dc4f/assets/stylesheets/bootstrap/mixins/_vendor-prefixes.scss#L76
so it's strange it's not in your compiled version.

**Comment by glebm** [comment]
Autoprefixer would remove it if it is not configured to support Firefox < 29. The defaults are: `> 1%, last 2 versions, Firefox ESR, Opera 12.1`, so I guess this makes sense

**Comment by cvrebert** [comment]
Perhaps we should mention autoprefixer's `browserslist` file in our docs?
