### ISSUE TITLE
Need var color for popover

### ISSUE THREAD

**Issue by clanshood** [twbs/bootstrap-sass#900]
I think you should have a variable ``$popover-color``, because you've ``$popover-bg``. So if we set up a popover with a dark color, the font become illegible.

**Comment by cvrebert** [comment]
This project is merely a translation of the upstream project: https://github.com/twbs/bootstrap
Issues not related to the Sass translation or packaging processes, such as your suggestion, should be filed with the upstream project rather than this project. Thanks.
