### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$alert-padding".

### ISSUE THREAD

**Issue by othaimeen** [twbs/bootstrap-sass#903]
I ran into this error while deploying my app:

Sass::SyntaxError: Undefined variable: "$alert-padding"

I tried following the previous issues & the stackoverflow solutions but none worked.

rails: 4.1.8
ruby 2.2

gem 'bootstrap-sass', '~> 3.2.0'
gem 'sass-rails', '~> 4.0.3'

//= require bootstrap-sprockets
//= require bootstrap

@import "bootstrap-sprockets";
@import "bootstrap";

thank you.

**Comment by thomas-mcdonald** [comment]
Your `config.assets.precompile` is incorrect and trying to compile files out of order.

**Comment by cvrebert** [comment]
Refs #654
