### ISSUE TITLE
Bootstrap isn't creating a css file when used with Grunt

### ISSUE THREAD

**Issue by grickaby** [twbs/bootstrap-sass#905]
```javascript
sass: {
            dist: {
                files: {
                    'theme/style.css': 'sass/style.scss',
                    'theme/css/bootstrap.css': 'bower_components/bootstrap-sass-official/assets/stylesheets/_bootstrap_custom.scss'
                    'theme/css/font-awesome.css': 'bower_components/fontawesome/scss/font-awesome.scss'
                },
                options: {
                    loadPath: ['bower_components/bourbon/app/assets/stylesheets']
                }
            }
        },
```

I have that in my gruntfile.js. When i run the sass command it creates the style.css file and the font-awesome.css file, however it does not create the bootstrap.css file. I've tried just processing the bootstrap sass file on its own, and it still does not create the css file. It doesn't even throw an error.

I can use @import "bootstrap"; within my main style.scss and it works, but i don't want 10,000 lines of css in my primary style sheet, thus why i am trying to create a separate css file.

The _bootstrap_custom.scss contains the same lines as _bootstrap.scss, I just commented out bootstrap functions that i don't need. I've also tried running this with the _bootstrap.scss file with the same effect, a bootstrap.css file not being created.

**Comment by glebm** [comment]
Why is bootstrap_custom specified under `bower_components`? it should be under `sass/` like `style.scss`. Also, instead of compiling it separately you could just import it in `style.scss`

**Comment by grickaby** [comment]
The reason it is under `bower_components` is because i install bootstrap using `bower install boostrap-sass-official` in Ruby. By using bower, it allows me to create a bower.json file where i can always grab the latest versions of bootstrap by typing `bower install` for a project.

``` javascript
  "main": "theme/style.css",
  "devDependencies": {
    "bootstrap-sass-official": "latest",
    "bourbon": "latest",
    "fontawesome": "latest"    
  }
```

Like i stated in my parent post, it does work using `@import "bootstrap";` in my main scss file, however it sticks all of bootstrap in my main style.css file. I don't want it to do that. I want it in it's own separate file. They only way i can do this, is to do a bower install, then copy the scss files to my sass folder, then set it up in grunt to create a separate file like so

``` javascript
        sass: {
            dist: {
                files: {
                    'theme/style.css': 'sass/style.scss'
                    'theme/css/bootstrap.css': 'sass/bootstrap.scss'
                }
            }
        },
```
The goal is automation. rather than moving files and folders around.

**Comment by cvrebert** [comment]
@glebm Isn't this just a rehash of https://github.com/gruntjs/grunt-contrib-sass/issues/180 ?
Any reason not to add a `bootstrap.scss` that consists of just `@import "_bootstrap";` ?

**Comment by cvrebert** [comment]
Ah, I see my suggestion is illegal:
> Note that you may not include a partial and a non-partial with the same name in the same directory. For example, `_colors.scss` may not exist alongside `colors.scss`.

– http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials

**Comment by glebm** [comment]
Yes, also we cannot distribute any non-partial files as this is incompatible with Compass and `sass watch` (they would copy the file into the project, which is not the setup 99% of the users want). It is trivial to add a file that does the import if one really wants a separate bootstrap.css file, so closing.
