### ISSUE TITLE
Problem with glyphicons

### ISSUE THREAD

**Issue by nfort** [twbs/bootstrap-sass#906]
Console in Chrome show

      Failed to decode downloaded font: [path for font]

**Comment by cvrebert** [comment]
Unable to reproduce. Try StackOverflow for personal support questions: stackoverflow.com/questions/tagged/twitter-bootstrap-3

**Comment by abrararies** [comment]
This is happening for me too.
@nfort did you manage to fix it?

**Comment by nfort** [comment]
@abrararies I just replaced fonts
