### ISSUE TITLE
Border Around Select Caret in IE

### ISSUE THREAD

**Issue by WonSong** [twbs/bootstrap-sass#907]
I also opened the same issue in the twbs/bootstrap and submitted a pull request: https://github.com/twbs/bootstrap/issues/16527

![Example](https://cloud.githubusercontent.com/assets/5981331/7788949/2924762c-0204-11e5-877d-372dd93d69b1.png)

Will create a pull request for this repo as well.

**Comment by cvrebert** [comment]
Closing in favor of https://github.com/twbs/bootstrap/issues/16527
A pull request in this repo should not be necessary, as the conversion script pulls in upstream changes from twbs/bootstrap automatically.
