### ISSUE TITLE
bootstrap-sprockets cancel tab event ?

### ISSUE THREAD

**Issue by StephaneJuban** [twbs/bootstrap-sass#909]
Hi,

I just wanted clarification on ```bootstrap-sprockets```.

For quite a long time I was facing an issue : [the tab event](http://getbootstrap.com/javascript/#tabs-events) was not working, nothing happened. On the raw template it works great but when I import it in a rails project, nothing.

I ended up removing one by one every "supposed errors" to finally see that, whenever I remove ```//= require bootstrap-sprockets``` from my application.js file, the tab events works again !

Any idea why this is happening ?

Thanks

**Comment by glebm** [comment]
Are you requiring both `bootstrap` and `bootstrap-sprockets`? You should be requiring just one of them but not both

**Comment by cvrebert** [comment]
@StephaneJuban Can you please answer glebm's question?

**Comment by StephaneJuban** [comment]
Sorry for the delay @cvrebert !
Yes, @glebm was right, I was using both, as soon as I removed one, everything worked fine

Thanks for the clarification :)
