### ISSUE TITLE
Missing IE-specific JS?

### ISSUE THREAD

**Issue by cviebrock** [twbs/bootstrap-sass#910]
Any reason why some of the IE-specific JS files from the Less version of Bootstrap aren't included in the Sass version?

I'm thinking specifically of https://github.com/twbs/bootstrap/blob/master/docs/assets/js/ie10-viewport-bug-workaround.js

Thanks!

**Comment by glebm** [comment]
These files are not part of Bootstrap at the moment, they are the examples from the docs.

**Comment by cvrebert** [comment]
Yes, these are part of Bootstrap's docs rather than Bootstrap per se.
