### ISSUE TITLE
IE9 missing some classes

### ISSUE THREAD

**Issue by luizfelipejr** [twbs/bootstrap-sass#912]
Hi,

I'm working with some sass variants in grid-framework, buttons, navbars and others...

Example 01:
.invoice-org-area {
    @include make-xs-column(10, $gutter: 5px);
    @include make-sm-column(5, $gutter: 20px);
    @include make-md-column(7, $gutter: 20px);
}

Example 02:
.btn {
    @include button-variant(#398bd1, #fff, #9db9d1);
}

It works in all Chrome, Firefox and Safari versions but as always in Internet Explorer 9 something broked. Looks like these css doesn't exist.

IE9 version:

![ie9](https://cloud.githubusercontent.com/assets/5906181/7928604/3ec954a4-08c9-11e5-8a8c-683724414a0e.PNG)

IE10, Chrome, Firefox and others navs...

![chrome](https://cloud.githubusercontent.com/assets/5906181/7928640/d1c84346-08c9-11e5-9217-c850fd6ff030.PNG)

I'm using html5shiv and respondjs...

I missed something?

Thanks

**Comment by cvrebert** [comment]
We can't help you without a simplified [JS Bin](http://jsbin.com) example that demonstrates the problem.
Also, be sure to verify that IE9 isn't running in IE8 mode.

**Comment by luizfelipejr** [comment]
Thanks for the answer @cvrebert :)
Follow the example link http://luizfelipejr.com.br/epay2/invoice-test.html

**Comment by cvrebert** [comment]
FYI, your page includes Respond.js twice, which can cause problems.

**Comment by cvrebert** [comment]
@luizfelipejr Please post your Sass source code.

**Comment by cvrebert** [comment]
@luizfelipejr Your page is also missing the X-UA-Compatible meta tag: http://getbootstrap.com/getting-started/#support-ie-compatibility-modes
More generally, please fix all Bootlint warnings/errors on your page; see https://github.com/twbs/bootlint#in-the-browser

**Comment by cvrebert** [comment]
@luizfelipejr And please also temporarily remove Font Awesome, just to eliminate it as a potential cause of the problem.

**Comment by luizfelipejr** [comment]
Precious tips @cvrebert :+1: 
I made some improvements but IE9 still crash. My SCSS in https://github.com/luizfelipejr/epay-tests.git

Thank you for spending your time helping me.

**Comment by cvrebert** [comment]
You're hitting IE9's selector limit; see http://stackoverflow.com/questions/9906794/internet-explorers-css-rules-limits
Closing as not a Bootstrap bug.

**Comment by luizfelipejr** [comment]
Thank you @cvrebert :) I will restructure my SASS code.
