### ISSUE TITLE
Bootstrap not being used after install

### ISSUE THREAD

**Issue by Atypique** [twbs/bootstrap-sass#917]
First of all, I am a real noobie when it comes to ruby on rails, so please bear with my lack of experience.

It comes regarding the install tutorial for ruby on rails. At one moment it says 

> Make sure the file has .scss extension (or .sass for Sass syntax). If you have just generated a new Rails app, it may come with a .css file instead. If this file exists, it will be served instead of Sass, so rename it:
> 
> ```
> $ mv app/assets/stylesheets/application.css app/assets/stylesheets/application.scss
> ```
> 
> Then, remove all the //= require and //= require_tree statements from the file. Instead, use @import to import Sass files."

And right there I have (had a problem) with my version of ruby on rails(latest at the time on this post) I didn't have the //=require but *=require and by removing those, it all falls apart.

Instead, I kept the file Application.css as it was and added a Custom.css.scss file stating the @import (Both) and it works just fine.

Well anyways, I thouht I would share this in case anybody needs a workaround, or in case that was just me misunderstanding the instructions, in which case enlightening me would be very appreciated.

**Comment by jerome2** [comment]
i have similar problem, and if just stick and follow the installation doc, this simply not works at all.
Also, sure, explication is confused.
the solution @Atypique provide works if you not have other requirement for other gems.
I would be very happy if the writer of this installation doc could do something for be more clear on what to do for install and use this gem.
Please, could you just do exactly what you write and see that this not works.
I think explain are confused and i don't know really how to do for having all working fine.
also, syntax for sass seems to not be this one (no ";"), i had to remove them....

**Comment by andrewhavens** [comment]
@Atypique @jerome2 These are the steps that you need to take:

1. Add the gem to your Gemfile:

         gem 'bootstrap-sass'

2. Run `bundle install` to install the gem.

3. Rename your `app/assets/stylesheets/application.css` to have a `.scss` extension.

4. Remove everything in the `application.scss` file.

5. Add the `@import` statements to load bootstrap, then any other files you want to import:

        @import "bootstrap-sprockets";
        @import "bootstrap";
        @import "bootstrap/theme";

        @import "custom";

**Comment by h4xnoodle** [comment]
I have the same issue as @Atypique above. @andrewhavens 's solution did not work for me (it's exactly as the docs describe anyways)

I get the error: `File to import not found or unreadable: bootstrap-sprockets.`

My application.scss looks like:

```css
@import "bootstrap-sprockets";
@import "bootstrap";
```

Removing `bootstrap-sprockets` and leaving `bootstrap` results in a similar error message s/bootstrap-sprockets/bootstrap.

```
$ ruby -v && rails -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
Rails 4.2.5
```

**Comment by glebm** [comment]
@h4xnoodle Perhaps you are using a buggy version of sprockets, sass, or sass-rails?

**Comment by chipse** [comment]
How is this not solved yet?

I'm getting the same error as h4xnoodle and a quick Google search shows that a lot of people are experiencing the same or similar issues.

I followed the guide in the repository and then when that didn't work followed the instructions as stated by andrewhavens above. 

```
$ ruby -v && rails -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Rails 5.0.0.1
```

Running the rails server works without issues but when trying to use:
```
$ sass --watch app/assets/stylesheets
```

I get the following error:
```
>>> Sass is watching for changes. Press Ctrl-C to stop.
      error app/assets/stylesheets/application.scss (Line 14: File to import not found or unreadable: bootstrap-sprockets.
Load path: /Users/chipse/workspace/Altruist/app/assets/stylesheets)
```

If I delete the `@import "bootstrap-sprockets"` the issue just moves to the next line and returns that it couldn't find "bootstrap" instead.

Here's my gemfile:
```
source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'bootstrap-sass, '~> 3.3.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'

group :development, :test do
  gem 'byebug', platform: :mir
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

Am I understanding how to use sass and foremost the "bootstrap-sass" repository? Do I not need to use the "sass --watch" command? I would be infinitely grateful if someone could explain what I'm doing wrong.

**Comment by megamit** [comment]
I noticed an issue similar to this while working with node. My ide tells me that it cannot resolve 'bootstrap' but it auto completes it to '~bootstrap-sass', which works.

**Comment by glebm** [comment]
@chipse Why are you running `sass --watch` on Rails? You don't need to, Rails will recompile files on request automatically.

**Comment by chipse** [comment]
@glebm Followed some guide that said to do so. Apparently that was wrong xD

So just to be totally clear. Will I be able to access bootstrap and all of it's content even if I get that error? When running bootstrap with php I get all the bootstrap files in my folder but when following this guide no bootstrap files shows up. Is that correct?

**Comment by yoshie902a** [comment]
I have the same issue, Boostrap-sass is not loading.

**Comment by fredosantana** [comment]
I believe removing *= require.self and *=require.tree . is only needed if the .sass extension is used instead of .scss. I've kept both on after converting to .scss and Bootstrap loads fine for me.

**Comment by ataber** [comment]
@yoshie902a FWIW, I had the same problem, and it works for me when I declare
```
gem 'bootstrap-sass', require: true
```

**Comment by davidchappy** [comment]
Simply renaming application.css to application.css.scss immediately applied Bootstrap styling for me.

**Comment by AlexCppns** [comment]
It s not working for me here, everything is underlined in red in my rubymine editor. The @imports cant be found. My gemfile:

```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'sequel-rails'
gem "pg"
gem 'awesome_print'
gem 'bootstrap-sass', require: true
gem 'bootswatch-rails'
gem 'jquery-rails'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```

**Comment by isaacjtullis** [comment]
Hey guys, I ran into this issue and couldn't for the life of me get anything to work. 

However, I finally got it to work. These are my steps. 
1) I followed exactly how to install the gem per the directions. 
2) I stopped my server
3) I ran `rake assets:precompile`
4) Re-ran my application and everything worked. 

I would love to get more feedback to see if this works. If it does, I would strongly recommend putting this inside of the docs. 

Note: I am upgrading from Bootstrap 3 to Bootstrap 4. This is a pre-existent application, I did not start from scratch.

**Comment by glebm** [comment]
You shouldn't have precompiled assets in your development environment. StackOverflow is a better place to ask.

**Comment by meatteyj** [comment]
I banged my head against the wall for a few hours trying everything mentioned above and in every other article. I couldn't believe it but rake assets:precompile then restarted my apache server and bootstrap styling was working on my app. i have my application.scss file with @import bootstrap-sprockets  @import bootstrap. I left require tree require self in the application.scss and here is my application.js 
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require_tree .

couldn't believe the rake assets:precompile command fixed it.

**Comment by marcusmertilien** [comment]
@meatteyj What do you have in your gemfile with regards to Bootstrap?
