### ISSUE TITLE
Broken: <button class="btn btn-default" type="button">Go!</button>

### ISSUE THREAD

**Issue by lgs** [twbs/bootstrap-sass#918]
`<button class="btn btn-default" type="button">Go!</button>` seems broken, 
the background color is not white as it should be and doen't have 1px solid #cccccc border as it should have, resulting (ugly) unaligned  with the rest of `class="input-group"`:

`<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
      <input type="text" class="form-control" placeholder="Search for...">
    </div>
  </div>
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </div>
  </div>
</div>`

<pre>
// Buttons: Global
$btn-font-weight: normal;
$btn-link-disabled-color: #cccccc;

// Buttons: Default
$btn-default-color: #ffffff;
$btn-default-bg: #bbbbbb;
$btn-default-border: #cccccc;
</pre>

my gems:

<pre>
ruby '2.2.2'
gem 'rails', '4.2.1'
...
gem 'sass-rails', '5.0.3'
gem 'bootstrap-sass', '3.3.4.1'
...
</pre>

**Comment by cvrebert** [comment]
@lgs Please upgrade to bootstrap-sass 3.3.5

**Comment by cvrebert** [comment]
And please check whether upstream Less-based Bootstrap (https://github.com/twbs/bootstrap) is affected.

**Comment by lgs** [comment]
I did update the gem yesterday to 3.3.5 but the affected search form still have the same bug. Is there something esle I need to do with theme already in place, or having 3.3.5 update should be enough?

**Comment by cvrebert** [comment]
@lgs 
> Is there something esle I need to do with theme already in place, or having 3.3.5 update should be enough?

What theme are you referring to?

> ( I'm not relly sure about what you mean in your second suggestion ( check whether upstream Less-based Bootstrap is affected ). I currently don't use less at all ...

Let me simplify a bit. If you enter your variable values into http://getbootstrap.com/customize and then use the downloaded CSS instead of your Sass-compiled Bootstrap, does the problem still persist?

**Comment by lgs** [comment]
@cvrebert

... I just dropped off all sass-rails and bootstrap-sass ... and the rest of Rails 4.2.1 asset pipeline and replaced with CDN Bootstrap 3.3.5:

<pre>
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js
</pre>

evrithing work fine and I'm not facing the search form bug ...

**Comment by cvrebert** [comment]
@lgs If you enter your variable values into http://getbootstrap.com/customize and then use the downloaded CSS instead of CDN Bootstrap, does the problem persist?

**Comment by cvrebert** [comment]
Closing due to lack of response.
