### ISSUE TITLE
Needs sass >=3.3.0 in order to use @at-root

### ISSUE THREAD

**Issue by Subtletree** [twbs/bootstrap-sass#920]
bootstrap-sass currently has sass >= 3.2.19 as a dependency.

`_glyphicons.scss` uses `@at-root` which is a feature new to sass 3.3.0.

I've been trying for hours to fix my icons after updating bootstrap-sass but not the sass gem.

**Comment by fofr** [comment]
As a point 3.3.x release this has caught us out too. The change was automatically picked up by some of our apps (`~> 3.3.3`) that are also pinned to sass 3.2.19, and it was the lack of glyphicons that highlighted the problem.

https://github.com/alphagov/govuk_admin_template/issues/70

It will also affect this rule:
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_responsive-utilities.scss#L21

**Comment by glebm** [comment]
Just pushed rubygem v3.3.5.1 to address the incorrect dependency.
