### ISSUE TITLE
v3.3.5 : glyphicons are not rendered 

### ISSUE THREAD

**Issue by zedalaye** [twbs/bootstrap-sass#921]
I upgraded bootstrap-sass to 3.3.5 and some glyphicons, like "glyphicon-shopping-cart" are not displayed anymore. I had to revert to 3.3.4.1 to get them back.

This is how it looks after update :

![way_bad](https://cloud.githubusercontent.com/assets/7906/8220651/df950e08-1555-11e5-9b81-f3a7099c6b51.png)

And this is how it looked before update :

![way_ok](https://cloud.githubusercontent.com/assets/7906/8220661/f75780ac-1555-11e5-8b96-0f244872a89c.png)

My Gemfile :

 ```Gemfile
...
gem 'rails', '4.1.11'
...
gem 'haml'
gem 'sass', '~> 3.2.19'
gem 'sass-rails', '~> 4.0.3'
gem 'compass-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
...
gem 'jquery-rails'
gem 'bootstrap-sass', '= 3.3.4.1' # Bug with some glyphicons in 3.3.5
gem 'autoprefixer-rails'
gem 'country_select'
gem 'bootstrap-datepicker-rails'
gem 'd3_rails'
gem 'x-editable-rails'
gem 'jquery-datatables-rails'
gem 'select2-rails'
gem 'momentjs-rails'
gem 'famfamfam_flags_rails', :git => 'https://github.com/ipolza/famfamfam_flags_rails.git'
gem 'dropzonejs-rails'
```

And my app/assets/stylesheets/application.scss

```application.scss
@import 'bootstrap-sprockets';
@import 'bootstrap';
@import 'bootstrap-datepicker3.css';
@import 'devise_bootstrap_views';
@import 'editable/bootstrap-editable';
@import 'dataTables/jquery.dataTables';
@import 'dataTables/bootstrap/3/jquery.dataTables.bootstrap';
@import 'select2';
@import 'select2-bootstrap';
@import 'famfamfam-flags';
@import 'dropzone/dropzone';
...
```

**Comment by Subtletree** [comment]
Your sass gem needs to be 3.3.0 to work with the latest bootstrap-sass

I would change your gemfile to:

    gem 'sass'
    gem 'sass-rails'

and run `bundle update sass-rails`

Issue #920 should resolve this dependency issue.

**Comment by zedalaye** [comment]
You are right. Upgrading sass did the trick.
