### ISSUE TITLE
For Rails form generator : data-toggle='buttons' with Latest Bootstrap 3.3.5

### ISSUE THREAD

**Issue by kntmrkm** [twbs/bootstrap-sass#923]
I don't know I think this issue is specific for Rails.

But bootstrap version up have broken `button toggle's function`.

I have a code like below.

```
<div data-toggle="buttons">
      <div class="checkbox">
        <label class="btn btn-block btn-facebook " for="post_post_facebook">
          <input name="post[post_facebook]" type="hidden" value="0" />
          <input class="hidden" type="checkbox" value="1" name="post[post_facebook]" id="post_post_facebook" /> Share with Facebook</label>
      </div>
</div>
```
[![Gyazo](http://i.gyazo.com/e6692c1a3ff463b6f4237f690a8b79af.gif)](http://gyazo.com/e6692c1a3ff463b6f4237f690a8b79af)

The code works with version 3.3.4.1.

But, With 3.3.5. After click button. Toggle function does not works.

So, I have removed `<input name="post[post_facebook]" type="hidden" value="0" />` .

Then Toggle function works.

I think `data-toggle='buttons'` does not work with Rails form generator.

Is not?

**Comment by cvrebert** [comment]
@kntmrkm Please report JavaScript issues upstream to https://github.com/twbs/bootstrap/issues
Thanks!
