### ISSUE TITLE
Update to button-variant mixin in v3.3.5 breaks sass compiler

### ISSUE THREAD

**Issue by stewartknapman** [twbs/bootstrap-sass#926]
After pulling down the latest version (3.3.5) I started getting this error when compiling my sass:
http://monosnap.com/image/FeYl1CPoBaeuRbXp435ufQGNZjCmgk

We are building a Shopify theme so I am concatenating the bootstrap sass files with my own styles and then sending them up to Shopify to compile them so I am at the mercy of their compiler. I am told that they are using Sass 3.2.6. However I don't know any other details of their setup other than that.

I tracked the issue down to this line in this commit: https://github.com/twbs/bootstrap-sass/commit/f95e617f9d165c85a7d9fe658f56b53c5b756dcb#diff-cb59fd159d76bb7ad52350045010767fR31

Commenting out that one line fixes the error I'm seeing and everything compiles fine.

I guess the issue is I don't actually know if it is your converter that is creating whacky sass, or if it's doing it correctly and Shopify's version of Sass is just to old to handle it. But I figured it needed addressing and this was the best place to start.

My work around for now is to roll back to version 3.3.4.

**Comment by cvrebert** [comment]
We now require Sass >=3.3.x. See #922.

**Comment by stewartknapman** [comment]
@cvrebert thanks. I'll forward that info on.
