### ISSUE TITLE
Mixed Content Issue When Requesting my Site Over HTTPS

### ISSUE THREAD

**Issue by moeabdol** [twbs/bootstrap-sass#928]
I get a mixed content issue as following:
The page at 'https://xxxx.com' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700'.

I understand that the font is part of normalize.css which is included in bootstrap by default; however, I want to disable this font as I'm not using it anywhere in my rails app. I actually serve my own fonts.

I wonder if there is a way to disable the font. Thanks

**Comment by cvrebert** [comment]
> I understand that the font is part of normalize.css

No, it's not. Open Sans isn't used by Bootstrap either. Must be a problem in some other stylesheet you're using.

**Comment by moeabdol** [comment]
@cvrebert 
![asdf](https://cloud.githubusercontent.com/assets/974790/8418201/35443fa0-1eba-11e5-8e99-e4da9934fad2.png)

**Comment by cvrebert** [comment]
@moeabdol `jquery-scrollbar` isn't part of Bootstrap either. Grep our source if you don't believe me.

**Comment by moeabdol** [comment]
@cvrebert you're absolutely right! I found the import inside another stylesheet. Thank you for clearing things up.
