### ISSUE TITLE
Need to specify sprockets version with rails 4.0.1

### ISSUE THREAD

**Issue by kenmazaika** [twbs/bootstrap-sass#929]
I'm running rails 4.0.1 with twitter bootstrap.  

On the latest version (3.3.5.1) I need to downgrade sprockets in order for glyph icons to work:
http://take.ms/fE7R9

https://github.com/cryogenx/nomster/compare/master...kenmazaika:fixed

Is Rails 4.0.1 support deprecated with the latest version of this gem?

**Comment by manuelpradal** [comment]
:+1:

**Comment by glebm** [comment]
Seems like an sprockets issue. Nothing has changed with regards to glyphicons since bootstrap-sass v3.3.3.

**Comment by andrewhavens** [comment]
I am still having this issue and I am not sure what the solution is. Does anyone know?

**Comment by sethk** [comment]
This might be related to #961.
