### ISSUE TITLE
Glyphicon not working if you set your $icon-font-path

### ISSUE THREAD

**Issue by mamartins** [twbs/bootstrap-sass#936]
Icons are not showing after I've set my own $icon-font-path to point to the correct path they are installed in version 3.3.5. Checked out version 3.3.4 and it was working

**Comment by redevorob** [comment]
Im getting the same, checked against previous version of bootstrap and all seems the same setup (that one is working ok). Just using the latest version of bootstrap 3.3.5.

Got the 5 "glyphicons-halflings-regular" files in "fonts" folder within my template.

Then got this setting in the "_variables.scss" file...
$icon-font-path: if($bootstrap-sass-asset-helper, "bootstrap/", "../fonts/") !default;

**Comment by mamartins** [comment]
Yes, I checked out 3.3.4 and I've done a diff and didn't found nothing suspicious

**Comment by glebm** [comment]
What is your environment? Are you using Compass, Rails, node.js, Sass Ruby or libsass, and what versions?

**Comment by redevorob** [comment]
Hi Glebm
I used the Scout app, with not being too up on the command line. Seems to be the latest version of Scout 0.7.1.

I noticed that adding this to the main .scss stylesheet overrides what is there and the glyphicons show...
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular') format('svg');
}

Had a look at what it was overriding that was this here...
@at-root {
  @font-face {
    font-family: 'Glyphicons Halflings';
    src: url(/stylesheets/fonts/bootstrap/glyphicons-halflings-regular.eot);
    src: url(/stylesheets/fonts/bootstrap/glyphicons-halflings-regular.eot?#iefix) format("embedded-opentype"), url(/stylesheets/fonts/bootstrap/glyphicons-halflings-regular.woff2) format("woff2"), url(/stylesheets/fonts/bootstrap/glyphicons-halflings-regular.woff) format("woff"), url(/stylesheets/fonts/bootstrap/glyphicons-halflings-regular.ttf) format("truetype"), url(/stylesheets/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format("svg");
}
}

Do you know where abouts the "/stylesheets/fonts/bootstrap/" is being brought in from?

thanks

**Comment by mamartins** [comment]
in my case angular,  bootstrap sass installed with bower

**Comment by glebm** [comment]
@redevorob scout uses Sass 3.2.1 and was last updated in 2012. You could try using Koala instead http://koala-app.com/.

@mamartins Make sure you are on the latest version of node-sass.

**Comment by mamartins** [comment]
I'm using gulp-sass 1.3.3 that, according to its  changeling uses node-sass 2.0 final

**Comment by glebm** [comment]
@mamartins Try updating to gulp-sass v2.0.3 and node-sass v3.2.0.

**Comment by redevorob** [comment]
That seems to have sorted it for me, using koala to compile the SASS. thanks ;)

**Comment by mamartins** [comment]
updated and it worked! Thanks
