### ISSUE TITLE
Some tags are missing for releases

### ISSUE THREAD

**Issue by JuanitoFatas** [twbs/bootstrap-sass#937]
Hello bootstrap-sass,

There are new releases (E.g. v3.3.4.1, v3.3.5.1) on rubygems.org but respective version tags are missing. Could you please push those tags so that people can leverage [GitHub compare view](https://github.com/blog/612-introducing-github-compare-view) to know what's been changed across two releases like this example:

https://github.com/rails/rails/compare/v4.1.10...v4.1.11

So people can see commits between these two versions.

Thanks!

**Comment by thomas-mcdonald** [comment]
@glebm - are these not tagged because it messes with bower or should I run through and tag?

**Comment by glebm** [comment]
@thomas-mcdonald Yes, these are rubygem-only tags and they would break Bower
