### ISSUE TITLE
Caret missing in bootstrap dropdown

### ISSUE THREAD

**Issue by pevers** [twbs/bootstrap-sass#938]
I switched versions from 3.3.4 to 3.3.5 and suddenly the carets on dropdown buttons disappeared. Removing the IE hack in https://github.com/twbs/bootstrap-sass/blob/next/assets/stylesheets/bootstrap/_dropdowns.scss#L14 fixed it but I'm sure there must be a better option in

**Comment by cvrebert** [comment]
@pevers What version of IE are you using? Does the problem still occur if you use the CSS from http://www.bootstrapcdn.com/ ?

**Comment by cvrebert** [comment]
Closing due to lack of response.
