### ISSUE TITLE
Version compatibility with Rails 3.2.22? 

### ISSUE THREAD

**Issue by dborovsky** [twbs/bootstrap-sass#939]
Hi

After bundle update display error:

ActionView::Template::Error (Undefined variable: "$font-size-base".
  (in /home/dima/myapp/app/app/assets/stylesheets/welcome.sass))

and other variables. 

I use Rails 3.2.22, and now bootstrap-sass (3.3.5.1)

I think problem in version gem. Right? What version of gem use?

**Comment by glebm** [comment]
Please see the discussion in https://github.com/twbs/bootstrap-sass/issues/764.

TLDR:

Rails 3.2 is no longer supported. However, you could try with the following gems:

```ruby
# Backported asset pipeline gems for Bootstrap compatibility:
gem 'sprockets-rails', '=2.0.0.backport1'
gem 'sprockets', github: 'DenisColeman/sprockets-2.2.2.backport'
gem 'sass-rails', github: 'guilleiguaran/sass-rails', branch: 'backport'
```

---

Disclaimer, from the sass-rails backport author in https://github.com/twbs/bootstrap-sass/issues/764#issuecomment-63518837:

> I'm going to say this as clearly as possible: using a random repo with no history, that purports to be a patched version of Sprockets, is a **REALLY bad idea™**.

The same goes for the sass-rails backport.

**Comment by dborovsky** [comment]
wfine with 'bootstrap-sass' version '2.1.1.0'
