### ISSUE TITLE
Sinatra and bootstrap-sass

### ISSUE THREAD

**Issue by charlesfonlupt** [twbs/bootstrap-sass#940]
Is it possible to install bootstrap-sass in Sinatra without using Compass? Thanks a lot for your help.

**Comment by cvrebert** [comment]
I presume it would be basically the same as the Foundation examples in http://recipes.sinatrarb.com/p/asset_management/sinatra_assetpack

**Comment by cvrebert** [comment]
If you run into a more specific problem, let us know.
