### ISSUE TITLE
grunt and bootstrap

### ISSUE THREAD

**Issue by NikonMcFly** [twbs/bootstrap-sass#941]
Im getting this problem when i run grunt 

>> Undefined variable: "$btn-border-radius-base".
>>   Line 20  Column 110  bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_buttons.scss

**Comment by thomas-mcdonald** [comment]
What does your Gruntfile look like? I think you're probably compiling all the partials by mistake.

**Comment by NikonMcFly** [comment]
sorry about the wait...I fully don't know whats going on? 
This is how my Gruntfile is set up
  sass: {  
    dist: { 
      files: { 
        'style/css/main.css': 'style/sass/main.scss'   // 'destination': 'source'
      }
    }
  }
when I import _bootstrap.scss I get I stated above in my terminal

**Comment by NikonMcFly** [comment]
I think its supposed to make a .sass-cache file. Also I am using npm

**Comment by pearcake** [comment]
Try use https://github.com/sindresorhus/grunt-sass builder instead of grunt-contrib-sass.  And dont forget to npm install --save-dev load-grunt-tasks.

**Comment by NikonMcFly** [comment]
No that didnt help. It has something to do with creating .sass-cache file and compiling @import "bootstrap";

**Comment by cvrebert** [comment]
Works fine for me: https://gist.github.com/cvrebert/e453cf70678c7dce5a83

**Comment by cvrebert** [comment]
Closing due to lack of response and unreproducibility.
