### ISSUE TITLE
mixin transform doesn't have -moz-

### ISSUE THREAD

**Issue by zeakd** [twbs/bootstrap-sass#942]
all transform mixin in venvdor-prefixes.scss
* scale
* scaleX
* scaleY
* ...
* rotateY

doesn't have -moz- that bootstrap have.

**Comment by glebm** [comment]
Prefixes are added by autoprefixer automatically. Please have a look at your autoprefixer version and configuration. Note that Firefox supports these unprefixed since v16.

**Comment by zeakd** [comment]
oh, I didn't know about it. 
Then, is there no reason to use these vendor-prefix mixins?

**Comment by joseorihuela** [comment]
Correct, you do not need to use the mixins. Check out the Gruntfile in the project for the autoprefixer task.

**Comment by zeakd** [comment]
Thanks! :0
