### ISSUE TITLE
Need to avoid "Uncaught Error: Bootstrap's JavaScript requires jQuery" when using webpack

### ISSUE THREAD

**Issue by tutuca** [twbs/bootstrap-sass#943]
I have the a build using grunt-webpack.

`Gruntfile.js`:

    module.exports = function (grunt) {
        grunt.initConfig({
            pkg: grunt.file.readJSON('package.json'),
            webpack: {
                main: {
                    entry: {
                    main: "./main.js",
                },
                output: {
                    path: ".",
                    filename: "out.js",
                },
              },
            },
        });
        grunt.loadNpmTasks('grunt-webpack');
        grunt.registerTask('default', ['webpack']);
    };

`package.json`:

    {
      "name": "prueba",
      "main": "out.js",
      "dependencies": {
        "jquery":"2.*",
        "bootstrap-sass":"*"
      },
      "devDependencies": {
        "grunt": "*",
        "webpack": "*",
        "grunt-webpack": "*",
        "grunt-contrib-concat": "*"
      }
    }

`main.js`:

    var jQuery = require("jquery");
    require('bootstrap-sass');
    jQuery(function () {
        alert("loaded");
    });

This fails to load with the following error:

    Uncaught Error: Bootstrap's JavaScript requires jQuery

Which come from the fact that bootstrap expects jquery to be loaded before itself in no-conflict mode.

Aparently the `require` invocation I do in the first is not enough.
Is there anything I can do in my current setup that could ensure that bootstrap loads correctly?

**Comment by glebm** [comment]
What is the version of jQuery as specified in `jQuery.fn.jquery`?

**Comment by tutuca** [comment]
>>> jQuery.fn.jquery
    "2.1.4"

**Comment by glebm** [comment]
`jQuery` needs to be a property on the global object for it to be accessible by other modules:

```js
window.jQuery = require("jquery");
```

**Comment by tutuca** [comment]
Great! Adding that statement right before requiring bootstrap did the trick!

Thanks for the quick response!
