### ISSUE TITLE
Some glyphicons not loading

### ISSUE THREAD

**Issue by obromios** [twbs/bootstrap-sass#946]
I have problem with some glyphicons not working. I am using bootstrap-sass 3.3.5. For instance these work

    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>

and these do not work

    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>

In my ```application.css.scss``` file I am loading bootstrap-sprockets before bootstrap, i.e.

    @import "bootstrap-sprockets";
    @import "bootstrap";

I am using ```rails 4.2.2```, ```sass-rails', '~> 4.0.4'```, ```'sprockets-rails', '>=2.1.4'```. Why is this not working?

Here is the relevant excerpt from the assets when I inspect the element chrome web tools:

    /* line 24, /Users/Chris/.rvm/gems/ruby-2.1.6@golf_mentor/gems/bootstrap-sass-3.3.5/assets/stylesheets/bootstrap/_glyphicons.scss */
    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }

    /* line 37, /Users/Chris/.rvm/gems/ruby-2.1.6@golf_mentor/gems/bootstrap-sass-  3.3.5/assets/stylesheets/bootstrap/_glyphicons.scss */
    .glyphicon-asterisk:before {
      content: "\2a";
    }
    
    /* line 38, /Users/Chris/.rvm/gems/ruby-2.1.6@golf_mentor/gems/bootstrap-sass-    3.3.5/assets/stylesheets/bootstrap/_glyphicons.scss */
    .glyphicon-plus:before {
      content: "\2b";
    }
This [question](http://stackoverflow.com/questions/31468298/some-glyphicons-not-working-with-boostrap-sass) was asked on Stackoverflow 10 days ago without answer, so maybe it is an issue with this gem.

**Comment by glebm** [comment]
The icons do work (e.g. see https://glebm.github.io/gulp-webpack-react-bootstrap-sass-template/).

Please try clearing the cache:

```
rake tmp:cache:clear  
rake assets:clean
```

**Comment by obromios** [comment]
I stopped my server, executed the two rake commands and then restarted the server.  I am still getting the same results, i.e. the star and asterisk glyphicons render properly, whereas heart and the thumbs-up render as empty black bordered boxes about the size of a bounding box for the two that do render.

I believe you that this works for most cases, but so far, not for my case.  Is a possible cause is that I am also loading an old version of the bootstrap somewhere, and if so, how do I check for this?

**Comment by glebm** [comment]
Make sure you are not serving a version of glyphicons from your project:
```
find . | grep glyphicons
```

**Comment by obromios** [comment]
Thank you, I did find some other bootstrap files, and deleted them.  I then stopped the server, cleared the cache with the two commands above, and restarted server.  However, the problem is persisting. I tried clearing the chrome browser's cache of file and pictures, and still no luck. I tried safari which gave the same result. Firefox was slightly different, in the square boxes that are being displayed for the heart and thumbs-up glyphicon, it had in the text E125 and E005.

I did ``` find . | grep glyphicons``` again and saw
```
./tmp/cache/assets/development/sass/f7d4d235b94ce2fd030546c66c6091e35d1ad1ca/_glyphicons.scssc
```
You can see in my initial post that when I inspect the elements source I am shown lines from the bootstrap-sass gem. Is there any way I can follow this trail further to see where the icons are loading from?

**Comment by obromios** [comment]
Another piece of information is that when I looked through the app, I found in the public folder, many files like
```
application-79ce58e54e439a9c8ddddf493571f366.css
```
which looked like caches for application.css and many images files.  These were not being cleared by the clear cache commands you gave me, and I do not know why they were there. I deleted them all but it did not solve the problem.

**Comment by williamboman** [comment]
I'm having the same problem when compiling the sass with `node-sass@2.1.1`. It looks like the `@at-root` directive is included in the css output, like;

```css
@at-root {
    @font-face {
      font-family: 'Glyphicons Halflings';
      ...
    }
}
```

**Comment by williamboman** [comment]
So, an update - `bootstrap-sass` does not compile properly on `node-sass@<3.2` (i.e. `libsass@<3.2.5`).

**Comment by glebm** [comment]
@obromios This happens if you run `rake assets:precompile` in development.

**Comment by glebm** [comment]
@williamboman This is documented in https://github.com/twbs/bootstrap-sass#c-bower.

**Comment by williamboman** [comment]
@glebm Yep, thanks :smile:!

**Comment by obromios** [comment]
I solved the problem by upgrading everything I could think of. The configuration that worked was
```
gem 'sprockets-rails', '>=2.1.4'
gem 'sass-rails', '~> 5.0.1'
gem 'compass-rails', '~> 2.0.4'
gem 'bootstrap-sass', '~> 3.3.5'
```
Not sure which did it, but I was very pleased to see those glyphicons.

**Comment by tfwright** [comment]
I had the same issue using 3.3.5. Downgrading to 3.3.1 fixed it, as did @obromios's configuration above.

**Comment by vsymguysung** [comment]
+1

**Comment by diegosky1** [comment]
+1 for @tfwright, I struggled for days with this. My final and successful gem config is:
```
gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0.1'
gem 'bootstrap-sass', '~> 3.3.1'
```
I'm not using neither sprocket-rails, nor compass-rails gems as @obromios does.

**Comment by joelbarker2011** [comment]
Upgrading the `sass-rails` gem to 5.x did it for me.

Although I had updated my bundle yesterday, some other gems were updated as a result of this:

    Installing sass 3.4.20 (was 3.2.19)
    Installing concurrent-ruby 1.0.0
    Installing tilt 2.0.2 (was 1.4.1)
    Installing sprockets 3.5.2 (was 2.12.4)
    Installing bootstrap-sass 3.3.6 (was 3.3.5)
    Installing sprockets-rails 3.0.0 (was 2.3.3)
    Installing sass-rails 5.0.4 (was 4.0.5)
