### ISSUE TITLE
Alerts not dismissed since 3.3.0

### ISSUE THREAD

**Issue by nholiphant** [twbs/bootstrap-sass#949]
Works
alert.js prior to 3.3.0 contains the line --> $parent = $this.hasClass('alert') ? $this : $this.parent()
 
Doesn't work
alert.js 3.3.x contains the line -->  $parent = $this.closest('.alert')

**Comment by cvrebert** [comment]
Non-Sass-specific bugs should be filed upstream at https://github.com/twbs/bootstrap instead of here. Thanks!

**Comment by nholiphant** [comment]
Hi Chris, I'm puzzled since the bug is in the bootstrap-sass gem, why would
it needed to be reported upstream?

Regards, Nevin

**Comment by cvrebert** [comment]
The bug doesn't truly lie in bootstrap-sass.
bootstrap-sass uses the **exact same JavaScript** (modulo [one unimportant file](https://github.com/twbs/bootstrap-sass/blob/master/assets/javascripts/bootstrap-sprockets.js)) as upstream Bootstrap; it doesn't make any changes to it. So any bug in the JavaScript is equally applicable to, and must be a bug in, upstream Bootstrap itself.

**Comment by nholiphant** [comment]
Thanks Chris
