### ISSUE TITLE
Wrong path in 2.3.2 bootstrap.scss file?

### ISSUE THREAD

**Issue by TomiS** [twbs/bootstrap-sass#950]
I find it difficult to successfully import all bootstrap scss files using the following file: https://github.com/twbs/bootstrap-sass/blob/v2.3.2.2/vendor/assets/stylesheets/bootstrap/bootstrap.scss 

I'm trying to use it like this

```
// File: App.scss (or similar)

// Application variables
@import './Application/scss/variables';

// Bootstrap
@import './vendor/bootstrap-sass/vendor/assets/stylesheets/bootstrap.scss';

// Application styles
@import './Application/scss/application.scss';
```

When I run sass with grunt, I get an error:
```
$ grunt sass:dev
Running "sass:dev" (sass) task
>> file to import not found or unreadable: bootstrap/variables
```

This seems to happen because all imports are prefixed with ```bootstrap/``` path even if all the imported files are located in the same folder. Is this a bug or am I missing something? Everything works if I just remove the prefixes.

I would provided a pull request that removes all bootstrap prefixes but it seems there is no 2.3 branch available.

**Comment by glebm** [comment]
v2.3.2.2 only officially supports Rails. Back then, Rails asset pipeline did not know how to import relative files, all imports had to be relative to one of the specified roots, thus the prefixes. This is not something we can fix in this repo as the change would break it for all users of old Rails. If you are stuck on v2.3.2.2 then I suggest you hack it together by forking and replacing the path.

**Comment by TomiS** [comment]
Thanks for answer @glebm, I understand. Closing ticket.
