### ISSUE TITLE
bower install modifies bower jQuery

### ISSUE THREAD

**Issue by dudewad** [twbs/bootstrap-sass#952]
Pretty weird, here. My bower distribution of jQuery 1.11.3 which is declared in my dependencies is being removed when I try to remove bootstrap-sass as well.

>bower uninstall bootstrap-sass --save
bower uninstall     bootstrap-sass
bower uninstall     jquery

It uninstalls jQuery from the target bower_components directory but leaves it in my bower.json. Following this up with bower install again simply reinstalls jQuery and everything is fine, but adding/removing modules explicitly should not add and remove other modules when there's an explicit dependency.

Here are my dependencies so you can try to repro:

  "dependencies": {
    "greensock": "~1.17.0",
    "jQuery": "~1.11.3",
    "angular": "~1.4.3"
  }

**Comment by glebm** [comment]
The package name should be `jquery`, not `jQuery`.

**Comment by dudewad** [comment]
Well now don't I feel silly.
Okay thanks :)

**Comment by glebm** [comment]
Bower is the silly one for not telling you that something is wrong.

**Comment by dudewad** [comment]
That IS a good point; it still installed jQuery without complaining. If they aren't doing case-sensetive checking then it really should throw a warning at the least, which it didn't -- if you have jQuery in your bower.json it'll install it as jQuery in the dependencies folder. I should log that as a bug...
