### ISSUE TITLE
@at-root syntax requires sass 3.3

### ISSUE THREAD

**Issue by nasmorn** [twbs/bootstrap-sass#953]
The @at-root syntax is used e.g. for the glyphicons font declaration.
It would be helpful if the dependencies reflected this in some way.
It was introduced in commit b01ab4942233bd7316a0634472e1243b13fb9f46

**Comment by glebm** [comment]
The rubygem version does depend on Sass 3.3+. As for other environments, there is no explicit dependency as there are multiple compilers the user can pick from. For node.js, this is mentioned in the Readme: https://github.com/twbs/bootstrap-sass#c-bower

**Comment by nasmorn** [comment]
I am talking about the ruby gem version. I see now that it is properly declared I am sorry. Bundler did not alert me to the issue though. This is a bit strange.

**Comment by newdark** [comment]
Thanks did not know @at-root was only in sass 3.3. Seams that for some reason the gem did not upgrade to sass 3.3 when we got the newer version of bootstrap.
