### ISSUE TITLE
4.0 Alpha!

### ISSUE THREAD

**Issue by cannikin** [twbs/bootstrap-sass#955]
What's the plan?

**Comment by FabianKoestring** [comment]
As far is i can see the `v4-dev` branch is shipped with an scss folder.

https://github.com/twbs/bootstrap/tree/v4-dev

**Comment by JanStevens** [comment]
I've already started to pack the scss folder for rails in a gem in this MR:

https://github.com/twbs/bootstrap-sass/pull/954

You can play around with it, if you find any issues please let me know :)

Regards

**Comment by nofxx** [comment]
Waiting for this!

**Comment by glebm** [comment]
See https://github.com/twbs/bootstrap-rubygem
