### ISSUE TITLE
namespace class for all of bootstrap not working due to & selector

### ISSUE THREAD

**Issue by kueda** [twbs/bootstrap-sass#958]
Bootstrap uses the `&` selector quite a bit, often trailing, like this:

```sass
.jumbotron {
  .container &,
  .container-fluid & {
    ...
  }
}
```

Which should generate CSS like 

```css
.container .jumbotron, .container-fluid .jumbotron { ... }
```

If you want to nest all bootstrap classes under a single namespace class, the generally-recommended solution is to do something like this:

```sass
.my-wrapper {
  @import "bootstrap-sprockets";
  @import "bootstrap";
}
```

However, given the way the bootstrap-sass is currently compiled, that means you get CSS like

```css
.container .my-wrapper .jumbotron, .container-fluid .my-wrapper .jumbotron { ... }
```

which ends up not selecting anything. This problem is nicely described and addressed at http://stackoverflow.com/questions/19793508/compiling-issue-in-bootstrap-3-with-namespace, but the solution requires storing a compiled copy of bootstrap instead of having the convenience of the bootstrap-sass gem. 

Is there a workaround I'm missing, or is this something that can be fixed in this gem?

**Comment by glebm** [comment]
There is no workaround that you are missing that I know of. I would merge a PR that works around this on the converter level, e.g. by replacing all nested selectors with explicit selectors, but this would be quite complicated to implement.

**Comment by glebm** [comment]
I search everywhere this could be mentioned and couldn't find anything, so I raised the issue on the Sass tracker.

**Comment by glebm** [comment]
A workaround example: https://github.com/twbs/bootstrap/pull/17352

**Comment by kueda** [comment]
Thanks for checking it out, @glebm. Curious to see if your PR gets integrated, not sure how common a use-case this is.

**Comment by cvrebert** [comment]
@glebm Can we close this in favor of https://github.com/twbs/bootstrap/pull/17364 & https://github.com/sass/sass/issues/1817 ?

**Comment by glebm** [comment]
Closing. However, if anyone would like to implement the workaround from https://gist.github.com/chriseppstein/476836b0488e293b258e on the converter level, I will merge it.
