### ISSUE TITLE
Missing assets from sass version

### ISSUE THREAD

**Issue by MichaelMallett** [twbs/bootstrap-sass#963]
How come the sass version is missing ie10-viewport-bug-workaround.js? (Plus whatever else I haven't discovered yet).

It's really confusing to have these kinds of differences and seemingly no reason for it.

**Comment by cvrebert** [comment]
That file is not part of Bootstrap itself. It's just used in the docs and examples. See http://getbootstrap.com/getting-started/#support-ie10-width
