### ISSUE TITLE
Glyphicons not found in JQuery

### ISSUE THREAD

**Issue by maxflex** [twbs/bootstrap-sass#978]
I'm getting these messages in console whenever I use a `glyphicon`

<img width="1440" alt="screen shot 2015-10-25 at 13 37 51" src="https://cloud.githubusercontent.com/assets/5883414/10715190/a6a22f08-7b1d-11e5-8094-ee3e65bea1cf.png">

The icon is rendered correctly though, so I there's no problem regarding CSS. The error is in JQuery, particularly this line of code:
`support.inlineBlockNeedsLayout = val = div.offsetWidth === 3;`

**Comment by cvrebert** [comment]
I guarantee you the error doesn't actually lie with jQuery.
Please try asking your troubleshooting question on StackOverflow. Thanks!
