### ISSUE TITLE
page-header none type styling in type.scss

### ISSUE THREAD

**Issue by michaud** [twbs/bootstrap-sass#979]
in bootstrap-sass/assets/stylesheets/bootstrap/_type.scss on line 135 there is a page-header class that shouldn't be in the type styling. And why does bootstrap have a page-header styling anyway? you always need to overrule this style for every site you make...

**Comment by cvrebert** [comment]
Please direct issues not directly related to the Sass translation or packaging to the upstream project: https://github.com/twbs/bootstrap
