### ISSUE TITLE
Is it possible to not include button CSS?

### ISSUE THREAD

**Issue by gregblass** [twbs/bootstrap-sass#980]
I'm finding myself fighting against the button CSS in every app I make. Overriding it gets really ugly when inspecting it all. I'd love to just start with a clean slate for my buttons. Is it possible to not include certain parts of the bootstrap CSS, (or the other way around, only include what I want, individually)?

**Comment by must-not-code** [comment]
https://github.com/twbs/bootstrap-sass#configuration

**Comment by gregblass** [comment]
Thank you very much!
