### ISSUE TITLE
Gradient mixin not working in IE9

### ISSUE THREAD

**Issue by nikhil-toobler** [twbs/bootstrap-sass#981]
Why the gradient mixin not working in IE9, in _gradients.scss already added a line for "IE9 and down".

**Comment by cvrebert** [comment]
@nikhil-toobler Please post an example that demonstrates the problem.

**Comment by nikhil-toobler** [comment]
@cvrebert  this is the demo link, plz have a look :- http://codepen.io/nikhil8krishnan/full/gaErKr/

**Comment by cvrebert** [comment]
It works fine. Your page is just insanely tall, so you have to scroll to notice the gradient.
Counterexample with reasonable height: http://codepen.io/cvrebert/full/avMNQM/
Screenshot of counterexample as proof:
<img width="1075" alt="proof" src="https://cloud.githubusercontent.com/assets/419884/11234703/90156baa-8d7f-11e5-81d3-ed3b6c2028d4.png">

**Comment by nikhil-toobler** [comment]
ok, it working after giving a reasonable height... thanks @cvrebert :+1:
