### ISSUE TITLE
ISSUE in loading asset on local machine with Prodcution ENViorment 

### ISSUE THREAD

**Issue by rabnawazPikesSoft** [twbs/bootstrap-sass#983]
"NetworkError: 500 Internal Server Error  - http://localhost:3000/assets/compiled/theme"

this type or error i faced even  i dont know what is this error every thing is working fine i load assets many time precompiled it also still facing such an error

**Comment by cvrebert** [comment]
We are unable to provide assistance with troubleshooting such a generic error.
