### ISSUE TITLE
Problem with Glypicons / URL

### ISSUE THREAD

**Issue by mikeemike85** [twbs/bootstrap-sass#988]
I've got the site "www.mutpol.de".

If you use www.mutpol.de everything is fine ...
If you use mutpol.de only, the Icons (for example print, etc) are not working any more ...

It should be a URI issue, but I can't finde anything ... !

**Comment by cvrebert** [comment]
This bug tracker is only for bugs and feature requests.
For personal troubleshooting/support questions, please ask on one of the venues listed on https://github.com/twbs/bootstrap#community instead. Thanks.
