### ISSUE TITLE
Compiled CSS has errors according to W3C CSS Validator

### ISSUE THREAD

**Issue by binarykitchen** [twbs/bootstrap-sass#989]
For example

```
.Bs a[href]:after 	Parse Error attr(href) ")"; 
.Bs abbr[title]:after 	Parse Error attr(title) ")"; 
 .Bs input[type="radio"], .Bs input[type="checkbox"] 	Value Error : margin-top Too many values or values are not recognized : 1px \000009 
.Bs .form-control-feedback 	Property pointer-events doesn't exist : none 
```

... and many more. Can't we ensure CSS validity here?

**Comment by cvrebert** [comment]
Not if you care about Internet Explorer support.
Please refer to http://getbootstrap.com/getting-started/#support-validators

**Comment by binarykitchen** [comment]
@cvrebert fair enough - although we have dropped IE support here and an error-free version of bootstrap would be very welcome

**Comment by cvrebert** [comment]
There are other hacks for targeting Safari and Firefox. :cry: All browsers suck, just in different ways.

**Comment by cvrebert** [comment]
> although we have dropped IE support here

Count yourself among a small and extremely fortunate minority :grin:

**Comment by binarykitchen** [comment]
not really, many more are doing this too since edge is doing a good job so far
