### ISSUE TITLE
Compilation results in outputting font-path.

### ISSUE THREAD

**Issue by EvanCarroll** [twbs/bootstrap-sass#992]
Problems with bootstrap-sass, compiling it with `gulp-sass`. When ever I compile using 

```javascript
gulp.src('sass/app.scss')                                            
  .pipe(sass({                                                       
    includePaths: ['node_modules/bootstrap-sass/assets/stylesheets'] 
  }).on('error', sass.logError))                                     
  .pipe(gulp.dest('./public/dist/'))                                 
;                                                                    
```

And, targeting this..
```javascript
@import "_bootstrap-sprockets"
@import "_bootstrap";         
```

I get

    src: url(font-path("bootstrap/glyphicons-halflings-regular.eot"));

However, the `font-path` thing isn't in the precompiled boostrap

    src: url('../fonts/glyphicons-halflings-regular.eot');

Why does mine have `font-path`? Is this a sass function, and if so why isn't it calling it and how do I get an error and how do I resolve this error?

Here is my post on StackOverflow about this http://stackoverflow.com/questions/34169023/bootstrap-sass-is-outputting-calls-to-font-path

**Comment by cvrebert** [comment]
What tool/framework are you using to compile bootstrap-sass?

**Comment by EvanCarroll** [comment]
I'm using gulp-sass. I updated the question.

**Comment by cvrebert** [comment]
> Why does mine have font-path?

Because if an undefined function is referenced in SCSS code, Sass outputs the call verbatim; see http://stackoverflow.com/a/27589115

> Is this a sass function

It is a library function that is defined by Sprockets, exported to Sass.

>, and if so why isn't it calling it

Presumably you aren't using Sprockets. If so, then you shouldn't be doing `@import "_bootstrap-sprockets"` since that's only applicable if you're using Sprockets.

**Comment by EvanCarroll** [comment]
Ah the docs didn't actually say what Sprockets was, and it said to use if you want icons.

**Comment by cvrebert** [comment]
I believe the instructions you're referring to are in sections of the documentation whose heading indicate that they're Rails-specific.

**Comment by cvrebert** [comment]
If removing that import doesn't solve things, let us know.
