### ISSUE TITLE
How to remove Glyphicons font?

### ISSUE THREAD

**Issue by banesto** [twbs/bootstrap-sass#997]
Hi!

Is there a way to disable inclusion of Glyphicons Halflings font as I am using FontAwesome [gem](https://github.com/FortAwesome/font-awesome-sass)?

**Comment by cvrebert** [comment]
You'd copy or edit `_bootstrap.scss` and remove [the `@import "bootstrap/glyphicons";` line](https://github.com/twbs/bootstrap-sass/blob/70f6d4de61771e65be8ff1ec23c50d33c447ce01/assets/stylesheets/_bootstrap.scss#L14) from the file.

In the future, please use StackOverflow for how-to questions. Thanks.

**Comment by cvrebert** [comment]
See also https://github.com/twbs/bootstrap-sass#sass . Glyphicons are just another component.

**Comment by banesto** [comment]
Thank you!
