### ISSUE TITLE
container-fixed mixin not respecting width variables

### ISSUE THREAD

**Issue by bwarman** [twbs/bootstrap-sass#998]
The container-fixed mixin, when used, doesn't take into account the various screen size variables that are included in the variables file. It only takes into account the gutter size. Adding this to the mixin solves the problem.

  @media (min-width: $screen-sm-min) {
    width: $container-sm;
  }
  @media (min-width: $screen-md-min) {
    width: $container-md;
  }
  @media (min-width: $screen-lg-min) {
    width: $container-lg;
  }

**Comment by cvrebert** [comment]
Methinks you want the `.container` class instead:
https://github.com/twbs/bootstrap-sass/blob/e15eef6a47ab94b15f80d44507859e4bc08ae965/assets/stylesheets/bootstrap/_grid.scss#L10

**Comment by cvrebert** [comment]
In any case, this doesn't seem to be caused by the Sass translation process, so it'd belong upstream at https://github.com/twbs/bootstrap/issues instead.
