### ISSUE TITLE
Dependency on jQuery should be specified

### ISSUE THREAD

**Issue by thewoolleyman** [twbs/bootstrap-sass#999]
bootstrap-sass depends on Jquery at runtime, but this dependency is not specified in package.json (nor are any others, are there any?)

Thanks,
-- Chad

**Comment by glebm** [comment]
There are no other runtime dependencies. The upstream only began specifying jQuery as a dependency in Bootstrap 4.

**Comment by thewoolleyman** [comment]
OK, but shouldn't jquery be specified as a dependency?  Otherwise people must explicitly put it in their package.json to avoid runtime failures, even if they don't use jQuery at all as a direct dependency.

In other words, even though it's "upstream", the jQuery dependency is still in the code of this library (e.g. https://github.com/twbs/bootstrap-sass/blob/5ad0746ff394aa810e730eefec69f65036450e66/assets/javascripts/bootstrap/alert.js#L94), thus jquery should be listed as a dependency in your package.json.

Or am I missing something?

**Comment by thomas-mcdonald** [comment]
@thewoolleyman Depends if you think it's legit to use Bootstrap without the javascript functionality, in which case a dependency on jQuery would be superfluous.

**Comment by thewoolleyman** [comment]
OK, good point.  I actually don't plan on using any of the jQuery functionality myself.  It's just for the plugins, right?

I guess the real problem is that the upstream should be split into two libraries, one which has no jquery dependency and one which does.  

Would that approach make sense for you too, to make the dependencies explicit?

**Comment by fatso83** [comment]
Then there's the thing that Bootstrap does not depend on the actual jQuery library, but the API of jQuery. Hence the possibility of using Zepto or other minimal jQuery versions. Explicitly having a dependency on jQuery would then include an unneeded package if you chose to bundle Zepto.

**Comment by cvrebert** [comment]
@twbs/sass Perhaps we should escalate this upstream and just follow any changes they make in response to the issue?
